# Generated by Django 6.1 on 2026-08-11 19:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_accountingperiod'),
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=50)),
                ('supplier_reference', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('partly_paid', 'Partly paid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='organisations.organisation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='contacts.contact')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.bill')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='accounting.account')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['organisation', 'status'], name='purchases_b_organis_118982_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['organisation', 'supplier'], name='purchases_b_organis_afa156_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['organisation', 'issue_date'], name='purchases_b_organis_785421_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('organisation', 'bill_number'), name='unique_bill_number_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bill_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='bill_line_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='bill_line_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='bill_line_tax_non_negative'),
        ),
    ]
