# Generated by Django 6.1 on 2026-08-12 08:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_journalentry_source_type'),
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
        ('purchases', '0002_supplierpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_credited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('partly_applied', 'Partly applied'), ('applied', 'Applied'), ('void', 'Void')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit', to='accounting.journalentry')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credits', to='purchases.bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credits_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credits', to='organisations.organisation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credits', to='contacts.contact')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('applied_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_allocations_applied', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='purchases.bill')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='purchases.suppliercredit')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credit_allocations', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCreditLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.suppliercredit')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_lines', to='accounting.account')),
            ],
        ),
        migrations.AddIndex(
            model_name='suppliercredit',
            index=models.Index(fields=['organisation', 'status'], name='purchases_s_organis_100360_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercredit',
            index=models.Index(fields=['organisation', 'supplier'], name='purchases_s_organis_03d7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercredit',
            index=models.Index(fields=['organisation', 'issue_date'], name='purchases_s_organis_b175c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercredit',
            constraint=models.UniqueConstraint(fields=('organisation', 'credit_number'), name='unique_supplier_credit_number_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_credit_allocation_amount_positive'),
        ),
    ]
