# Generated by Django 6.1 on 2026-08-12 09:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_journalentry_source_type'),
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
        ('purchases', '0003_bill_amount_credited_suppliercredit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercredit',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.CreateModel(
            name='SupplierRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refund', to='accounting.journalentry')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refunds_received', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refunds_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_refunds', to='organisations.organisation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refunds', to='contacts.contact')),
                ('supplier_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='purchases.suppliercredit')),
            ],
            options={
                'ordering': ['-refund_date', '-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='purchases_s_organis_326b6a_idx'), models.Index(fields=['organisation', 'supplier'], name='purchases_s_organis_ca5dee_idx'), models.Index(fields=['organisation', 'refund_date'], name='purchases_s_organis_dafbce_idx'), models.Index(fields=['organisation', 'supplier_credit'], name='purchases_s_organis_6f17ce_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_refund_amount_positive')],
            },
        ),
    ]
