# Generated by Django 6.1 on 2026-08-12 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
        ('purchases', '0004_suppliercredit_amount_refunded_supplierrefund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_made', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.bill'),
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='purchases.bill')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payment_allocations', to='organisations.organisation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='purchases.supplierpayment')),
            ],
            options={
                'indexes': [models.Index(fields=['organisation', 'payment'], name='purchases_s_organis_1de8d9_idx'), models.Index(fields=['organisation', 'bill'], name='purchases_s_organis_ad1e03_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_allocation_amount_positive')],
            },
        ),
    ]
