# Generated by Django 6.1 on 2026-08-12 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_backfill_supplier_payment_allocations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_allocations_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
    ]
