# Generated by Django 6.1 on 2026-08-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_maximum_quantity_product_minimum_quantity_and_more'),
        ('purchases', '0008_bill_approved_at_bill_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='inventory_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_bill_line', to='inventory.inventorytransaction'),
        ),
    ]
