# Generated by Django 6.1 on 2026-08-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_purchaseorder_purchaseorderline_and_more'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='tax_rate_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='tax.taxrate'),
        ),
        migrations.AddField(
            model_name='suppliercreditline',
            name='tax_rate_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_lines', to='tax.taxrate'),
        ),
    ]
