# Generated by Django 6.1 on 2026-09-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_bill_base_currency_amount_bill_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercreditallocation',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='reversal_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
