# Generated by Django 6.1 on 2026-09-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_allocation_carrying_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='suppliercreditline',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
