# Generated by Django 6.1 on 2026-09-12 01:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_billline_tax_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='suppliercreditline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
