# Generated by Django 6.1 on 2026-08-12 13:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0011_alter_journalentry_source_type'),
        ('organisations', '0002_organisation_require_separate_approver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('sales_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('track_inventory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_of_goods_sold_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cost_products', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_products', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organisations.organisation')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_for_sale', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county_state', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='organisations.organisation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('opening', 'Opening'), ('purchase_receipt', 'Purchase receipt'), ('sale_issue', 'Sale issue'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('return_in', 'Return in'), ('return_out', 'Return out')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('transfer', 'Transfer'), ('opening', 'Opening'), ('return', 'Return')], max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='organisations.organisation')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_posted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movement', to='inventory.stockmovement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organisation', 'status'], name='inventory_p_organis_8dbd12_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organisation', 'product_type'], name='inventory_p_organis_e94060_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organisation', 'code'], name='inventory_p_organis_d97c44_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organisation', 'code'), name='unique_product_code_per_organisation'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['organisation', 'status'], name='inventory_w_organis_58e377_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organisation', 'code'), name='unique_warehouse_code_per_organisation'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organisation', 'product', 'warehouse'], name='inventory_s_organis_fae660_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organisation', 'status', 'movement_date'], name='inventory_s_organis_9c1c98_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'),
        ),
    ]
