# Generated by Django 6.1 on 2026-08-12 22:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organisations', '0002_organisation_require_separate_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=8, max_digits=24),
        ),
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('average_unit_cost', models.DecimalField(decimal_places=8, max_digits=24)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layer', to='inventory.stockmovement')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cost_layers', to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['effective_date', 'created_at', 'id'],
                'indexes': [models.Index(fields=['organisation', 'product', 'warehouse', 'effective_date'], name='inventory_i_organis_7c956f_idx')],
            },
        ),
    ]
