# Generated by Django 6.1 on 2026-08-13 01:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_journalentry_source_type'),
        ('contacts', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_total_cost_and_more'),
        ('organisations', '0002_organisation_require_separate_approver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_inventory_products', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_date', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('counting', 'Counting'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts_created', to=settings.AUTH_USER_MODEL)),
                ('offset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='organisations.organisation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('adjustment_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_line', to='inventory.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.product')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stockcount')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase_receipt', 'Purchase receipt'), ('sales_issue', 'Sales issue'), ('transfer', 'Warehouse transfer'), ('customer_return', 'Customer return'), ('supplier_return', 'Supplier return')], max_length=30)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=8, max_digits=24)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_document_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transaction', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('debit_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='accounting.account')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_inventory_transfers', to='inventory.warehouse')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='organisations.organisation')),
                ('primary_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='primary_inventory_transaction', to='inventory.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.product')),
                ('secondary_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_inventory_transaction', to='inventory.stockmovement')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'transaction_type', 'reference'), name='unique_inventory_transaction_reference'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_transaction_quantity_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.UniqueConstraint(fields=('organisation', 'reference'), name='unique_stock_count_reference'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('stock_count', 'product'), name='unique_stock_count_product'),
        ),
    ]
