# Generated by Django 6.1 on 2026-08-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_maximum_quantity_product_minimum_quantity_and_more'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_purchase_tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_purchase_products', to='tax.taxrate'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_sales_tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_sales_products', to='tax.taxrate'),
        ),
    ]
