# Generated by Django 6.1 on 2026-08-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_default_purchase_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening'), ('purchase_receipt', 'Purchase receipt'), ('sale_issue', 'Sale issue'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('return_in', 'Return in'), ('return_out', 'Return out'), ('production_material_issue', 'Production material issue'), ('production_material_return', 'Production material return'), ('production_completion', 'Production completion'), ('production_scrap', 'Production scrap')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('transfer', 'Transfer'), ('opening', 'Opening'), ('return', 'Return'), ('manufacturing', 'Manufacturing')], max_length=20),
        ),
    ]
