import { useEffect, useRef, useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { useAuth } from '../../store/AuthContext';
import { api } from '../../services/api';
import { normaliseApiError } from '../../services/apiError';
import { getOrganisationToday } from '../../utils/dateUtils';
import { ONBOARDING_STEPS, newOnboarding, changeOnboardingCountry, validateOnboardingStep, blankRegistration } from '../../utils/onboarding';
import '../../styles/publicAccess.css';
export default function OnboardingPage(){
 const auth=useAuth(),navigate=useNavigate(),guard=useRef(false),heading=useRef(null),idempotency=useRef(crypto.randomUUID());
 const [form,setForm]=useState(()=>newOnboarding(getOrganisationToday('Africa/Accra'))),[step,setStep]=useState(0),[options,setOptions]=useState(null),[busy,setBusy]=useState(false),[completing,setCompleting]=useState(false),[error,setError]=useState(''),[fieldErrors,setFieldErrors]=useState({}),[confirmed,setConfirmed]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{if(!auth.isAuthenticated)return;let live=true;api.get('onboarding/').then(result=>{if(live){setOptions({...result.options,policy_required:result.policy_required});setForm(current=>({...current,...result.data}));setStep(result.step);}}).catch(e=>{if(live)setError(normaliseApiError(e));});return()=>{live=false;};},[auth.isAuthenticated]);
 useEffect(()=>{heading.current?.focus();},[step]);
 if(auth.isLoading)return <p>Restoring your session…</p>;
 if(!auth.isAuthenticated)return <Navigate to="/login" replace/>;
 if(!auth.user?.is_email_verified)return <Navigate to="/resend-verification" replace/>;
 if(auth.organisations.length&&!busy&&!completing)return <Navigate to="/select-organisation" replace/>;
 const change=(name,value)=>{setForm(f=>({...f,[name]:value}));setSaved(false);setFieldErrors(e=>({...e,[name]:''}));};
 const registration=(name,value)=>{setForm(f=>({...f,registration:{...f.registration,[name]:value}}));setFieldErrors(e=>({...e,[name]:''}));};
 const field=(name,label,type='text',required=false)=><label key={name}>{label}<input name={name} type={type} required={required} value={form[name]??''} onChange={e=>change(name,type==='number'?Number(e.target.value):e.target.value)} aria-invalid={Boolean(fieldErrors[name])} aria-describedby={fieldErrors[name]?`error-${name}`:undefined}/>{fieldErrors[name]&&<small id={`error-${name}`} className="access-error">{fieldErrors[name]}</small>}</label>;
 async function save(exit=false){if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await api.put('onboarding/',{data:form,step});setSaved(true);if(exit)await auth.logout();}catch(e){setError(normaliseApiError(e));}finally{guard.current=false;setBusy(false);}}
 async function submit(e){e.preventDefault();const errors=validateOnboardingStep(step,form);setFieldErrors(errors);if(Object.keys(errors).length){setError('Review the highlighted fields.');return;}setError('');if(step<7){setStep(step+1);return;}if(!confirmed||guard.current)return;guard.current=true;setBusy(true);try{const result=await api.post('onboarding/',{data:form,idempotency_key:idempotency.current,confirmed:true});setCompleting(true);await auth.bootstrapAuth();await auth.selectOrganisation(result.organisation);navigate('/welcome',{replace:true});}catch(e){setError(normaliseApiError(e));}finally{guard.current=false;setBusy(false);}}
 return <main className="onboarding-page public-access"><header><Link className="auth-brand" to="/onboarding">Ledgify</Link><button type="button" disabled={busy} onClick={()=>save(true)}>Save and exit</button></header><div className="onboarding-layout"><aside><h1>Set up your organisation</h1><ol className="onboarding-progress">{ONBOARDING_STEPS.map((label,index)=><li key={label} aria-current={step===index?'step':undefined}><span>{index<step?'✓':index+1}</span>{label}</li>)}</ol><p>Saved setup stays private to your account. Financial records are created only after your final confirmation.</p></aside><section className="onboarding-card"><p className="access-help">Step {step+1} of 8</p><h2 ref={heading} tabIndex={-1}>{ONBOARDING_STEPS[step]}</h2>{error&&<p role="alert" className="auth-error">{error}</p>}{saved&&<p role="status">Setup progress saved.</p>}{!options?<p>Loading setup options…</p>:<form onSubmit={submit}>
 {step===0&&<><p>Start with your business details, review your regional and accounting settings, then confirm creation.</p><p>Have an invitation? Open the invitation email and accept it with this verified account instead of creating another organisation.</p><p>Opening balances are optional. Tax setup may stay draft for accountant review.</p>{options.policy_required&&(options.policies.terms_url&&options.policies.privacy_url?<label className="access-check"><input type="checkbox" required checked={Boolean(form.terms_accepted)} onChange={e=>setForm(f=>({...f,terms_accepted:e.target.checked,terms_version:options.policies.terms_version,privacy_version:options.policies.privacy_version}))}/><span>I agree to the <a href={options.policies.terms_url} target="_blank" rel="noreferrer">Terms</a> and <a href={options.policies.privacy_url} target="_blank" rel="noreferrer">Privacy Policy</a> before creating this organisation.</span></label>:<p role="alert">Current policies are unavailable. Contact support before creating an organisation.</p>)}</>}
 {step===1&&<><div className="access-grid">{field('legal_name','Legal business name','text',true)}{field('trading_name','Trading name (optional)')}{field('business_type','Business type','text',true)}{field('registration_number','Registration number (optional)')}{field('tax_number','Tax identification number (optional)')}{field('email','Business email','email',true)}{field('phone','Phone number','tel',true)}{field('address_line_1','Address','text',true)}{field('address_line_2','Address line 2 (optional)')}{field('city','City / town','text',true)}{field('region','Region / state')}{field('postal_code','Postal code (where applicable)')}{field('ghana_post_gps',form.country_code==='GH'?'GhanaPost GPS / digital address (optional)':'Digital address (optional)')}{field('website','Website (optional)','url')}</div><p className="access-help">{form.country_code==='GH'?'Ghana phone numbers may use +233 or local forms such as 024… .':'Use a local or international phone number for your business.'} Enter your actual registered business details.</p><label>Logo (optional, PNG/JPEG up to 250 KB)<input type="file" accept="image/png,image/jpeg" onChange={e=>{const file=e.target.files[0];if(!file)return;if(file.size>250*1024||!['image/png','image/jpeg'].includes(file.type)){setError('Choose a PNG or JPEG under 250 KB.');return;}const reader=new FileReader();reader.onload=()=>change('logo_data',reader.result);reader.readAsDataURL(file);}}/></label>{form.logo_data&&<img className="onboarding-logo" src={form.logo_data} alt="Business logo preview"/>}</>}
 {step===2&&<><label>Country (two-letter code)<input name="country_code" list="onboarding-countries" minLength={2} maxLength={2} required value={form.country_code} onChange={e=>setForm(f=>changeOnboardingCountry(f,e.target.value.toUpperCase(),options.defaults))}/><datalist id="onboarding-countries"><option value="GH">Ghana</option><option value="GB">United Kingdom</option><option value="US">United States</option><option value="NG">Nigeria</option><option value="KE">Kenya</option></datalist></label><div className="access-grid">{field('base_currency','Base currency (ISO code)','text',true)}<label>Timezone<select required value={form.timezone} onChange={e=>change('timezone',e.target.value)}><option value="">Select timezone</option>{options.timezones.map(zone=><option key={zone}>{zone}</option>)}</select></label>{field('locale','Locale','text',true)}</div><p>{form.country_code==='GH'?'Recommended for Ghana: GHS, Africa/Accra and en-GH.':'Review the currency, timezone and locale for your business. Ghana tax configuration is not installed for other countries.'}</p><label className="access-check"><input type="checkbox" checked={form.regional_confirmed} onChange={e=>change('regional_confirmed',e.target.checked)}/>I have reviewed the currency and timezone.</label>{fieldErrors.regional_confirmed&&<p className="access-error">{fieldErrors.regional_confirmed}</p>}</>}
 {step===3&&<><div className="access-grid">{field('financial_year_start_month','Financial-year start month (1–12)','number',true)}{field('first_year_start','First financial-year start','date',true)}{field('first_year_end','First financial-year end','date',true)}{field('accounting_start_date','Accounting start / conversion date','date',true)}</div><label>Reporting basis<select value={form.reporting_basis} onChange={e=>change('reporting_basis',e.target.value)}><option value="ACCRUAL">Accrual</option></select></label><p>An explicit open period will cover the accounting start through year end. Posted financial-year settings require controlled changes later.</p></>}
 {step===4&&<><div className="onboarding-choices">{[['ghana_small_business','Recommended Ghana small-business chart'],['general','Recommended general / international chart'],['import_later','Import an existing Chart of Accounts'],['minimal','Start with a minimal structure']].filter(([key])=>key!=='ghana_small_business'||form.country_code==='GH').map(([value,label])=><label key={value}><input type="radio" name="chart" value={value} checked={form.chart===value} onChange={()=>change('chart',value)}/>{label}</label>)}</div>{form.chart==='import_later'&&<p>Required controls are created now. Use the existing Excel preview/import workflow after setup to add your accounts.</p>}<h3>Accounts to be created</h3><ul className="onboarding-account-list">{options.charts[form.chart]?.map(row=><li key={row.code}><strong>{row.code} · {row.name}</strong><span>{row.account_type}{row.is_system_account?' · Required protected control':''}</span></li>)}</ul><p>Ghana tax controls are created only when you explicitly activate a Ghana tax profile.</p></>}
 {step===5&&<><label>Tax structure<select value={form.tax_structure} onChange={e=>setForm(f=>({...f,tax_structure:e.target.value,registration:blankRegistration(),activate_tax:false,tax_confirmation:false}))}>{form.country_code==='GH'&&<option value="GHANA_GRA">Ghana – GRA Tax Structure</option>}<option value="CUSTOM_INTERNATIONAL">Custom / International</option><option value="NO_TAX">No Tax</option></select></label>{field('tax_effective_from','Tax profile effective date','date',true)}{form.country_code==='GH'&&form.tax_structure==='GHANA_GRA'?<>{[['vat_registered','VAT registered','vat_effective_from'],['wht_agent','Income-tax withholding agent','wht_effective_from'],['vat_wht_agent','VAT-withholding agent','vat_wht_effective_from'],['paye_employer','PAYE employer','paye_effective_from']].map(([flag,label,date])=><fieldset key={flag}><legend>{label}</legend><label className="access-check"><input type="checkbox" checked={form.registration[flag]} onChange={e=>registration(flag,e.target.checked)}/>This registration applies to the organisation</label>{form.registration[flag]&&<label>Effective date<input type="date" required value={form.registration[date]||''} onChange={e=>registration(date,e.target.value)}/>{fieldErrors[date]&&<small className="access-error">{fieldErrors[date]}</small>}</label>}</fieldset>)}{['tin','vat_registration_number'].map(key=><label key={key}>{key==='tin'?'TIN':'VAT registration number'}<input required={form.registration.vat_registered} value={form.registration[key]||''} onChange={e=>registration(key,e.target.value)}/>{fieldErrors[key]&&<small className="access-error">{fieldErrors[key]}</small>}</label>)}{form.registration.vat_registered&&<div className="access-notice"><strong>Ghana VAT reference {options.ghana_reference.version}</strong><p>Effective {options.ghana_reference.effective_from}. {options.ghana_reference.components.map(c=>`${c.name} ${c.rate}%`).join(' + ')}. All components use the same taxable value.</p></div>}<p>Unverified WHT schedules and GRA upload adapters remain unavailable. PAYE is tracking only. GRA E-VAT is not connected.</p></>:<p>Configure organisation-specific tax rates in Tax Settings after creation. No Ghana rates will be installed for international organisations.</p>}<label className="access-check"><input type="checkbox" checked={form.activate_tax} onChange={e=>change('activate_tax',e.target.checked)}/>Activate this reviewed tax profile during creation</label>{form.activate_tax?<label className="access-check"><input type="checkbox" checked={form.tax_confirmation} onChange={e=>change('tax_confirmation',e.target.checked)}/>I confirm these registrations, effective dates and tax-account mappings. Activate only the declared obligations.</label>:<p>The tax profile will remain draft for accountant review. Transactions requiring an active tax profile remain blocked until it is reviewed and activated.</p>}{fieldErrors.tax_confirmation&&<p className="access-error">{fieldErrors.tax_confirmation}</p>}</>}
 {step===6&&<div className="onboarding-choices">{[['zero','Start a new business with zero opening balances'],['enter_now','Enter opening balances after setup'],['import_later','Import data later'],['accountant','Get help from an accountant']].map(([value,label])=><label key={value}><input type="radio" name="opening_choice" checked={form.opening_choice===value} onChange={()=>change('opening_choice',value)}/>{label}</label>)}<p>No opening journal is created by this wizard. Optional tasks never prevent completing setup.</p></div>}
 {step===7&&<><dl className="onboarding-review">{[['Legal business',form.legal_name],['Country',form.country_code],['Currency / timezone',`${form.base_currency} · ${form.timezone}`],['Financial year',`${form.first_year_start} – ${form.first_year_end}`],['Accounting start',form.accounting_start_date],['Chart of Accounts',form.chart.replaceAll('_',' ')],['Tax structure',form.tax_structure.replaceAll('_',' ')],['Tax profile',form.activate_tax?'Explicit activation requested':'Draft for review'],['Opening data',form.opening_choice.replaceAll('_',' ')]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>The organisation, owner membership, first financial year, open period, accounts and tax profile are created together. Review your choices before confirming.</p><label className="access-check"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these details and authorise organisation creation.</label></>}
 <footer className="onboarding-actions">{step>0&&<button type="button" disabled={busy} onClick={()=>{setStep(step-1);setError('');}}>Back</button>}<button type="button" disabled={busy} onClick={()=>save(false)}>Save progress</button><button className="access-primary" type="submit" disabled={busy||step===7&&!confirmed||step===0&&options.policy_required&&!form.terms_accepted}>{busy?'Saving…':step===7?'Create organisation':'Continue'}</button></footer></form>}</section></div></main>;
}
