# Generated by Django 6.1 on 2026-08-09 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_class', models.CharField(choices=[('bank', 'Bank'), ('current_asset', 'Current Asset'), ('fixed_asset', 'Fixed Asset'), ('receivable', 'Accounts Receivable'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long-term Liability'), ('payable', 'Accounts Payable'), ('equity', 'Equity'), ('sales', 'Sales'), ('other_income', 'Other Income'), ('cost_of_sales', 'Cost of Sales'), ('operating_expense', 'Operating Expense'), ('other_expense', 'Other Expense')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_system_account', models.BooleanField(default=False)),
                ('allow_manual_journals', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organisations.organisation')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['organisation', 'account_type'], name='accounting__organis_037c44_idx'), models.Index(fields=['organisation', 'account_class'], name='accounting__organis_d2dd9d_idx'), models.Index(fields=['organisation', 'status'], name='accounting__organis_b49a94_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'code'), name='unique_account_code_per_organisation')],
            },
        ),
    ]
