# Generated by Django 6.1 on 2026-08-10 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_journalline_and_more'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_sequence', to='organisations.organisation')),
            ],
        ),
    ]
