# Generated by Django 6.1 on 2026-08-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_flow_category',
            field=models.CharField(choices=[('operating', 'Operating activities'), ('investing', 'Investing activities'), ('financing', 'Financing activities'), ('cash', 'Cash and cash equivalents'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=30),
        ),
    ]
