# Generated by Django 6.1 on 2026-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_account_cash_flow_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('bank', 'Bank'), ('adjustment', 'Adjustment'), ('customer_credit', 'Customer Credit'), ('supplier_credit', 'Supplier Credit')], default='manual', max_length=20),
        ),
    ]
