# Generated by Django 6.1 on 2026-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('bank', 'Bank'), ('adjustment', 'Adjustment'), ('customer_credit', 'Customer Credit'), ('supplier_credit', 'Supplier Credit'), ('customer_refund', 'Customer Refund'), ('bad_debt', 'Bad Debt'), ('supplier_refund', 'Supplier Refund')], default='manual', max_length=20),
        ),
    ]
