# Generated by Django 6.1 on 2026-08-12 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_journalentry_source_type'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_class',
            field=models.CharField(choices=[('bank', 'Bank'), ('current_asset', 'Current Asset'), ('fixed_asset', 'Fixed Asset'), ('receivable', 'Accounts Receivable'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long-term Liability'), ('payable', 'Accounts Payable'), ('equity', 'Equity'), ('retained_earnings', 'Retained earnings'), ('sales', 'Sales'), ('other_income', 'Other Income'), ('cost_of_sales', 'Cost of Sales'), ('operating_expense', 'Operating Expense'), ('other_expense', 'Other Expense')], max_length=30),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('bank', 'Bank'), ('adjustment', 'Adjustment'), ('customer_credit', 'Customer Credit'), ('supplier_credit', 'Supplier Credit'), ('customer_refund', 'Customer Refund'), ('bad_debt', 'Bad Debt'), ('supplier_refund', 'Supplier Refund'), ('bank_transfer', 'Bank Transfer'), ('year_end_close', 'Year-end Close')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('profit_or_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_years_closed', to=settings.AUTH_USER_MODEL)),
                ('closing_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_year_closed', to='accounting.journalentry')),
                ('closing_reversal_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_year_reopened', to='accounting.journalentry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYearHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('closed', 'Closed'), ('reopened', 'Reopened')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('accounting_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_year_history', to='accounting.journalentry')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='accounting.financialyear')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_year_history', to='organisations.organisation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_year_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriodHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('locked', 'Locked'), ('reopened', 'Reopened')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='accounting.accountingperiod')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_period_history', to='organisations.organisation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_period_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['organisation', 'accounting_period'], name='accounting__organis_6f1e05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financialyear',
            index=models.Index(fields=['organisation', 'status'], name='accounting__organis_fa608a_idx'),
        ),
        migrations.AddIndex(
            model_name='financialyear',
            index=models.Index(fields=['organisation', 'start_date', 'end_date'], name='accounting__organis_8b872f_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='financial_year_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='financialyear',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_financial_year_name_per_organisation'),
        ),
        migrations.AddIndex(
            model_name='financialyearhistory',
            index=models.Index(fields=['organisation', 'financial_year'], name='accounting__organis_df7c71_idx'),
        ),
    ]
