# Generated by Django 6.1 on 2026-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_account_account_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('bank', 'Bank'), ('adjustment', 'Adjustment'), ('customer_credit', 'Customer Credit'), ('supplier_credit', 'Supplier Credit'), ('customer_refund', 'Customer Refund'), ('bad_debt', 'Bad Debt'), ('supplier_refund', 'Supplier Refund'), ('bank_transfer', 'Bank Transfer'), ('year_end_close', 'Year-end Close'), ('inventory_adjustment', 'Inventory adjustment')], default='manual', max_length=20),
        ),
    ]
