# Generated by Django 6.1 on 2026-08-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('bank', 'Bank'), ('adjustment', 'Adjustment'), ('customer_credit', 'Customer Credit'), ('supplier_credit', 'Supplier Credit'), ('customer_refund', 'Customer Refund'), ('bad_debt', 'Bad Debt'), ('supplier_refund', 'Supplier Refund'), ('bank_transfer', 'Bank Transfer'), ('year_end_close', 'Year-end Close'), ('inventory_adjustment', 'Inventory adjustment'), ('inventory_receipt', 'Inventory receipt'), ('inventory_issue', 'Inventory issue'), ('customer_return', 'Customer return'), ('supplier_return', 'Supplier return'), ('stock_count', 'Stock count'), ('fixed_asset_acquisition', 'Fixed asset acquisition'), ('depreciation', 'Depreciation'), ('fixed_asset_disposal', 'Fixed asset disposal'), ('payroll', 'Payroll'), ('payroll_payment', 'Payroll payment'), ('fx_revaluation', 'FX revaluation'), ('fx_realised', 'Realised FX')], default='manual', max_length=30),
        ),
    ]
