# Generated by Django 6.1 on 2026-08-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_journalentry_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('bank', 'Bank'), ('adjustment', 'Adjustment'), ('customer_credit', 'Customer Credit'), ('supplier_credit', 'Supplier Credit'), ('customer_refund', 'Customer Refund'), ('bad_debt', 'Bad Debt'), ('supplier_refund', 'Supplier Refund'), ('bank_transfer', 'Bank Transfer'), ('year_end_close', 'Year-end Close'), ('inventory_adjustment', 'Inventory adjustment'), ('inventory_receipt', 'Inventory receipt'), ('inventory_issue', 'Inventory issue'), ('customer_return', 'Customer return'), ('supplier_return', 'Supplier return'), ('stock_count', 'Stock count'), ('fixed_asset_acquisition', 'Fixed asset acquisition'), ('depreciation', 'Depreciation'), ('fixed_asset_disposal', 'Fixed asset disposal'), ('payroll', 'Payroll'), ('payroll_payment', 'Payroll payment'), ('fx_revaluation', 'FX revaluation'), ('fx_realised', 'Realised FX'), ('manufacturing_material_issue', 'Manufacturing material issue'), ('manufacturing_completion', 'Manufacturing completion'), ('manufacturing_cost', 'Manufacturing cost'), ('manufacturing_variance', 'Manufacturing variance')], default='manual', max_length=30),
        ),
    ]
