# Generated by Django 6.1 on 2026-08-27 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_journalentry_source_type'),
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('bank', 'Bank'), ('adjustment', 'Adjustment'), ('customer_credit', 'Customer Credit'), ('supplier_credit', 'Supplier Credit'), ('customer_refund', 'Customer Refund'), ('bad_debt', 'Bad Debt'), ('supplier_refund', 'Supplier Refund'), ('bank_transfer', 'Bank Transfer'), ('year_end_close', 'Year-end Close'), ('inventory_adjustment', 'Inventory adjustment'), ('inventory_receipt', 'Inventory receipt'), ('inventory_issue', 'Inventory issue'), ('customer_return', 'Customer return'), ('supplier_return', 'Supplier return'), ('stock_count', 'Stock count'), ('fixed_asset_acquisition', 'Fixed asset acquisition'), ('depreciation', 'Depreciation'), ('fixed_asset_disposal', 'Fixed asset disposal'), ('payroll', 'Payroll'), ('payroll_payment', 'Payroll payment'), ('fx_revaluation', 'FX revaluation'), ('fx_realised', 'Realised FX'), ('manufacturing_material_issue', 'Manufacturing material issue'), ('manufacturing_completion', 'Manufacturing completion'), ('manufacturing_cost', 'Manufacturing cost'), ('manufacturing_variance', 'Manufacturing variance'), ('opening_balance', 'Opening Balance')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_created', to=settings.AUTH_USER_MODEL)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_record', to='accounting.journalentry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='organisations.organisation')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_posted', to=settings.AUTH_USER_MODEL)),
                ('reversal_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_reversal_record', to='accounting.journalentry')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opening_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unusual_side_confirmed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_lines', to='accounting.account')),
                ('opening_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.openingbalance')),
            ],
            options={
                'ordering': ['account__code'],
            },
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['organisation', 'status'], name='accounting__organis_70e0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['organisation', 'opening_date'], name='accounting__organis_074fad_idx'),
        ),
        migrations.AddConstraint(
            model_name='openingbalanceline',
            constraint=models.UniqueConstraint(fields=('opening_balance', 'account'), name='unique_opening_balance_account'),
        ),
    ]
