# Generated by Django 6.1 on 2026-09-10 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preflight(apps,schema_editor):
    from django.db.models import Count
    Opening=apps.get_model('accounting','OpeningBalance')
    if Opening.objects.filter(status='posted').values('organisation_id','opening_date').annotate(n=Count('id')).filter(n__gt=1).exists():
        raise RuntimeError('Ambiguous posted opening balances: run audit_accounting_integrity and resolve by an authorised plan before migrating. No history was changed.')
    Period=apps.get_model('accounting','AccountingPeriod')
    for period in Period.objects.all().iterator():
        if Period.objects.filter(organisation_id=period.organisation_id,start_date__lte=period.end_date,end_date__gte=period.start_date).exclude(pk=period.pk).exists():
            raise RuntimeError('Overlapping accounting periods: run audit_accounting_integrity and resolve by an authorised plan before migrating. No history was changed.')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_accountimportbatch'),
        ('organisations', '0006_normalise_legacy_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight,migrations.RunPython.noop),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=32)),
                ('key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(null=True)),
                ('result_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted')), fields=('organisation', 'opening_date'), name='unique_posted_opening_date'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(fields=('organisation', 'operation', 'key'), name='unique_payment_request_key'),
        ),
    ]
