# Generated by Django 6.1 on 2026-09-10 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_postgres_ledger_guards'),
        ('organisations', '0006_normalise_legacy_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.UUIDField()),
                ('operation', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reversal_journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry')),
            ],
        ),
    ]
