# Generated by Django 6.1 on 2026-09-22 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_source_and_period_guards'),
        ('organisations', '0009_organisation_accounting_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClassificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_events', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('replacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_replacement_events', to='accounting.account')),
            ],
        ),
    ]
