# Generated by Django 6.1 on 2026-09-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_account_classification_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_current_control',
            field=models.BooleanField(default=True),
        ),
    ]
