# Generated by Django 6.1 on 2026-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='require_separate_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('approver', 'Approver'), ('employee', 'Employee'), ('viewer', 'Read only')], default='employee', max_length=20),
        ),
    ]
