# Generated by Django 6.1 on 2026-08-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_require_separate_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='tax_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax_period_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax_reporting_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax_scheme',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
