# Generated by Django 6.1 on 2026-08-13 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_journalentry_exchange_rate_and_more'),
        ('organisations', '0003_organisation_tax_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='fx_gain_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisations_fx_gain', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='fx_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisations_fx_loss', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
