# Generated by Django 6.1 on 2026-08-28 01:54

import common.currencies
from django.db import migrations, models


def normalise_legacy_ghanaian_currency_values(apps, schema_editor):
    """Convert only known legacy Ghanaian currency labels; preserve every other value."""
    connection = schema_editor.connection
    quote = connection.ops.quote_name
    currency_columns = {
        'currency', 'base_currency', 'reporting_currency', 'tax_reporting_currency',
        'transaction_currency', 'foreign_currency', 'source_currency',
    }
    with connection.cursor() as cursor:
        tables = connection.introspection.table_names(cursor)
        for table in tables:
            columns = {column.name for column in connection.introspection.get_table_description(cursor, table)}
            for column in columns & currency_columns:
                cursor.execute(
                    f"UPDATE {quote(table)} SET {quote(column)} = %s WHERE {quote(column)} IN (%s, %s, %s)",
                    ["GHS", "GH¢", "GH₵", "GHC"],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
    ]

    operations = [
        migrations.RunPython(normalise_legacy_ghanaian_currency_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organisation',
            name='base_currency',
            field=models.CharField(default='GBP', max_length=3, validators=[common.currencies.validate_currency_code]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='reporting_currency',
            field=models.CharField(blank=True, max_length=3, validators=[common.currencies.validate_optional_currency_code]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='tax_reporting_currency',
            field=models.CharField(blank=True, max_length=3, validators=[common.currencies.validate_optional_currency_code]),
        ),
    ]
