# Generated by Django 6.1 on 2026-09-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_normalise_legacy_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ghana_post_gps',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='payment_instructions',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
