# Generated by Django 6.1 on 2026-09-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_ghana_post_gps_organisation_logo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='tax_configuration_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax_structure_type',
            field=models.CharField(blank=True, choices=[('GHANA_GRA', 'GHANA_GRA'), ('CUSTOM_INTERNATIONAL', 'CUSTOM_INTERNATIONAL'), ('NO_TAX', 'NO_TAX')], default='', max_length=30),
        ),
    ]
