# Generated by Django 6.1 on 2026-09-19 17:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification_identityemailattempt_and_more'),
        ('organisations', '0008_organisation_tax_configuration_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='accounting_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='business_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organisation',
            name='locale',
            field=models.CharField(default='en-GB', max_length=30),
        ),
        migrations.CreateModel(
            name='AccessAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=80)),
                ('subject_id', models.UUIDField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.UUIDField(null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationSetup',
            fields=[
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='setup', serialize=False, to='organisations.organisation')),
                ('opening_choice', models.CharField(max_length=30)),
                ('checklist', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_acceptance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.policyacceptance')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('approver', 'Approver'), ('employee', 'Employee'), ('viewer', 'Read only')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('token_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organisations.organisation')),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('organisation'), condition=models.Q(('status', 'pending')), name='one_pending_invitation_per_org_email')],
            },
        ),
    ]
