import { api } from "./api";

export const commercialService = {
  quotes: () => api.get("quotes/"), quote: (id) => api.get(`quotes/${id}/`),
  createQuote: (data) => api.post("quotes/", data),
  updateQuote: (id, data) => api.patch(`quotes/${id}/`, data),
  acceptQuote: (id) => api.post(`quotes/${id}/accept/`, {}),
  convertQuoteToInvoice: (id, data) => api.post(`quotes/${id}/convert-to-invoice/`, data),
  salesOrders: () => api.get("sales-orders/"), salesOrder: (id) => api.get(`sales-orders/${id}/`),
  createSalesOrder: (data) => api.post("sales-orders/", data),
  approveSalesOrder: (id) => api.post(`sales-orders/${id}/approve/`, {}),
  fulfilSalesOrder: (id, data) => api.post(`sales-orders/${id}/fulfil/`, data),
  convertSalesOrderToInvoice: (id, data) => api.post(`sales-orders/${id}/convert-to-invoice/`, data),
  purchaseOrders: () => api.get("purchase-orders/"), purchaseOrder: (id) => api.get(`purchase-orders/${id}/`),
  createPurchaseOrder: (data) => api.post("purchase-orders/", data),
  updatePurchaseOrder: (id, data) => api.patch(`purchase-orders/${id}/`, data),
  approvePurchaseOrder: (id) => api.post(`purchase-orders/${id}/approve/`, {}),
  receivePurchaseOrder: (id, data) => api.post(`purchase-orders/${id}/receive/`, data),
  convertPurchaseOrderToBill: (id, data) => api.post(`purchase-orders/${id}/convert-to-bill/`, data),
  customerCredits: () => api.get("customer-credit-notes/"),
  createCustomerCredit: (data) => api.post("customer-credit-notes/", data),
  customerCredit: (id) => api.get(`customer-credit-notes/${id}/`),
  approveCustomerCredit: (id) => api.post(`customer-credit-notes/${id}/approve/`, {}),
  applyCustomerCredit: (id, data) => api.post(`customer-credit-notes/${id}/apply/`, data),
  customerRefunds: () => api.get("customer-refunds/"),
  createCustomerRefund: (data) => api.post("customer-refunds/", data),
  supplierCredits: () => api.get("supplier-credits/"),
  supplierCredit: (id) => api.get(`supplier-credits/${id}/`),
  createSupplierCredit: (data) => api.post("supplier-credits/", data),
  approveSupplierCredit: (id) => api.post(`supplier-credits/${id}/approve/`, {}),
  applySupplierCredit: (id, data) => api.post(`supplier-credits/${id}/apply/`, data),
  supplierRefunds: () => api.get("supplier-refunds/"),
  createSupplierRefund: (data) => api.post("supplier-refunds/", data),
};
