import { useEffect, useMemo, useState } from "react";
import { Save, X } from "lucide-react";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import { CURRENCY_OPTIONS } from "../../utils/currency";

const classes = {
  asset: [["bank","Bank"],["current_asset","Current Asset"],["fixed_asset","Fixed Asset"],["receivable","Accounts Receivable"]],
  liability: [["current_liability","Current Liability"],["long_term_liability","Long-term Liability"],["payable","Accounts Payable"]],
  equity: [["equity","Equity"],["retained_earnings","Retained Earnings"]],
  revenue: [["sales","Sales"],["other_income","Other Income"]],
  expense: [["cost_of_sales","Cost of Sales"],["operating_expense","Operating Expense"],["other_expense","Other Expense"]],
};
const blank = (currency) => ({ code: "", name: "", description: "", account_type: "asset", account_class: "current_asset", cash_flow_category: "not_applicable", currency: currency || "", allow_manual_journals: true, status: "active" });

export default function AccountFormModal({ isOpen, account, currency, onClose, onSaved }) {
  const [form, setForm] = useState(() => account ? { code: account.code, name: account.name, description: account.description || "", account_type: account.account_type, account_class: account.account_class, cash_flow_category: account.cash_flow_category, currency: account.currency || "", allow_manual_journals: account.allow_manual_journals, status: account.status } : blank(currency)); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [reason, setReason] = useState("");
  const [replacementOpen, setReplacementOpen] = useState(false);
  const [candidates, setCandidates] = useState([]);
  const [replacement, setReplacement] = useState("");
  const rules = account?.classification_policy;
  const classificationChanged = account && (form.account_type !== account.account_type || form.account_class !== account.account_class);
  const classLabel = value => Object.values(classes).flat().find(([key]) => key === value)?.[1] || value;
  const startReplacement = async () => {
    setSaving(true); setError("");
    try { const rows = await accountingApiService.accounts(); setCandidates(rows.filter(row => row.id !== account.id && row.account_type === account.account_type && row.currency === account.currency && row.status === 'active' && !row.classification_policy?.has_activity && !row.classification_policy?.protected)); setReplacementOpen(true); setConfirmed(false); setReason(""); }
    catch (requestError) { setError(normaliseApiError(requestError)); } finally { setSaving(false); }
  };
  const options = useMemo(() => classes[form.account_type] || [], [form.account_type]);
  useEffect(() => { if (!isOpen) return undefined; const close = (event) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [isOpen, onClose]);
  if (!isOpen) return null;
  const update = (event) => { const { name, value, checked, type } = event.target; if (name === "account_type") { setForm({ ...form, account_type: value, account_class: classes[value][0][0] }); } else setForm({ ...form, [name]: type === "checkbox" ? checked : value }); setConfirmed(false); setError(""); };
  const submit = async (event) => { event.preventDefault(); if (!form.code.trim() || !form.name.trim() || !form.account_type || !form.account_class) { setError("Account code, name, type and class are required."); return; } if ((classificationChanged || replacementOpen) && (!confirmed || !reason.trim())) { setError("Confirm the change and enter a reason before saving."); return; } setSaving(true); try { if (replacementOpen) { const result = await accountingApiService.replaceAccountControl(account.id, {replacement_id: replacement, confirmed, reason}); onSaved(result, "Control account replaced for future postings. Historical transactions and balances remain on the original account."); return; } const result = account ? await accountingApiService.updateAccount(account.id, {...form, classification_confirmed: confirmed, classification_reason: reason}) : await accountingApiService.createAccount(form); onSaved(result, account ? "Account updated successfully." : "Account created successfully."); } catch (requestError) { setError(normaliseApiError(requestError, "The account could not be saved.")); } finally { setSaving(false); } };
  return <div className="account-modal-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="account-modal" role="dialog" aria-modal="true" aria-labelledby="account-modal-title"><header className="account-modal-header"><div><span>Chart of Accounts</span><h2 id="account-modal-title">{account ? "Edit Account" : "Add Account"}</h2><p>{account ? `${account.code} · ${account.name}` : "Create a new account for recording and reporting financial activity."}</p></div><button type="button" className="account-modal-close" onClick={onClose} aria-label="Close account form"><X size={19}/></button></header><form className="account-form" onSubmit={submit}>{error && <div className="account-form-error" role="alert">{error}</div>}
    {(account?.is_system_account || rules?.protected) && <div className="account-control-notice"><strong>System / Control Account{["receivable", "payable"].includes(account.account_class) ? (account.is_current_control ? " · Current posting control" : " · Former posting control") : ""}</strong><span>Classification and status are protected because this account is a control account or is referenced by system configuration.</span></div>}
    <section className="account-form-section"><div><h3>Account details</h3><p>Identity used throughout journals and financial reports.</p></div><div className="account-form-grid"><label className="account-form-field">Account code<input autoFocus required name="code" value={form.code} onChange={update} disabled={account?.is_system_account}/><small>Used to organise and identify accounts in your chart.</small></label><label className="account-form-field">Account name<input required name="name" value={form.name} onChange={update}/></label><label className="account-form-field account-form-field-full">Description<textarea name="description" rows="3" value={form.description} onChange={update} placeholder="Explain what activity belongs in this account."/></label></div></section>
    <section className="account-form-section"><div><h3>Classification</h3><p>Controls financial statement and reporting presentation.</p></div><div className="account-form-grid"><label className="account-form-field">Account type<select required name="account_type" disabled={Boolean(account && !rules?.can_change_type) || replacementOpen} value={form.account_type} onChange={update}>{Object.keys(classes).map((value) => <option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select><small>{account && !rules?.can_change_type ? "Account type cannot be changed because this account contains accounting activity or is a protected control account." : "Controls where this account appears in financial statements."}</small></label><label className="account-form-field">Account class<select required name="account_class" disabled={Boolean(account && !rules?.can_change_class) || replacementOpen} value={form.account_class} onChange={update}>{options.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><small>Provides a more detailed reporting classification within the account type.</small></label></div></section>
    <section className="account-form-section"><div><h3>Settings</h3><p>Posting, currency and cash-flow behaviour.</p></div><div className="account-form-grid"><label className="account-form-field">Status<select name="status" value={form.status} onChange={update} disabled={rules?.protected}><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select>{account?.is_system_account && <small>System accounts cannot be deactivated here.</small>}</label><label className="account-form-field">Currency<select name="currency" disabled={rules?.has_activity || rules?.protected} value={form.currency} onChange={update}><option value="">Use organisation currency</option>{CURRENCY_OPTIONS.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label className="account-form-field">Cash flow category<select name="cash_flow_category" disabled={rules?.has_activity || rules?.protected} value={form.cash_flow_category} onChange={update}><option value="operating">Operating activities</option><option value="investing">Investing activities</option><option value="financing">Financing activities</option><option value="cash">Cash and cash equivalents</option><option value="not_applicable">Not applicable</option></select></label><label className="account-checkbox-field"><input type="checkbox" name="allow_manual_journals" checked={form.allow_manual_journals} onChange={update}/><span><strong>Allow manual journals</strong><small>Permit this account in manually created journal entries.</small></span></label></div></section>
    {rules?.can_replace_control && !replacementOpen && <section className="account-form-section"><h3>Replace control account</h3><p>Choose an unused account for future automatic postings. The original account remains available for historical balances and reversals.</p><button type="button" className="invoice-secondary-button" disabled={saving} onClick={startReplacement}>Choose replacement control</button></section>}
    {replacementOpen && <section className="account-form-section"><h3>Future posting control</h3><label className="account-form-field">Replacement account<select required value={replacement} onChange={event => {setReplacement(event.target.value); setConfirmed(false);}}><option value="">Select an unused account</option>{candidates.map(row => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label>{!candidates.length && <p>Create an unused active account with the same type and currency first.</p>}<button type="button" onClick={()=>{setReplacementOpen(false);setConfirmed(false);setReason("");}}>Cancel replacement</button></section>}
    {(classificationChanged || replacementOpen) && <section className="account-form-section"><h3>Confirm classification change</h3><p>{replacementOpen ? "Historical transactions remain on the old account. Future postings use the new control account. Existing balances are not automatically transferred; any transfer requires a proper accounting journal." : `You are changing ${classLabel(account.account_class)} to ${classLabel(form.account_class)}. Historical transactions will not be modified. Report grouping and future control-account behaviour may change.`}</p><label className="account-form-field">Reason<textarea required maxLength={2000} value={reason} onChange={event => setReason(event.target.value)}/></label><label className="account-checkbox-field"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)}/><span>I understand and confirm this change.</span></label></section>}
    <footer className="account-modal-actions"><button type="button" className="invoice-secondary-button" onClick={onClose}>Cancel</button><button className="page-primary-button" disabled={saving}><Save size={16}/>{saving ? "Saving…" : "Save Account"}</button></footer></form></section></div>;
}
