import { useMemo, useRef, useState } from "react";
import { Download, FileSpreadsheet, Search, Upload, X } from "lucide-react";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import TablePagination from "../common/TablePagination";
import { useTablePagination } from "../../hooks/useTablePagination";

const saveBlob = (blob, name) => { const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url); };
const humanise = (value) => String(value || "").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

export default function AccountImportModal({ onClose, onCompleted }) {
  const input=useRef(null);const [file,setFile]=useState(null);const [batch,setBatch]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [search,setSearch]=useState("");const [filter,setFilter]=useState("");
  const rows=useMemo(()=>(batch?.rows||[]).filter(row=>(!filter||row.status===filter)&&`${row.data.code} ${row.data.name}`.toLowerCase().includes(search.toLowerCase())),[batch,filter,search]);const paging=useTablePagination(rows);
  const downloadTemplate=async()=>{setBusy(true);try{saveBlob(await accountingApiService.downloadAccountImportTemplate(),"Ledgify_Chart_of_Accounts_Import_Template.xlsx");}catch(e){setError(normaliseApiError(e));}finally{setBusy(false);}};
  const preview=async()=>{if(!file)return;setBusy(true);setError("");try{setBatch(await accountingApiService.previewAccountImport(file));}catch(e){setError(normaliseApiError(e,"The workbook could not be validated."));}finally{setBusy(false);}};
  const confirm=async()=>{setBusy(true);setError("");try{const result=await accountingApiService.confirmAccountImport(batch.id);setBatch(result);await onCompleted(result);}catch(e){setError(normaliseApiError(e,"The import could not be completed."));}finally{setBusy(false);}};
  return <div className="account-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="account-modal account-import-modal" role="dialog" aria-modal="true" aria-labelledby="account-import-title"><header className="account-modal-header"><div><span>Chart of Accounts</span><h2 id="account-import-title">Import Accounts</h2><p>Download the Ledgify template, upload it for validation, then confirm an atomic import.</p></div><button className="account-modal-close" onClick={onClose} aria-label="Close"><X size={19}/></button></header><div className="account-form">
    <ol className="account-import-steps"><li className="active">Download Template</li><li className={file?"active":""}>Upload File</li><li className={batch?"active":""}>Validate and Preview</li><li className={batch&&!batch.invalid_rows?"active":""}>Confirm Import</li><li className={batch?.status==="completed"?"active":""}>Import Results</li></ol>
    {error&&<div className="account-form-error" role="alert">{error}</div>}
    {!batch&&<><section className="account-form-section"><div><h3>1. Download template</h3><p>Includes exact Ledgify fields, allowed values, instructions and non-importable example rows.</p></div><button disabled={busy} className="invoice-secondary-button" onClick={downloadTemplate}><Download size={16}/>Download Excel Template</button></section><section className="account-form-section"><div><h3>2. Upload workbook</h3><p>Macro-free .xlsx only · maximum 5 MB · maximum 1,000 accounts.</p></div><button type="button" className="account-import-dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFile(e.dataTransfer.files[0]||null);}}><Upload/><strong>{file?file.name:"Choose or drop an .xlsx file"}</strong><span>{file?`${(file.size/1024).toFixed(1)} KB`:"The file is validated securely on the server"}</span></button><input ref={input} hidden type="file" accept=".xlsx" onChange={e=>setFile(e.target.files[0]||null)}/></section></>}
    {batch&&<>{batch.status==="completed"?<section className="chart-accounts-success"><FileSpreadsheet/><div><strong>Import completed</strong><p>{batch.created_account_ids.length} accounts created. Audit reference: {batch.id}</p></div></section>:<><div className="account-import-summary">{[["Total Rows",batch.total_rows],["Valid Rows",batch.valid_rows],["Warnings",batch.rows.filter(r=>r.status==="warning").length],["Invalid Rows",batch.invalid_rows],["Existing Conflicts",batch.existing_rows]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="chart-accounts-toolbar"><label className="chart-account-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search preview"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{["ready","warning","error","existing"].map(value=><option key={value}>{value}</option>)}</select>{batch.invalid_rows>0&&<button className="invoice-secondary-button" onClick={async()=>saveBlob(await accountingApiService.accountImportErrors(batch.id),`Ledgify_Account_Import_Errors_${batch.id}.csv`)}>Download Error Report</button>}</div><div className="chart-accounts-table-wrapper"><table className="chart-accounts-table"><thead><tr><th>Row</th><th>Code</th><th>Name</th><th>Type</th><th>Class</th><th>Status</th><th>Messages</th></tr></thead><tbody>{paging.pageRows.map(row=><tr key={row.row_number}><td>{row.row_number}</td><td>{row.data.code||"—"}</td><td>{row.data.name||"—"}</td><td>{humanise(row.data.account_type)}</td><td>{humanise(row.data.account_class)}</td><td><span className={`chart-account-status chart-account-status-${row.status}`}>{humanise(row.status)}</span></td><td>{[...row.errors,...row.warnings].map(item=>item.message).join(" ")||"Ready to import"}</td></tr>)}</tbody></table></div><TablePagination {...paging}/></>}</>}
    <footer className="account-modal-actions"><button className="invoice-secondary-button" onClick={onClose}>{batch?.status==="completed"?"Close":"Cancel"}</button>{!batch&&<button className="page-primary-button" disabled={!file||busy} onClick={preview}>{busy?"Validating…":"Validate and Preview"}</button>}{batch&&batch.status!=="completed"&&<><button className="invoice-secondary-button" onClick={()=>{setBatch(null);setError("");}}>Choose Another File</button><button className="page-primary-button" disabled={busy||batch.invalid_rows>0} onClick={confirm}>{busy?"Importing…":"Confirm Import"}</button></>}</footer>
  </div></section></div>;
}
