# Generated by Django 6.1 on 2026-08-13 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0013_alter_journalentry_source_type'),
        ('contacts', '0001_initial'),
        ('organisations', '0003_organisation_tax_effective_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT'), ('GST', 'GST'), ('SALES_TAX', 'Sales tax'), ('OTHER', 'Other')], max_length=20)),
                ('scope', models.CharField(choices=[('SALES', 'Sales'), ('PURCHASES', 'Purchases'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('recoverable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates_created', to=settings.AUTH_USER_MODEL)),
                ('input_tax_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_tax_rates', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='organisations.organisation')),
                ('output_tax_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_tax_rates', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_rate_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('transaction_date', models.DateField()),
                ('source_type', models.CharField(max_length=30)),
                ('source_id', models.UUIDField()),
                ('document_number', models.CharField(max_length=50)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('direction', models.CharField(choices=[('OUTPUT', 'Output'), ('INPUT', 'Input')], max_length=10)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('ADJUSTMENT', 'Adjustment')], default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='contacts.contact')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.journalentry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='organisations.organisation')),
                ('tax_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='accounting.account')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tax.taxrate')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PREPARED', 'Prepared'), ('FILED', 'Filed'), ('LOCKED', 'Locked')], default='OPEN', max_length=20)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_periods_filed', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_periods', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'start_date', 'end_date'), name='unique_tax_period_per_org'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='tax_period_dates_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(fields=('organisation', 'code'), name='unique_tax_rate_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='tax_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='taxtransaction',
            constraint=models.UniqueConstraint(fields=('organisation', 'source_type', 'source_id', 'tax_rate', 'direction'), name='unique_tax_transaction_source_rate_direction'),
        ),
    ]
