# Generated by Django 6.1 on 2026-09-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_tax_integrity_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
