# Generated by Django 6.1 on 2026-09-12 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_source_and_period_guards'),
        ('organisations', '0008_organisation_tax_configuration_version_and_more'),
        ('tax', '0005_tax_configuration_mutation_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxadjustment',
            name='idempotency_key',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='taxadjustment',
            name='payload_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taxpayment',
            name='idempotency_key',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayment',
            name='payload_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='taxadjustment',
            constraint=models.UniqueConstraint(fields=('organisation', 'idempotency_key'), name='taxadjustment_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='taxpayment',
            constraint=models.UniqueConstraint(fields=('organisation', 'idempotency_key'), name='taxpayment_request_unique'),
        ),
    ]
