import { useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../../services/api';
import { useAuth } from '../../store/AuthContext';
import { normaliseApiError } from '../../services/apiError';
import { readIdentityLink, clearIdentityLink } from '../../utils/identityLinks';
import '../../styles/publicAccess.css';
export default function AcceptInvitationPage(){
 const auth=useAuth(),navigate=useNavigate(),guard=useRef(false);const [token]=useState(readIdentityLink);
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[invitation,setInvitation]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function review(e){e?.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');try{if(!auth.isAuthenticated)await auth.login({email,password});setPassword('');setInvitation(await api.post('invitation-acceptance/',{token,confirmed:false}));}catch(e){setError(normaliseApiError(e,'This invitation is unavailable. Sign in with the verified invited email or ask for a new invitation.'));}finally{guard.current=false;setBusy(false);}}
 return <main className="auth-screen public-access"><section className="auth-card"><div className="auth-brand">Ledgify</div><h1>Accept organisation invitation</h1>{error&&<p role="alert" className="auth-error">{error}</p>}{!token?<p>This invitation link is invalid. Ask the organisation owner for a new invitation.</p>:invitation?<><h2>{invitation.organisation_name}</h2><p>Invited role: {invitation.role}</p><p>{invitation.message}</p><button disabled={busy} onClick={async()=>{if(guard.current)return;guard.current=true;setBusy(true);try{const result=await api.post('invitation-acceptance/',{token,confirmed:true});const session=await auth.bootstrapAuth();const org=session.organisations.find(o=>o.id===result.organisation_id);if(!org)throw Error('Refresh your organisation list and try again.');await auth.selectOrganisation(org);clearIdentityLink();navigate('/',{replace:true});}catch(e){setError(normaliseApiError(e));}finally{guard.current=false;setBusy(false);}}}>{busy?'Accepting…':'Confirm acceptance'}</button></>:<><p>Sign in with the verified email address that received this invitation. Expired or revoked invitations cannot be accepted.</p>{!auth.isAuthenticated?<form onSubmit={review}><label>Email address<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?'Checking…':'Sign in and review invitation'}</button></form>:<button disabled={busy} onClick={review}>Review invitation</button>}<p>New to Ledgify? <Link to="/register" target="_blank" rel="noreferrer">Register and verify your invited email</Link>, then return here to sign in and accept.</p><Link to="/resend-verification" target="_blank" rel="noreferrer">Request verification email</Link></>}</section></main>;
}
