// Support statement imports, rules, and cash coding through controlled backend workflows.

import { useCallback, useEffect, useState } from "react";
import PageHeader from "../../components/layout/PageHeader";
import TablePagination from "../../components/common/TablePagination";
import { useTablePagination } from "../../hooks/useTablePagination";
import { accountingApiService } from "../../services/accountingApiService";
import { bankService } from "../../services/bankService";
import { normaliseApiError } from "../../services/apiError";
import "../../styles/chartOfAccounts.css";
import "../../styles/products.css";

const show=(value)=>value==null||value===""?"—":typeof value==="object"?value.name||value.id||JSON.stringify(value):String(value);
const cashCodingAccounts=(accounts)=>accounts.filter((item)=>!["receivable","payable"].includes(item.account_class));
function Table({rows}){const pagination=useTablePagination(rows);if(!rows.length)return <p>No records found.</p>;const keys=Object.keys(rows[0]).filter((key)=>!["id","metadata","rows"].includes(key)).slice(0,9);return <><div className="chart-accounts-table-wrapper"><table className="chart-accounts-table"><thead><tr>{keys.map((key)=><th key={key}>{key.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{pagination.pageRows.map((row,index)=><tr key={row.id||index}>{keys.map((key)=><td key={key}>{show(row[key])}</td>)}</tr>)}</tbody></table></div><TablePagination {...pagination}/></>}

export function LiveBankImportPage(){const [accounts,setAccounts]=useState([]);const [history,setHistory]=useState([]);const [account,setAccount]=useState("");const [file,setFile]=useState(null);const [preview,setPreview]=useState(null);const [message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const [bankAccounts,imports]=await Promise.all([bankService.accounts(),bankService.imports()]);setAccounts(bankAccounts);setHistory(imports);}catch(error){setMessage(normaliseApiError(error));}},[]);useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame);},[load]);
  const submit=async(event)=>{event.preventDefault();const data=new FormData();data.append("bank_account_id",account);data.append("file",file);data.append("mapping",JSON.stringify({transaction_date:"Date",description:"Description",reference:"Reference",amount:"Amount"}));try{setPreview(await bankService.previewImport(data));setMessage("");await load();}catch(error){setMessage(normaliseApiError(error));}};
  const commit=async()=>{try{setPreview(await bankService.commitImport(preview.id));setMessage("Import committed.");await load();}catch(error){setMessage(normaliseApiError(error));}};
  return <div className="products-page"><PageHeader eyebrow="Banking" title="Statement import" description="Preview CSV rows, duplicates, and validation errors before committing."/>{message&&<div className="invoice-form-alert">{message}</div>}<form className="invoice-form-card" onSubmit={submit}><label>Bank account <select required value={account} onChange={(event)=>setAccount(event.target.value)}><option value="">Select</option>{accounts.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>CSV file <input required type="file" accept=".csv,text/csv" onChange={(event)=>setFile(event.target.files[0])}/></label><button className="page-primary-button">Preview</button></form>{preview&&<section className="invoice-form-card"><h2>Preview</h2><Table rows={preview.rows||[]}/>{preview.status==="previewed"&&<button className="page-primary-button" onClick={()=>void commit()}>Commit ready rows</button>}</section>}<section className="invoice-form-card"><h2>Import history</h2><Table rows={history}/></section></div>}

export function LiveBankRulesPage(){const [rules,setRules]=useState([]);const [accounts,setAccounts]=useState([]);const [message,setMessage]=useState("");const [form,setForm]=useState({name:"",priority:100,direction:"money_out",description_contains:"",target_account_id:""});const load=useCallback(async()=>{try{const [items,ledgers]=await Promise.all([bankService.rules(),accountingApiService.accounts({status:"active"})]);setRules(items);setAccounts(cashCodingAccounts(ledgers));}catch(error){setMessage(normaliseApiError(error));}},[]);useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame);},[load]);const submit=async(event)=>{event.preventDefault();try{await bankService.createRule(form);setForm((value)=>({...value,name:"",description_contains:""}));await load();}catch(error){setMessage(normaliseApiError(error));}};return <div className="products-page"><PageHeader eyebrow="Banking" title="Bank rules" description="Deterministic account-coding suggestions; rules never auto-reconcile."/>{message&&<div className="invoice-form-alert">{message}</div>}<form className="invoice-form-card" onSubmit={submit}><label>Name <input required value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})}/></label><label>Description contains <input value={form.description_contains} onChange={(event)=>setForm({...form,description_contains:event.target.value})}/></label><label>Direction <select value={form.direction} onChange={(event)=>setForm({...form,direction:event.target.value})}><option value="money_out">Money out</option><option value="money_in">Money in</option></select></label><label>Target account <select required value={form.target_account_id} onChange={(event)=>setForm({...form,target_account_id:event.target.value})}><option value="">Select a non-control account</option>{accounts.map((item)=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><button className="page-primary-button">Create rule</button></form><section className="invoice-form-card"><Table rows={rules}/></section></div>}

export function LiveCashCodingPage(){const [queue,setQueue]=useState([]);const [accounts,setAccounts]=useState([]);const [selected,setSelected]=useState([]);const [account,setAccount]=useState("");const [message,setMessage]=useState("");const load=useCallback(async()=>{try{const [items,ledgers]=await Promise.all([bankService.transactions({status:"unreconciled"}),accountingApiService.accounts({status:"active"})]);setQueue(items);setAccounts(cashCodingAccounts(ledgers));}catch(error){setMessage(normaliseApiError(error));}},[]);useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame);},[load]);const reconcile=async()=>{try{await bankService.bulkReconcile(selected,account);setSelected([]);setMessage("Transactions reconciled.");await load();}catch(error){setMessage(normaliseApiError(error));}};return <div className="products-page"><PageHeader eyebrow="Banking" title="Cash coding" description="Code unreconciled transactions through the existing journal-safe reconciliation engine."/>{message&&<div className="invoice-form-alert">{message}</div>}<section className="invoice-form-card"><label>Target account <select value={account} onChange={(event)=>setAccount(event.target.value)}><option value="">Select a non-control account</option>{accounts.map((item)=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>{queue.map((row)=><label key={row.id}><input type="checkbox" checked={selected.includes(row.id)} onChange={(event)=>setSelected((value)=>event.target.checked?[...value,row.id]:value.filter((id)=>id!==row.id))}/>{row.transaction_date} · {row.description} · {row.amount}</label>)}<button disabled={!selected.length||!account} className="page-primary-button" onClick={()=>void reconcile()}>Reconcile selected</button></section></div>}
