# Generated by Django 6.1 on 2026-08-13 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0015_journalentry_exchange_rate_and_more'),
        ('fx', '0001_initial'),
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(max_length=20)),
                ('account_class', models.CharField(max_length=30)),
                ('cash_flow_category', models.CharField(default='not_applicable', max_length=30)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cta_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cta_groups', to='consolidation.consolidationaccount')),
                ('parent_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_groups', to='organisations.organisation')),
                ('reporting_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fx.currency')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('consolidation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consolidation.consolidationaccount')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='consolidation.consolidationgroup')),
            ],
        ),
        migrations.AddField(
            model_name='consolidationaccount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='consolidation.consolidationgroup'),
        ),
        migrations.CreateModel(
            name='ConsolidationGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ownership_percentage', models.DecimalField(decimal_places=4, default=100, max_digits=7)),
                ('consolidation_method', models.CharField(choices=[('full', 'Full'), ('proportionate', 'Proportionate'), ('equity', 'Equity')], default='full', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='consolidation.consolidationgroup')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('prepared', 'Prepared'), ('finalised', 'Finalised')], default='open', max_length=12)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidations_finalised', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='consolidation.consolidationgroup')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidations_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consolidation.consolidationgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consolidation.consolidationperiod')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_currency', models.CharField(max_length=3)),
                ('reporting_currency', models.CharField(max_length=3)),
                ('translation_metadata', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consolidation.consolidationgroup')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='consolidation.consolidationperiod')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationSnapshotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_debit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_credit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('translated_debit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('translated_credit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('translation_method', models.CharField(max_length=20)),
                ('consolidation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consolidation.consolidationaccount')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='consolidation.consolidationsnapshot')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
            ],
        ),
        migrations.CreateModel(
            name='EliminationJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eliminations_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consolidation.consolidationgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eliminations', to='consolidation.consolidationperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eliminations_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EliminationJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('consolidation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consolidation.consolidationaccount')),
                ('counterparty_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_elimination_lines', to='organisations.organisation')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='consolidation.eliminationjournal')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elimination_lines', to='organisations.organisation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consolidationaccount',
            constraint=models.UniqueConstraint(fields=('group', 'code'), name='unique_group_account'),
        ),
        migrations.AddConstraint(
            model_name='consolidationgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'organisation'), name='unique_group_member'),
        ),
    ]
