# Generated by Django 6.1 on 2026-08-13 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_journalentry_source_type'),
        ('consolidation', '0001_initial'),
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminationjournal',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='consolidation.eliminationjournal'),
        ),
        migrations.AddField(
            model_name='eliminationjournal',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eliminationjournal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eliminations_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eliminationjournal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='consolidationaccountmapping',
            constraint=models.UniqueConstraint(fields=('group', 'source_account', 'effective_from'), name='unique_active_source_mapping_date'),
        ),
        migrations.AddConstraint(
            model_name='eliminationjournal',
            constraint=models.UniqueConstraint(fields=('group', 'entry_number'), name='unique_group_elimination_number'),
        ),
    ]
