# Generated by Django 6.1 on 2026-08-12 08:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_journalentry_source_type'),
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
        ('sales', '0002_customerpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_credited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.CreateModel(
            name='CustomerCreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('partly_applied', 'Partly applied'), ('applied', 'Applied'), ('void', 'Void')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_note', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='contacts.contact')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit_notes', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('applied_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_allocations_applied', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit_allocations', to='organisations.organisation')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.customercreditnote')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCreditNoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.customercreditnote')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_lines', to='accounting.account')),
            ],
        ),
        migrations.AddIndex(
            model_name='customercreditnote',
            index=models.Index(fields=['organisation', 'status'], name='sales_custo_organis_7307c0_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditnote',
            index=models.Index(fields=['organisation', 'customer'], name='sales_custo_organis_27d074_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditnote',
            index=models.Index(fields=['organisation', 'issue_date'], name='sales_custo_organis_d94923_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercreditnote',
            constraint=models.UniqueConstraint(fields=('organisation', 'credit_note_number'), name='unique_customer_credit_number_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='customercreditallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_credit_allocation_amount_positive'),
        ),
    ]
