# Generated by Django 6.1 on 2026-08-12 09:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentry_source_type'),
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
        ('sales', '0003_invoice_amount_credited_customercreditnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditnote',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_written_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('partly_paid', 'Partly paid'), ('paid', 'Paid'), ('void', 'Void'), ('written_off', 'Written off')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='BadDebtWriteOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('write_off_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_write_off', to='accounting.journalentry')),
                ('bad_debt_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_write_offs', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_write_offs_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_debt_write_offs', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-write_off_date', '-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='sales_badde_organis_cbd645_idx'), models.Index(fields=['organisation', 'invoice'], name='sales_badde_organis_584ba3_idx'), models.Index(fields=['organisation', 'write_off_date'], name='sales_badde_organis_ee7942_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bad_debt_write_off_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_refund', to='accounting.journalentry')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_refunds_issued', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_refunds_created', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.customercreditnote')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='contacts.contact')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_refunds', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-refund_date', '-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='sales_custo_organis_56ddeb_idx'), models.Index(fields=['organisation', 'customer'], name='sales_custo_organis_c3922f_idx'), models.Index(fields=['organisation', 'refund_date'], name='sales_custo_organis_957212_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_refund_amount_positive')],
            },
        ),
    ]
