# Generated by Django 6.1 on 2026-08-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_quote_quoteline_salesorder_salesorderline_and_more'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditnoteline',
            name='tax_rate_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_lines', to='tax.taxrate'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_rate_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='tax.taxrate'),
        ),
    ]
