# Generated by Django 6.1 on 2026-08-13 03:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_customercreditnoteline_tax_rate_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditnote',
            name='base_currency_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='customercreditnote',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1'), max_digits=20),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='base_currency_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1'), max_digits=20),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='realised_fx_gain_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='base_currency_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1'), max_digits=20),
        ),
    ]
