# Generated by Django 6.1 on 2026-09-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_customercreditnote_base_currency_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditallocation',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentallocation',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentallocation',
            name='reversal_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
