# Generated by Django 6.1 on 2026-09-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_phase2_allocation_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditallocation',
            name='carrying_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customercreditallocation',
            name='source_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentallocation',
            name='carrying_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customerpaymentallocation',
            name='source_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
