# Generated by Django 6.1 on 2026-09-10 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_ghana_post_gps_organisation_logo_data_and_more'),
        ('sales', '0013_allocation_carrying_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEmailAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('document_hash', models.CharField(max_length=64)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('failure_category', models.CharField(blank=True, max_length=40)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_attempts', to='sales.invoice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'key'), name='unique_invoice_email_key')],
            },
        ),
    ]
