# Generated by Django 6.1 on 2026-09-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_invoiceemailattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercreditnoteline',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
