# Generated by Django 6.1 on 2026-09-12 01:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_customercreditnoteline_tax_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercreditnoteline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
