VIEW_ACCOUNTING = "view_accounting"
MANAGE_CONTACTS = "manage_contacts"
MANAGE_ACCOUNTS = "manage_accounts"
CREATE_JOURNAL = "create_journal"
POST_JOURNAL = "post_journal"
REVERSE_JOURNAL = "reverse_journal"
CREATE_INVOICE = "create_invoice"
APPROVE_INVOICE = "approve_invoice"
CREATE_CUSTOMER_PAYMENT = "create_customer_payment"
CREATE_BILL = "create_bill"
APPROVE_BILL = "approve_bill"
CREATE_SUPPLIER_PAYMENT = "create_supplier_payment"
CREATE_CUSTOMER_REFUND = "create_customer_refund"
CREATE_SUPPLIER_REFUND = "create_supplier_refund"
CREATE_BAD_DEBT_WRITE_OFF = "create_bad_debt_write_off"
CREATE_CUSTOMER_CREDIT = "create_customer_credit"
APPROVE_CUSTOMER_CREDIT = "approve_customer_credit"
CREATE_SUPPLIER_CREDIT = "create_supplier_credit"
APPROVE_SUPPLIER_CREDIT = "approve_supplier_credit"
RECONCILE_BANK = "reconcile_bank"
UNRECONCILE_BANK = "unreconcile_bank"
MANAGE_BANK_TRANSACTIONS = "manage_bank_transactions"
CLOSE_PERIOD = "close_period"
REOPEN_PERIOD = "reopen_period"
MANAGE_FINANCIAL_YEARS = "manage_financial_years"
CLOSE_FINANCIAL_YEAR = "close_financial_year"
REOPEN_FINANCIAL_YEAR = "reopen_financial_year"
MANAGE_ORGANISATION_USERS = "manage_organisation_users"
EXPORT_REPORTS = "export_reports"
VIEW_INVENTORY = "view_inventory"
MANAGE_PRODUCTS = "manage_products"
MANAGE_WAREHOUSES = "manage_warehouses"
ADJUST_STOCK = "adjust_stock"
CREATE_QUOTE = "create_quote"
APPROVE_QUOTE = "approve_quote"
CREATE_SALES_ORDER = "create_sales_order"
APPROVE_SALES_ORDER = "approve_sales_order"
FULFIL_SALES_ORDER = "fulfil_sales_order"
CREATE_PURCHASE_ORDER = "create_purchase_order"
APPROVE_PURCHASE_ORDER = "approve_purchase_order"
RECEIVE_PURCHASE_ORDER = "receive_purchase_order"
IMPORT_BANK_STATEMENTS = "import_bank_statements"
MANAGE_BANK_RULES = "manage_bank_rules"
VIEW_FIXED_ASSETS = "view_fixed_assets"
MANAGE_FIXED_ASSETS = "manage_fixed_assets"
RUN_DEPRECIATION = "run_depreciation"
VIEW_TAX = "view_tax"
MANAGE_TAX_RATES = "manage_tax_rates"
PREPARE_TAX_RETURN = "prepare_tax_return"
FILE_TAX_RETURN = "file_tax_return"
VIEW_PAYROLL = "view_payroll"
MANAGE_EMPLOYEES = "manage_employees"
PROCESS_PAYROLL = "process_payroll"
APPROVE_PAYROLL = "approve_payroll"
PAY_PAYROLL = "pay_payroll"
VIEW_CONSOLIDATION="view_consolidation";MANAGE_CONSOLIDATION="manage_consolidation";RUN_CONSOLIDATION="run_consolidation";POST_ELIMINATIONS="post_eliminations";FINALISE_CONSOLIDATION="finalise_consolidation"
VIEW_MANUFACTURING="view_manufacturing"
MANAGE_BOMS="manage_boms"
CREATE_PRODUCTION_ORDER="create_production_order"
RELEASE_PRODUCTION_ORDER="release_production_order"
ISSUE_MATERIALS="issue_materials"
POST_PRODUCTION_COSTS="post_production_costs"
COMPLETE_PRODUCTION="complete_production"
CLOSE_PRODUCTION_ORDER="close_production_order"
USE_AI_ASSISTANT="use_ai_assistant"
VIEW_AI_INSIGHTS="view_ai_insights"
USE_AI_ACTIONS="use_ai_actions"
APPROVE_AI_ACTIONS="approve_ai_actions"
MANAGE_AI_SETTINGS="manage_ai_settings"

ALL_PERMISSIONS = frozenset(
    value for name, value in globals().copy().items()
    if name.isupper() and isinstance(value, str)
)

OPERATIONAL = {
    VIEW_ACCOUNTING, MANAGE_CONTACTS, MANAGE_ACCOUNTS,
    CREATE_JOURNAL, POST_JOURNAL, REVERSE_JOURNAL,
    CREATE_INVOICE, APPROVE_INVOICE, CREATE_CUSTOMER_PAYMENT,
    CREATE_BILL, APPROVE_BILL, CREATE_SUPPLIER_PAYMENT,
    CREATE_CUSTOMER_REFUND, CREATE_SUPPLIER_REFUND,
    CREATE_BAD_DEBT_WRITE_OFF, CREATE_CUSTOMER_CREDIT,
    APPROVE_CUSTOMER_CREDIT, CREATE_SUPPLIER_CREDIT,
    APPROVE_SUPPLIER_CREDIT, RECONCILE_BANK, UNRECONCILE_BANK,
    MANAGE_BANK_TRANSACTIONS, CLOSE_PERIOD, REOPEN_PERIOD,
    MANAGE_FINANCIAL_YEARS, CLOSE_FINANCIAL_YEAR,
    REOPEN_FINANCIAL_YEAR, EXPORT_REPORTS,
    VIEW_INVENTORY, MANAGE_PRODUCTS, MANAGE_WAREHOUSES, ADJUST_STOCK,
    CREATE_QUOTE, APPROVE_QUOTE, CREATE_SALES_ORDER, APPROVE_SALES_ORDER,
    FULFIL_SALES_ORDER, CREATE_PURCHASE_ORDER, APPROVE_PURCHASE_ORDER,
    RECEIVE_PURCHASE_ORDER,
    IMPORT_BANK_STATEMENTS, MANAGE_BANK_RULES,
    VIEW_FIXED_ASSETS, MANAGE_FIXED_ASSETS, RUN_DEPRECIATION,
    VIEW_TAX, MANAGE_TAX_RATES, PREPARE_TAX_RETURN,
    VIEW_PAYROLL, MANAGE_EMPLOYEES, PROCESS_PAYROLL, APPROVE_PAYROLL, PAY_PAYROLL,
    VIEW_CONSOLIDATION,MANAGE_CONSOLIDATION,RUN_CONSOLIDATION,POST_ELIMINATIONS,FINALISE_CONSOLIDATION,
    VIEW_MANUFACTURING,MANAGE_BOMS,CREATE_PRODUCTION_ORDER,RELEASE_PRODUCTION_ORDER,ISSUE_MATERIALS,
    POST_PRODUCTION_COSTS,COMPLETE_PRODUCTION,CLOSE_PRODUCTION_ORDER,
    USE_AI_ASSISTANT,VIEW_AI_INSIGHTS,USE_AI_ACTIONS,APPROVE_AI_ACTIONS,MANAGE_AI_SETTINGS,
}

ROLE_PERMISSIONS = {
    "owner": ALL_PERMISSIONS,
    "admin": ALL_PERMISSIONS,
    "accountant": OPERATIONAL,
    "bookkeeper": {
        VIEW_ACCOUNTING, MANAGE_CONTACTS, CREATE_JOURNAL,
        CREATE_INVOICE, CREATE_CUSTOMER_PAYMENT, CREATE_BILL,
        CREATE_SUPPLIER_PAYMENT, CREATE_CUSTOMER_CREDIT,
        CREATE_SUPPLIER_CREDIT, RECONCILE_BANK,
        MANAGE_BANK_TRANSACTIONS, EXPORT_REPORTS,
        VIEW_INVENTORY, MANAGE_PRODUCTS, MANAGE_WAREHOUSES, ADJUST_STOCK,
        CREATE_QUOTE, CREATE_SALES_ORDER, FULFIL_SALES_ORDER,
        CREATE_PURCHASE_ORDER, RECEIVE_PURCHASE_ORDER,
        IMPORT_BANK_STATEMENTS, MANAGE_BANK_RULES,
        VIEW_FIXED_ASSETS, MANAGE_FIXED_ASSETS, RUN_DEPRECIATION,
        VIEW_TAX, PREPARE_TAX_RETURN,
        VIEW_PAYROLL, MANAGE_EMPLOYEES, PROCESS_PAYROLL,
        VIEW_MANUFACTURING, MANAGE_BOMS, CREATE_PRODUCTION_ORDER,
        ISSUE_MATERIALS, POST_PRODUCTION_COSTS,
    },
    "approver": {
        VIEW_ACCOUNTING, POST_JOURNAL, APPROVE_INVOICE, APPROVE_BILL,
        APPROVE_CUSTOMER_CREDIT, APPROVE_SUPPLIER_CREDIT,
        CLOSE_PERIOD, EXPORT_REPORTS,
        VIEW_INVENTORY,
        APPROVE_QUOTE, APPROVE_SALES_ORDER, APPROVE_PURCHASE_ORDER,
        VIEW_FIXED_ASSETS, RUN_DEPRECIATION,
        VIEW_TAX, PREPARE_TAX_RETURN,
        VIEW_PAYROLL, APPROVE_PAYROLL,
        VIEW_MANUFACTURING, RELEASE_PRODUCTION_ORDER,
        COMPLETE_PRODUCTION, CLOSE_PRODUCTION_ORDER,
    },
    "viewer": {VIEW_ACCOUNTING, VIEW_INVENTORY, VIEW_FIXED_ASSETS, VIEW_TAX, VIEW_PAYROLL, VIEW_MANUFACTURING, EXPORT_REPORTS},
    "employee": {VIEW_ACCOUNTING},
}
