# Generated by Django 6.1 on 2026-08-13 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0016_alter_journalentry_source_type'),
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCostTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_order_id', models.UUIDField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('cost_type', models.CharField(choices=[('material', 'Material'), ('labour', 'Labour'), ('overhead', 'Overhead'), ('subcontract', 'Subcontract'), ('completion', 'Completion'), ('return', 'Return'), ('scrap', 'Scrap'), ('variance', 'Variance')], max_length=20)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_cost_transactions', to='accounting.journalentry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cost_transactions', to='organisations.organisation')),
            ],
            options={
                'ordering': ['transaction_date', 'created_at', 'id'],
            },
        ),
    ]
