# Generated by Django 6.1 on 2026-08-13 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_journalentry_source_type'),
        ('inventory', '0005_alter_stockmovement_movement_type_and_more'),
        ('manufacturing', '0001_initial'),
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='BOMVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=30)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('output_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='manufacturing.billofmaterials')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('scrap_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='inventory.product')),
                ('bom_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='manufacturing.bomversion')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('completed_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('in_progress', 'In progress'), ('partly_completed', 'Partly completed'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.bomversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='organisations.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders_released', to=settings.AUTH_USER_MODEL)),
                ('variance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_variance_orders', to='accounting.account')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
                ('wip_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_wip_orders', to='accounting.account')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrderComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('issued_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('returned_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('planned_unit_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('planned_total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.bomcomponent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='manufacturing.productionorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(fields=('organisation', 'code'), name='unique_bom_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='bomversion',
            constraint=models.UniqueConstraint(fields=('bom', 'version_number'), name='unique_bom_version'),
        ),
        migrations.AddConstraint(
            model_name='bomversion',
            constraint=models.CheckConstraint(condition=models.Q(('output_quantity__gt', 0)), name='bom_output_positive'),
        ),
        migrations.AddConstraint(
            model_name='bomcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bom_component_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='bomcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('scrap_percentage__gte', 0)), name='bom_scrap_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('organisation', 'order_number'), name='unique_production_order'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gt', 0)), name='production_planned_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionordercomponent',
            constraint=models.UniqueConstraint(fields=('production_order', 'product'), name='unique_order_component'),
        ),
    ]
