import { useEffect, useMemo, useRef, useState } from "react";
import { Bell, Building2, ChevronDown, CircleHelp, Landmark, LogOut, Menu, Search, Settings, UserRound, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { globalSearch } from "../../services/globalSearchService";
import { useAuth } from "../../store/AuthContext";

const resultIcons = { Customer: UserRound, Supplier: UserRound, Invoice: Landmark, Bill: Landmark, Account: Landmark, Product: Landmark, "Fixed Asset": Building2, "Production Order": Settings };

function Header({ onOpenMobileMenu }) {
  const auth = useAuth(); const navigate = useNavigate(); const root = useRef(null); const searchInput = useRef(null);
  const [open, setOpen] = useState(""); const [query, setQuery] = useState(""); const [groups, setGroups] = useState([]); const [loading, setLoading] = useState(false); const [active, setActive] = useState(-1);
  const name = [auth.user?.first_name, auth.user?.last_name].filter(Boolean).join(" ") || auth.user?.email || "User";
  const initials = name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const results = useMemo(() => groups.flatMap((group) => group.items), [groups]);
  const show = (panel) => { setOpen((current) => current === panel ? "" : panel); setActive(-1); };
  useEffect(() => {
    const close = (event) => { if (event.key === "Escape") { setOpen(""); searchInput.current?.blur(); } if (event.key === "k" && (event.metaKey || event.ctrlKey)) { event.preventDefault(); setOpen("search"); searchInput.current?.focus(); } };
    const outside = (event) => { if (!root.current?.contains(event.target)) setOpen(""); };
    window.addEventListener("keydown", close); document.addEventListener("mousedown", outside);
    return () => { window.removeEventListener("keydown", close); document.removeEventListener("mousedown", outside); };
  }, []);
  useEffect(() => {
    if (query.trim().length < 2) return undefined;
    let current = true;
    const timer = window.setTimeout(async () => { const data = await globalSearch(query); if (current) { setGroups(data); setLoading(false); setActive(-1); } }, 300);
    return () => { current = false; window.clearTimeout(timer); };
  }, [query]);
  const go = (item) => { setOpen(""); setQuery(""); navigate(item.path); };
  const changeQuery = (event) => { const value = event.target.value; setQuery(value); setActive(-1); if (value.trim().length < 2) { setGroups([]); setLoading(false); } else setLoading(true); };
  const searchKeys = (event) => { if (!results.length) return; if (event.key === "ArrowDown") { event.preventDefault(); setActive((value) => (value + 1) % results.length); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((value) => value <= 0 ? results.length - 1 : value - 1); } if (event.key === "Enter" && active >= 0) { event.preventDefault(); go(results[active]); } };
  const switchOrganisation = async (organisation) => { setOpen(""); if (organisation.id === auth.selectedOrganisation?.id) return; await auth.selectOrganisation(organisation); navigate("/", { replace: true }); window.location.reload(); };
  const logout = () => { setOpen(""); auth.logout(); };
  return <header className="header" ref={root}>
    <div className="header-left"><button type="button" className="header-menu-button" onClick={onOpenMobileMenu} aria-label="Open navigation menu"><Menu size={21}/></button><div className="header-popover-anchor"><button type="button" className="header-company-button" onClick={() => show("organisation")} aria-expanded={open === "organisation"}><span className="header-company-mark"><Building2 size={17}/></span><span className="header-company-copy"><small>Organisation</small><strong>{auth.selectedOrganisation?.name || "Select organisation"}</strong></span><ChevronDown size={15}/></button>{open === "organisation" && <div className="header-popover header-organisation-panel" role="menu"><div className="header-popover-title"><div><strong>Switch organisation</strong><span>Choose your current company</span></div></div>{auth.organisations.map((organisation) => <button type="button" role="menuitem" className={organisation.id === auth.selectedOrganisation?.id ? "is-selected" : ""} key={organisation.id} onClick={() => void switchOrganisation(organisation)}><span className="header-company-mark"><Building2 size={16}/></span><span><strong>{organisation.name}</strong><small>{organisation.role || "Member"}</small></span>{organisation.id === auth.selectedOrganisation?.id && <span className="header-current-label">Current</span>}</button>)}</div>}</div></div>
    <div className="header-search-wrap"><div className={`header-search ${open === "search" ? "is-active" : ""}`}><Search size={18}/><input ref={searchInput} value={query} onFocus={() => setOpen("search")} onChange={changeQuery} onKeyDown={searchKeys} type="search" placeholder="Search customers, invoices, accounts…" aria-label="Search Ledgify" aria-expanded={open === "search"}/><kbd>⌘K</kbd>{query && <button type="button" onClick={() => { setQuery(""); setGroups([]); setLoading(false); }} aria-label="Clear search"><X size={15}/></button>}</div>{open === "search" && <div className="header-popover header-search-panel"><div className="header-popover-title"><div><strong>Search Ledgify</strong><span>Results from your current organisation</span></div></div>{query.trim().length < 2 ? <div className="header-panel-state"><Search size={22}/><span>Enter at least 2 characters to search.</span></div> : loading ? <div className="header-panel-state"><span className="header-spinner"/>Searching…</div> : groups.length ? <div className="header-search-results">{groups.map((group) => <section key={group.label}><h3>{group.label}</h3>{group.items.map((item) => { const Icon = resultIcons[item.type] || Search; const index = results.findIndex((result) => result.type === item.type && result.id === item.id); return <button type="button" className={active === index ? "is-active" : ""} key={`${item.type}-${item.id}`} onMouseEnter={() => setActive(index)} onClick={() => go(item)}><span className="header-result-icon"><Icon size={16}/></span><span><strong>{item.title}</strong><small>{item.detail || item.type}</small></span><em>{item.type}</em></button>; })}</section>)}</div> : <div className="header-panel-state"><Search size={22}/><strong>No results found</strong><span>Try a code, name or reference.</span></div>}</div>}</div>
    <div className="header-actions"><button type="button" className="header-icon-button header-mobile-search" aria-label="Open search" onClick={() => { setOpen("search"); window.setTimeout(() => searchInput.current?.focus(), 0); }}><Search size={20}/></button><div className="header-popover-anchor"><button type="button" className="header-icon-button" aria-label="Notifications" title="Notifications" aria-expanded={open === "notifications"} onClick={() => show("notifications")}><Bell size={20}/></button>{open === "notifications" && <div className="header-popover header-notifications-panel"><div className="header-popover-title"><div><strong>Notifications</strong><span>Recent account activity</span></div></div><div className="header-panel-state"><Bell size={23}/><strong>No notifications</strong><span>Notification delivery is not configured yet.</span></div></div>}</div><div className="header-popover-anchor"><button type="button" className="header-profile" onClick={() => show("profile")} aria-label={`Open user menu for ${name}`} aria-expanded={open === "profile"}><span className="profile-avatar">{initials}</span><span className="profile-details"><strong>{name}</strong><span>{auth.selectedOrganisation?.role || "Member"}</span></span><ChevronDown size={15}/></button>{open === "profile" && <div className="header-popover header-profile-panel" role="menu"><div className="header-user-card"><span className="profile-avatar">{initials}</span><span><strong>{name}</strong><small>{auth.user?.email}</small><em>{auth.selectedOrganisation?.role || "Member"}</em></span></div><button type="button" role="menuitem" onClick={() => { setOpen(""); navigate("/settings"); }}><Settings size={17}/><span>Account &amp; organisation settings</span></button>{auth.organisations.length > 1 && <button type="button" role="menuitem" onClick={() => setOpen("organisation")}><Building2 size={17}/><span>Switch organisation</span></button>}<a role="menuitem" href="mailto:support@ledgify.app"><CircleHelp size={17}/><span>Help &amp; support</span></a><div className="header-menu-divider"/><button type="button" role="menuitem" className="header-logout" onClick={logout}><LogOut size={17}/><span>Log out</span></button></div>}</div></div>
  </header>;
}
export default Header;
