"""AI settings, proposals, and audit records that keep autonomous posting disabled."""

import uuid
from django.conf import settings
from django.db import models

class AISettings(models.Model):
    organisation=models.OneToOneField("organisations.Organisation",on_delete=models.CASCADE,related_name="ai_settings");ai_enabled=models.BooleanField(default=True);allow_financial_analysis=models.BooleanField(default=True);allow_draft_actions=models.BooleanField(default=True);allow_anomaly_detection=models.BooleanField(default=True);data_sharing_level=models.CharField(max_length=20,choices=(("minimal","Minimal"),("standard","Standard")),default="minimal");updated_at=models.DateTimeField(auto_now=True)
class AIConversation(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);organisation=models.ForeignKey("organisations.Organisation",on_delete=models.CASCADE,related_name="ai_conversations");user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="ai_conversations");title=models.CharField(max_length=200);status=models.CharField(max_length=10,choices=(("active","Active"),("archived","Archived")),default="active");created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
class AIMessage(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);conversation=models.ForeignKey(AIConversation,on_delete=models.CASCADE,related_name="messages");role=models.CharField(max_length=10,choices=(("user","User"),("assistant","Assistant"),("system","System"),("tool","Tool")));content=models.TextField();metadata=models.JSONField(default=dict);created_at=models.DateTimeField(auto_now_add=True)
class AIActionAudit(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);organisation=models.ForeignKey("organisations.Organisation",on_delete=models.CASCADE,related_name="ai_actions");user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name="ai_actions");conversation=models.ForeignKey(AIConversation,on_delete=models.SET_NULL,null=True,blank=True,related_name="actions");action_type=models.CharField(max_length=50);requested_action=models.TextField();proposed_payload=models.JSONField(default=dict);executed_payload=models.JSONField(null=True,blank=True);status=models.CharField(max_length=10,choices=(("proposed","Proposed"),("approved","Approved"),("executed","Executed"),("rejected","Rejected"),("failed","Failed")),default="proposed");result=models.JSONField(default=dict);created_at=models.DateTimeField(auto_now_add=True);executed_at=models.DateTimeField(null=True,blank=True)
class FinancialAnomaly(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);organisation=models.ForeignKey("organisations.Organisation",on_delete=models.CASCADE,related_name="financial_anomalies");anomaly_type=models.CharField(max_length=50);severity=models.CharField(max_length=10,choices=(("low","Low"),("medium","Medium"),("high","High"),("critical","Critical")));source_type=models.CharField(max_length=50);source_id=models.CharField(max_length=100,blank=True);detected_at=models.DateTimeField(auto_now_add=True);status=models.CharField(max_length=10,choices=(("open","Open"),("reviewed","Reviewed"),("dismissed","Dismissed"),("resolved","Resolved")),default="open");score=models.DecimalField(max_digits=5,decimal_places=2);summary=models.CharField(max_length=255);details=models.JSONField(default=dict);reviewed_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,null=True,blank=True);reviewed_at=models.DateTimeField(null=True,blank=True)
