# Generated by Django 6.1 on 2026-08-13 02:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0013_alter_journalentry_source_type'),
        ('organisations', '0002_organisation_require_separate_approver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_useful_life_months', models.PositiveIntegerField()),
                ('default_depreciation_method', models.CharField(choices=[('straight_line', 'Straight line'), ('reducing_balance', 'Reducing balance')], default='straight_line', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_categories_created', to=settings.AUTH_USER_MODEL)),
                ('default_accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_accumulation_categories', to='accounting.account')),
                ('default_asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_categories', to='accounting.account')),
                ('default_depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_expense_categories', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_asset_categories', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('in_service_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('useful_life_months', models.PositiveIntegerField()),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight line'), ('reducing_balance', 'Reducing balance')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('fully_depreciated', 'Fully depreciated'), ('disposed', 'Disposed')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_accumulated', to='accounting.account')),
                ('activation_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_fixed_asset', to='accounting.journalentry')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_created', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_depreciation_expense', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='organisations.organisation')),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.fixedassetcategory')),
            ],
            options={
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDisposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disposal_date', models.DateField()),
                ('disposal_type', models.CharField(choices=[('sale', 'Sale'), ('scrap', 'Scrap'), ('write_off', 'Write-off')], max_length=20)),
                ('proceeds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gain_or_loss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal', to='fixed_assets.fixedasset')),
                ('disposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_disposed', to=settings.AUTH_USER_MODEL)),
                ('gain_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_disposal_gains', to='accounting.account')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_disposal', to='accounting.journalentry')),
                ('loss_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_disposal_losses', to='accounting.account')),
                ('proceeds_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_disposal_proceeds', to='accounting.account')),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_value_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedule', to='accounting.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='fixed_assets.fixedasset')),
            ],
            options={
                'ordering': ['period'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'period'), name='unique_asset_depreciation_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='fixedassetcategory',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_fixed_asset_category_name'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(fields=('organisation', 'asset_number'), name='unique_fixed_asset_number'),
        ),
    ]
