# Generated by Django 6.1 on 2026-09-19 17:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def normalise_existing_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    from django.db.models import Count
    from django.db.models.functions import Lower, Trim
    collisions = User.objects.annotate(normalised=Lower(Trim("email"))).values("normalised").annotate(total=Count("id")).filter(total__gt=1).count()
    if collisions:
        raise RuntimeError("Case-insensitive email collisions exist. Run audit_identity_emails and resolve ownership before migrating; no accounts were merged.")
    User.objects.update(email=Lower(Trim("email")))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auth_version'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityEmailAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('verification', 'Verification'), ('invitation', 'Invitation')], max_length=20)),
                ('deduplication_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=16)),
                ('failure_category', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_version', models.CharField(max_length=100)),
                ('privacy_version', models.CharField(max_length=100)),
                ('terms_url', models.URLField()),
                ('privacy_url', models.URLField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('marketing_consent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RunPython(normalise_existing_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email')), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
