# Generated by Django 6.1 on 2026-09-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification_identityemailattempt_and_more'),
        ('organisations', '0009_organisation_accounting_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityemailattempt',
            name='invitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisationinvitation'),
        ),
        migrations.AddField(
            model_name='identityemailattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyacceptance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL),
        ),
    ]
