# Generated by Django 6.1 on 2026-08-13 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def seed_currencies(apps, schema_editor):
    Currency=apps.get_model("fx","Currency")
    for code,name,symbol,places in [("GBP","Pound sterling","£",2),("USD","US dollar","$",2),("EUR","Euro","€",2),("GHS","Ghana cedi","GH₵",2),("AUD","Australian dollar","A$",2),("CAD","Canadian dollar","C$",2),("JPY","Japanese yen","¥",0),("NZD","New Zealand dollar","NZ$",2)]:
        Currency.objects.get_or_create(code=code,defaults={"name":name,"symbol":symbol,"decimal_places":places})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0015_journalentry_exchange_rate_and_more'),
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FXRevaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revaluation_type', models.CharField(choices=[('receivables', 'Receivables'), ('payables', 'Payables'), ('bank', 'Bank accounts')], max_length=20)),
                ('as_of_date', models.DateField()),
                ('foreign_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('old_base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gain_loss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('foreign_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fx.currency')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluation', to='accounting.journalentry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_revaluations', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_rates', to='fx.currency')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='organisations.organisation')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_rates', to='fx.currency')),
            ],
            options={
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'base_currency', 'target_currency', 'effective_date'), name='unique_fx_rate_date'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='fx_rate_positive')],
            },
        ),
        migrations.RunPython(seed_currencies,migrations.RunPython.noop),
    ]
