# Generated by Django 6.1 on 2026-08-13 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_journalentry_source_type'),
        ('fx', '0001_initial'),
        ('organisations', '0004_organisation_fx_gain_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fxrevaluation',
            name='reversal_journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_fx_revaluation', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='fxrevaluation',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fxrevaluation',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluations_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fxrevaluation',
            name='source_reference',
            field=models.CharField(default='aggregate', max_length=100),
        ),
        migrations.AlterField(
            model_name='fxrevaluation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='fxrevaluation',
            constraint=models.UniqueConstraint(fields=('organisation', 'revaluation_type', 'as_of_date', 'foreign_currency', 'source_reference'), name='unique_fx_revaluation_exposure'),
        ),
    ]
