// Present employee and pay-run workflows without reproducing payroll calculations locally.

import {useEffect,useState} from "react";
import PageHeader from "../../components/layout/PageHeader";
import ReportExportMenu from "../../components/reports/ReportExportMenu";
import {accountingApiService} from "../../services/accountingApiService";
import {normaliseApiError} from "../../services/apiError";
import {payrollApiService} from "../../services/payrollApiService";
import {useAuth} from "../../store/AuthContext";

const today=()=>new Date().toISOString().slice(0,10);const list=(data)=>Array.isArray(data)?data:data.results||[];
export default function PayrollPage(){
 const {hasPermission}=useAuth();const [tab,setTab]=useState("runs");const [employees,setEmployees]=useState([]);const [components,setComponents]=useState([]);const [runs,setRuns]=useState([]);const [payslips,setPayslips]=useState([]);const [accounts,setAccounts]=useState([]);const [summary,setSummary]=useState({});const [error,setError]=useState("");
 const [employee,setEmployee]=useState({employee_number:"",first_name:"",last_name:"",email:"",phone:"",department:"",job_title:"",hire_date:today(),employment_status:"active",pay_frequency:"monthly",payment_method:"bank",bank_account_details:{},currency:"GBP"});
 const [component,setComponent]=useState({name:"",component_type:"earning",calculation_method:"fixed",default_account:"",liability_account:null,taxable:false,pensionable:false,active:true});
 const [run,setRun]=useState({pay_period_start:today().slice(0,8)+"01",pay_period_end:today(),payment_date:today(),payroll_liability_account:""});
 const load=async()=>{const [e,c,r,p,a,s]=await Promise.all([payrollApiService.employees(),payrollApiService.components(),payrollApiService.runs(),payrollApiService.payslips(),accountingApiService.accounts({status:"active"}),payrollApiService.summary()]);setEmployees(list(e));setComponents(list(c));setRuns(list(r));setPayslips(list(p));setAccounts(list(a));setSummary(s);};
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load().catch((x)=>setError(normaliseApiError(x))));return()=>cancelAnimationFrame(frame);},[]);
 const createEmployee=async(e)=>{e.preventDefault();try{await payrollApiService.createEmployee(employee);await load();}catch(x){setError(normaliseApiError(x));}};
 const createComponent=async(e)=>{e.preventDefault();try{await payrollApiService.createComponent({...component,liability_account:component.liability_account||null});await load();}catch(x){setError(normaliseApiError(x));}};
 const createRun=async(e)=>{e.preventDefault();try{await payrollApiService.createRun(run);await load();}catch(x){setError(normaliseApiError(x));}};
 const advance=async(id,action)=>{try{await payrollApiService[action](id);await load();}catch(x){setError(normaliseApiError(x));}};
 return <div className="products-page"><PageHeader eyebrow="Payroll" title="Payroll" description="Country-neutral employees, components, pay runs, payslips and accounting." />{error&&<div className="invoice-form-alert">{error}</div>}
 <div className="report-tabs">{["runs","employees","components","payslips","reports"].map(x=><button type="button" key={x} onClick={()=>setTab(x)} className={tab===x?"active":""}>{x}</button>)}</div>
 {tab==="employees"&&<><section className="invoice-form-card"><h2>Employees</h2><table><thead><tr><th>Number</th><th>Name</th><th>Department</th><th>Status</th><th>Frequency</th></tr></thead><tbody>{employees.map(x=><tr key={x.id}><td>{x.employee_number}</td><td>{x.full_name}</td><td>{x.department||"—"}</td><td>{x.employment_status}</td><td>{x.pay_frequency}</td></tr>)}</tbody></table></section>{hasPermission("manage_employees")&&<form className="invoice-form-card form-grid" onSubmit={createEmployee}><h2>Add employee</h2>{["employee_number","first_name","last_name","email","department","job_title","hire_date","currency"].map(k=><label key={k}>{k.replaceAll("_"," ")}<input required={["employee_number","first_name","last_name","hire_date","currency"].includes(k)} type={k.includes("date")?"date":"text"} value={employee[k]} onChange={e=>setEmployee({...employee,[k]:e.target.value})}/></label>)}<button className="button button-primary">Add employee</button></form>}</>}
 {tab==="components"&&<><section className="invoice-form-card"><h2>Components</h2><table><thead><tr><th>Name</th><th>Type</th><th>Method</th><th>Taxable</th><th>Active</th></tr></thead><tbody>{components.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.component_type}</td><td>{x.calculation_method}</td><td>{x.taxable?"Yes":"No"}</td><td>{x.active?"Yes":"No"}</td></tr>)}</tbody></table></section>{hasPermission("manage_employees")&&<form className="invoice-form-card form-grid" onSubmit={createComponent}><h2>Add component</h2><label>Name<input required value={component.name} onChange={e=>setComponent({...component,name:e.target.value})}/></label><label>Type<select value={component.component_type} onChange={e=>setComponent({...component,component_type:e.target.value})}><option value="earning">Earning</option><option value="deduction">Deduction</option><option value="employer_cost">Employer cost</option></select></label><label>Expense/control account<select required value={component.default_account} onChange={e=>setComponent({...component,default_account:e.target.value})}><option value="">Select…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>Liability account<select value={component.liability_account||""} onChange={e=>setComponent({...component,liability_account:e.target.value})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><button className="button button-primary">Add component</button></form>}</>}
 {tab==="runs"&&<><section className="invoice-form-card"><h2>Pay runs</h2><table><thead><tr><th>Period</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>{runs.map(x=><tr key={x.id}><td>{x.pay_period_start} – {x.pay_period_end}</td><td>{x.payment_date}</td><td>{x.status}</td><td>{x.status==="draft"&&<button onClick={()=>advance(x.id,"calculate")}>Calculate</button>} {x.status==="calculated"&&hasPermission("approve_payroll")&&<button onClick={()=>advance(x.id,"approve")}>Approve</button>} {x.status==="approved"&&<button onClick={()=>advance(x.id,"post")}>Post</button>}</td></tr>)}</tbody></table></section>{hasPermission("process_payroll")&&<form className="invoice-form-card form-grid" onSubmit={createRun}><h2>New pay run</h2>{["pay_period_start","pay_period_end","payment_date"].map(k=><label key={k}>{k.replaceAll("_"," ")}<input type="date" value={run[k]} onChange={e=>setRun({...run,[k]:e.target.value})}/></label>)}<label>Payroll liability<select required value={run.payroll_liability_account} onChange={e=>setRun({...run,payroll_liability_account:e.target.value})}><option value="">Select…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><button className="button button-primary">Create run</button></form>}</>}
 {tab==="payslips"&&<section className="invoice-form-card"><h2>Payslips</h2><table><thead><tr><th>Employee</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Payment</th></tr></thead><tbody>{payslips.map(x=><tr key={x.id}><td>{x.employee_name}</td><td>{x.gross_pay}</td><td>{x.deductions}</td><td>{x.net_pay}</td><td>{x.payment_status}</td></tr>)}</tbody></table></section>}
 {tab==="reports"&&<section className="invoice-form-card"><div className="section-heading"><h2>Payroll summary</h2><ReportExportMenu title="Payroll Summary" rows={[summary]}/></div><dl className="summary-list">{Object.entries(summary).map(([k,v])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{v}</dd></div>)}</dl></section>}
 </div>;
}
