// Present employee and pay-run workflows without reproducing payroll calculations locally.

import {useEffect,useMemo,useState} from "react";
import {Banknote,CalendarDays,CircleDollarSign,Download,Landmark,ReceiptText,RefreshCw,Users} from "lucide-react";
import PageHeader from "../../components/layout/PageHeader";
import ReportExportMenu from "../../components/reports/ReportExportMenu";
import {accountingApiService} from "../../services/accountingApiService";
import {normaliseApiError} from "../../services/apiError";
import {payrollApiService} from "../../services/payrollApiService";
import {useAuth} from "../../store/AuthContext";
import {formatCurrency} from "../../utils/currency";
import "../../styles/payrollReports.css";

const today=()=>new Date().toISOString().slice(0,10);const list=(data)=>Array.isArray(data)?data:data.results||[];
const reportOptions=[
 ["summary","Summary","Payroll totals across the selected payment period."],
 ["earnings","Employee earnings","Gross pay, deductions and net pay by employee."],
 ["liability","Payroll liability","Net payroll paid and still outstanding."],
 ["yearToDate","Year to date","Employee totals for a complete calendar year."],
];
const displayDate=(value)=>value?new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`)):"—";
function PayrollReports(){
 const {selectedOrganisation}=useAuth();const currency=selectedOrganisation?.base_currency||"GBP";const yearNow=Number(today().slice(0,4));
 const [report,setReport]=useState("summary");const [filters,setFilters]=useState({start_date:`${yearNow}-01-01`,end_date:today(),year:yearNow});const [applied,setApplied]=useState({start_date:`${yearNow}-01-01`,end_date:today(),year:yearNow});const [data,setData]=useState(null);const [state,setState]=useState({loading:true,error:""});
 useEffect(()=>{let active=true;const request=report==="yearToDate"?payrollApiService.yearToDate(applied.year):payrollApiService[report]({start_date:applied.start_date,end_date:applied.end_date});request.then(value=>{if(active){setData(value);setState({loading:false,error:""});}}).catch(error=>{if(active)setState({loading:false,error:normaliseApiError(error,"Payroll report could not be loaded.")});});return()=>{active=false;};},[applied,report]);
 const rows=useMemo(()=>Array.isArray(data)?data:[],[data]);const totals=useMemo(()=>rows.reduce((result,row)=>({gross:Number(result.gross)+Number(row.gross_pay||0),deductions:Number(result.deductions)+Number(row.deductions||0),net:Number(result.net)+Number(row.net_pay||0)}),{gross:0,deductions:0,net:0}),[rows]);
 const summary=data&&!Array.isArray(data)?data:{};const cards=report==="liability"?[["Net payroll",summary.net,Banknote],["Amount paid",summary.paid,CircleDollarSign],["Outstanding",summary.outstanding,Landmark],["Employer costs",summary.employer_costs,ReceiptText]]:report==="summary"?[["Gross payroll",summary.gross,Banknote],["Deductions",summary.deductions,ReceiptText],["Net payroll",summary.net,CircleDollarSign],["Employer costs",summary.employer_costs,Users]]:[["Employees",rows.length,Users],["Gross earnings",totals.gross,Banknote],["Deductions",totals.deductions,ReceiptText],["Net earnings",totals.net,CircleDollarSign]];
 const exportRows=rows.length?rows.map(row=>({employee_number:row.employee__employee_number,employee:`${row.employee__first_name} ${row.employee__last_name}`.trim(),gross_pay:Number(row.gross_pay||0),deductions:Number(row.deductions||0),net_pay:Number(row.net_pay||0)})):[{gross:Number(summary.gross||0),deductions:Number(summary.deductions||0),employer_costs:Number(summary.employer_costs||0),net:Number(summary.net||0),paid:Number(summary.paid||0),...(report==="liability"?{outstanding:Number(summary.outstanding||0)}:{})}];
 const selected=reportOptions.find(([id])=>id===report);
 return <section className="payroll-report-workspace">
  <div className="payroll-report-heading"><div><span className="payroll-report-eyebrow">Payroll reporting</span><h2>{selected[1]}</h2><p>{selected[2]}</p></div><ReportExportMenu title={`Payroll ${selected[1]}`} rows={exportRows} metadata={{organisation:selectedOrganisation?.name,currency,...applied}} disabled={state.loading||Boolean(state.error)}/></div>
  <nav className="payroll-report-nav" aria-label="Payroll reports">{reportOptions.map(([id,label,description])=><button type="button" key={id} className={report===id?"is-active":""} onClick={()=>{if(id!==report){setState({loading:true,error:""});setReport(id);}}}><strong>{label}</strong><span>{description}</span></button>)}</nav>
  <form className="payroll-report-filters" onSubmit={event=>{event.preventDefault();setState({loading:true,error:""});setApplied({...filters});}}>{report==="yearToDate"?<label><span>Calendar year</span><select value={filters.year} onChange={event=>setFilters({...filters,year:Number(event.target.value)})}>{Array.from({length:6},(_,index)=>yearNow-index).map(year=><option key={year} value={year}>{year}</option>)}</select></label>:<><label><span>Payment date from</span><input type="date" value={filters.start_date} max={filters.end_date} onChange={event=>setFilters({...filters,start_date:event.target.value})}/></label><label><span>Payment date to</span><input type="date" value={filters.end_date} min={filters.start_date} onChange={event=>setFilters({...filters,end_date:event.target.value})}/></label></>}<button className="page-primary-button"><RefreshCw size={16}/>Run report</button><div className="payroll-report-period"><CalendarDays size={16}/><span>{report==="yearToDate"?`Year ending 31 Dec ${applied.year}`:`${displayDate(applied.start_date)} – ${displayDate(applied.end_date)}`}</span></div></form>
  {state.loading?<div className="payroll-report-state"><span className="payroll-report-spinner"/><strong>Preparing payroll report…</strong><p>Reading posted and paid payroll records.</p></div>:state.error?<div className="payroll-report-state is-error"><strong>Report unavailable</strong><p>{state.error}</p><button type="button" onClick={()=>{setState({loading:true,error:""});setApplied({...filters});}}>Try again</button></div>:<>
   <div className="payroll-report-cards">{cards.map(([label,value,Icon],index)=><article key={label} className={label==="Outstanding"&&Number(value)>0?"is-attention":""}><div><Icon size={19}/></div><span>{label}</span><strong>{index===0&&report!=="summary"&&report!=="liability"?Number(value||0).toLocaleString("en-GB"):formatCurrency(value,currency)}</strong></article>)}</div>
   {rows.length?<div className="payroll-report-table-wrap"><table className="payroll-report-table"><thead><tr><th>Employee</th><th>Employee no.</th><th className="is-numeric">Gross pay</th><th className="is-numeric">Deductions</th><th className="is-numeric">Net pay</th></tr></thead><tbody>{rows.map(row=><tr key={row.employee_id}><td><strong>{row.employee__first_name} {row.employee__last_name}</strong></td><td>{row.employee__employee_number}</td><td className="is-numeric">{formatCurrency(row.gross_pay,currency)}</td><td className="is-numeric">{formatCurrency(row.deductions,currency)}</td><td className="is-numeric payroll-net-value">{formatCurrency(row.net_pay,currency)}</td></tr>)}</tbody><tfoot><tr><td colSpan="2">Report total</td><td className="is-numeric">{formatCurrency(totals.gross,currency)}</td><td className="is-numeric">{formatCurrency(totals.deductions,currency)}</td><td className="is-numeric">{formatCurrency(totals.net,currency)}</td></tr></tfoot></table></div>:report!=="summary"&&report!=="liability"?<div className="payroll-report-state"><Users size={28}/><strong>No payroll activity found</strong><p>No posted or paid payslips match this reporting period.</p></div>:<div className="payroll-report-note"><Download size={17}/><span>Totals include posted and paid payroll only. Use Export to download the displayed report with its period and currency context.</span></div>}
  </>}
 </section>;
}
export default function PayrollPage(){
 const {hasPermission}=useAuth();const [tab,setTab]=useState("runs");const [employees,setEmployees]=useState([]);const [components,setComponents]=useState([]);const [runs,setRuns]=useState([]);const [payslips,setPayslips]=useState([]);const [accounts,setAccounts]=useState([]);const [error,setError]=useState("");
 const [employee,setEmployee]=useState({employee_number:"",first_name:"",last_name:"",email:"",phone:"",department:"",job_title:"",hire_date:today(),employment_status:"active",pay_frequency:"monthly",payment_method:"bank",bank_account_details:{},currency:"GBP"});
 const [component,setComponent]=useState({name:"",component_type:"earning",calculation_method:"fixed",default_account:"",liability_account:null,taxable:false,pensionable:false,active:true});
 const [run,setRun]=useState({pay_period_start:today().slice(0,8)+"01",pay_period_end:today(),payment_date:today(),payroll_liability_account:""});
 const load=async()=>{const [e,c,r,p,a]=await Promise.all([payrollApiService.employees(),payrollApiService.components(),payrollApiService.runs(),payrollApiService.payslips(),accountingApiService.accounts({status:"active"})]);setEmployees(list(e));setComponents(list(c));setRuns(list(r));setPayslips(list(p));setAccounts(list(a));};
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load().catch((x)=>setError(normaliseApiError(x))));return()=>cancelAnimationFrame(frame);},[]);
 const createEmployee=async(e)=>{e.preventDefault();try{await payrollApiService.createEmployee(employee);await load();}catch(x){setError(normaliseApiError(x));}};
 const createComponent=async(e)=>{e.preventDefault();try{await payrollApiService.createComponent({...component,liability_account:component.liability_account||null});await load();}catch(x){setError(normaliseApiError(x));}};
 const createRun=async(e)=>{e.preventDefault();try{await payrollApiService.createRun(run);await load();}catch(x){setError(normaliseApiError(x));}};
 const advance=async(id,action)=>{try{await payrollApiService[action](id);await load();}catch(x){setError(normaliseApiError(x));}};
 return <div className="products-page"><PageHeader eyebrow="Payroll" title="Payroll" description="Country-neutral employees, components, pay runs, payslips and accounting." />{error&&<div className="invoice-form-alert">{error}</div>}
 <div className="report-tabs">{["runs","employees","components","payslips","reports"].map(x=><button type="button" key={x} onClick={()=>setTab(x)} className={tab===x?"active":""}>{x}</button>)}</div>
 {tab==="employees"&&<><section className="invoice-form-card"><h2>Employees</h2><table><thead><tr><th>Number</th><th>Name</th><th>Department</th><th>Status</th><th>Frequency</th></tr></thead><tbody>{employees.map(x=><tr key={x.id}><td>{x.employee_number}</td><td>{x.full_name}</td><td>{x.department||"—"}</td><td>{x.employment_status}</td><td>{x.pay_frequency}</td></tr>)}</tbody></table></section>{hasPermission("manage_employees")&&<form className="invoice-form-card form-grid" onSubmit={createEmployee}><h2>Add employee</h2>{["employee_number","first_name","last_name","email","department","job_title","hire_date","currency"].map(k=><label key={k}>{k.replaceAll("_"," ")}<input required={["employee_number","first_name","last_name","hire_date","currency"].includes(k)} type={k.includes("date")?"date":"text"} value={employee[k]} onChange={e=>setEmployee({...employee,[k]:e.target.value})}/></label>)}<button className="button button-primary">Add employee</button></form>}</>}
 {tab==="components"&&<><section className="invoice-form-card"><h2>Components</h2><table><thead><tr><th>Name</th><th>Type</th><th>Method</th><th>Taxable</th><th>Active</th></tr></thead><tbody>{components.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.component_type}</td><td>{x.calculation_method}</td><td>{x.taxable?"Yes":"No"}</td><td>{x.active?"Yes":"No"}</td></tr>)}</tbody></table></section>{hasPermission("manage_employees")&&<form className="invoice-form-card form-grid" onSubmit={createComponent}><h2>Add component</h2><label>Name<input required value={component.name} onChange={e=>setComponent({...component,name:e.target.value})}/></label><label>Type<select value={component.component_type} onChange={e=>setComponent({...component,component_type:e.target.value})}><option value="earning">Earning</option><option value="deduction">Deduction</option><option value="employer_cost">Employer cost</option></select></label><label>Expense/control account<select required value={component.default_account} onChange={e=>setComponent({...component,default_account:e.target.value})}><option value="">Select…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>Liability account<select value={component.liability_account||""} onChange={e=>setComponent({...component,liability_account:e.target.value})}><option value="">None</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><button className="button button-primary">Add component</button></form>}</>}
 {tab==="runs"&&<><section className="invoice-form-card"><h2>Pay runs</h2><table><thead><tr><th>Period</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>{runs.map(x=><tr key={x.id}><td>{x.pay_period_start} – {x.pay_period_end}</td><td>{x.payment_date}</td><td>{x.status}</td><td>{x.status==="draft"&&<button onClick={()=>advance(x.id,"calculate")}>Calculate</button>} {x.status==="calculated"&&hasPermission("approve_payroll")&&<button onClick={()=>advance(x.id,"approve")}>Approve</button>} {x.status==="approved"&&<button onClick={()=>advance(x.id,"post")}>Post</button>}</td></tr>)}</tbody></table></section>{hasPermission("process_payroll")&&<form className="invoice-form-card form-grid" onSubmit={createRun}><h2>New pay run</h2>{["pay_period_start","pay_period_end","payment_date"].map(k=><label key={k}>{k.replaceAll("_"," ")}<input type="date" value={run[k]} onChange={e=>setRun({...run,[k]:e.target.value})}/></label>)}<label>Payroll liability<select required value={run.payroll_liability_account} onChange={e=>setRun({...run,payroll_liability_account:e.target.value})}><option value="">Select…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><button className="button button-primary">Create run</button></form>}</>}
 {tab==="payslips"&&<section className="invoice-form-card"><h2>Payslips</h2><table><thead><tr><th>Employee</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Payment</th></tr></thead><tbody>{payslips.map(x=><tr key={x.id}><td>{x.employee_name}</td><td>{x.gross_pay}</td><td>{x.deductions}</td><td>{x.net_pay}</td><td>{x.payment_status}</td></tr>)}</tbody></table></section>}
 {tab==="reports"&&<PayrollReports/>}
 </div>;
}
