# Generated by Django 6.1 on 2026-08-09 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(choices=[('immediate', 'Due immediately'), ('7_days', '7 days'), ('14_days', '14 days'), ('30_days', '30 days'), ('60_days', '60 days')], default='30_days', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organisation', 'name'], name='contacts_co_organis_387799_idx'), models.Index(fields=['organisation', 'is_customer'], name='contacts_co_organis_5e24e2_idx'), models.Index(fields=['organisation', 'is_supplier'], name='contacts_co_organis_67dc53_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('account_number', ''), _negated=True), fields=('organisation', 'account_number'), name='unique_contact_account_number_per_organisation')],
            },
        ),
    ]
