# Generated by Django 6.1 on 2026-08-13 03:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0014_alter_journalentry_source_type'),
        ('organisations', '0003_organisation_tax_effective_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('pay_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('other', 'Other')], default='monthly', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank transfer'), ('cash', 'Cash'), ('other', 'Other')], default='bank', max_length=20)),
                ('bank_account_details', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organisations.organisation')),
            ],
            options={
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_cost', 'Employer cost')], max_length=20)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed amount'), ('quantity_rate', 'Quantity × rate'), ('adapter', 'Jurisdiction adapter')], default='fixed', max_length=30)),
                ('taxable', models.BooleanField(default=False)),
                ('pensionable', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_components', to='accounting.account')),
                ('liability_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_liability_components', to='accounting.account')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_components', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayrollComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_components', to='payroll.employee')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='payroll.payrollcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('posted', 'Posted'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='organisations.organisation')),
                ('payroll_liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='accounting.account')),
            ],
            options={
                'ordering': ['-pay_period_end'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments_created', to=settings.AUTH_USER_MODEL)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment', to='accounting.journalentry')),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('employer_costs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.employee')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payslips', to='accounting.journalentry')),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('taxable', models.BooleanField(default=False)),
                ('pensionable', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='accounting.account')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='payroll.payrollcomponent')),
                ('liability_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslip_liability_lines', to='accounting.account')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payroll.payslip')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organisation', 'employee_number'), name='unique_employee_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payrollcomponent',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_payroll_component_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employeepayrollcomponent',
            constraint=models.UniqueConstraint(fields=('employee', 'component'), name='unique_employee_payroll_component'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('organisation', 'pay_period_start', 'pay_period_end'), name='unique_payroll_run_period'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('pay_run', 'employee'), name='unique_employee_payslip_per_run'),
        ),
    ]
