import { useState } from 'react';
import { Check, ChevronRight, Circle, Info, Search, ShieldCheck } from 'lucide-react';
import { taxUiLabel, componentSummary, filterTaxVersions, setupProgress } from '../../utils/taxSettingsPresentation.js';

export function TaxBadge({value, children}) { return <span className={`tax-settings-badge tone-${['ACTIVE','APPROVED','FILED','PAID'].includes(value)?'success':['DRAFT','PENDING_APPROVAL','PENDING_VERIFICATION','SCHEDULED'].includes(value)?'attention':['REJECTED','INVALID'].includes(value)?'error':'neutral'}`}>{children || taxUiLabel(value)}</span>; }
export function TaxEmpty({title,children}) {return <div className="tax-settings-empty"><Info size={20} aria-hidden="true"/><div><h3>{title}</h3><p>{children}</p></div></div>;}
export function TaxSummary({items}) {return <dl className="tax-settings-summary">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value ?? 'Not recorded'}</dd></div>)}</dl>;}
export function TaxSettingsNav({tab,onChange}) {
 const tabs=[['Dashboard','Overview'],['Profile','Tax Profile'],['Registrations','Registrations'],['Codes & versions','Tax Rates and Codes'],['Mapping','Account Mapping'],['Returns','Returns and Filing'],['History','Configuration History'],['EVAT','GRA E-VAT']];
 return <nav className="tax-settings-nav" aria-label="Tax Settings sections"><div role="tablist" aria-label="Tax Settings" onKeyDown={event=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();const index=tabs.findIndex(([key])=>key===tab);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;onChange(tabs[next][0]);event.currentTarget.querySelectorAll('[role=tab]')[next].focus();}}>{tabs.map(([key,label])=><button key={key} id={`tax-tab-${key.replaceAll(' ','-')}`} type="button" role="tab" aria-selected={tab===key} aria-controls="tax-settings-panel" tabIndex={tab===key?0:-1} onClick={()=>onChange(key)}>{label}</button>)}</div></nav>;
}
export function TaxSetupProgress({active,profiles,versions,onContinue,canConfigure}) {
 if(active)return <div className="tax-settings-ready"><ShieldCheck size={18} aria-hidden="true"/><span><strong>Configuration active</strong> · Version {active.version} · Effective {active.effective_from}</span><span>Posted history is retained</span></div>;
 const progress=setupProgress(profiles,versions);
 return <section className="tax-settings-progress"><div className="tax-settings-section-heading"><div><h2>Complete your tax setup</h2><p>Review each part before approving and activating your configuration.</p></div><strong>{progress.percent}%</strong></div><progress value={progress.percent} max="100" aria-label="Tax setup progress"/><ol>{progress.steps.map((step,i)=><li key={step.label} className={step.done?'is-complete':i===progress.current?'is-current':''} aria-current={i===progress.current?'step':undefined}>{step.done?<Check size={17} aria-hidden="true"/>:<Circle size={17} aria-hidden="true"/>}<span>{step.label}</span></li>)}</ol>{canConfigure&&<button type="button" className="tax-settings-primary" onClick={onContinue}>Continue setup<ChevronRight size={16} aria-hidden="true"/></button>}</section>;
}
export function TaxStructureChoices({value,onChange,country,active,effectiveDate}) {
 const choices=[['GHANA_GRA','Ghana – GRA Tax Structure','Ghana VAT, NHIL, GETFund and supported withholding configuration','Recommended for Ghana organisations'],['CUSTOM_INTERNATIONAL','Custom / International','Create and maintain organisation-specific tax rules','Suitable for other jurisdictions'],['NO_TAX','No Tax','Record transactions without tax calculations','For organisations not currently applying tax']];
 return <fieldset className="tax-structure-choices"><legend>Tax structure</legend><div>{choices.filter(([key])=>key!=='GHANA_GRA'||country==='GH').map(([key,title,description,note])=><label key={key} className={value===key?'is-selected':''}><div><input required type="radio" name="tax-structure" value={key} checked={value===key} onChange={e=>onChange(e.target.value)}/><strong>{title}</strong>{value===key&&<TaxBadge>Selected</TaxBadge>}</div><p>{description}</p><small>{note}</small>{active?.structure===key&&<small>Current · Effective {active.effective_from}</small>}{value===key&&effectiveDate&&<small>Proposed effective date · {effectiveDate}</small>}</label>)}</div></fieldset>;
}
export function TaxConfigurationSummary({profile,history=[],onEdit,canEdit}) {
 if(!profile)return <TaxEmpty title="Configuration not started">Choose a tax structure, then enter the registrations that apply to your organisation.</TaxEmpty>;
 const reg=profile.registration||{};const reviewed=history.find(event=>/review/i.test(event.event)&&event.subject_id===profile.id);
 return <section><div className="tax-settings-section-heading"><div><h2>Configuration summary</h2><p>Current organisation settings and approval information.</p></div>{canEdit&&<button type="button" onClick={onEdit}>Create new version</button>}</div><TaxSummary items={[
 ['Tax structure',taxUiLabel(profile.structure)],['Configuration version',`Version ${profile.version}`],['Effective date',profile.effective_from],['VAT registration status',reg.vat_registered?'Registered':'Not registered'],['Withholding-agent status',reg.wht_agent?'Enabled':'Not enabled'],['VAT-withholding-agent status',reg.vat_wht_agent?'Enabled':'Not enabled'],['Reporting frequency',taxUiLabel(reg.frequency)],['Last reviewed date',reviewed?.created_at || (profile.reviewed_by?'Reviewed; date not recorded':'Not reviewed')],['Approval status',<TaxBadge value={profile.status}/>]
 ]}/></section>;
}
export function TaxComposition({active,versions,codes}) {
 if(active?.structure!=='GHANA_GRA')return null;
 const version=versions.find(v=>v.display_status==='ACTIVE'&&v.classification==='STANDARD'&&['SALES','BOTH'].includes(codes.find(c=>c.id===v.code)?.scope));
 if(!version)return <section><h2>Ghana tax structure</h2><TaxEmpty title="No active standard sales version">Review your tax codes and approved effective dates before applying tax.</TaxEmpty></section>;
 const standard=version.components.length===3&&[['VAT',15],['NHIL',2.5],['GETFUND',2.5]].every(([key,rate])=>version.components.some(c=>c.code.toUpperCase()===key&&Number(c.rate)===rate&&c.kind!=='FIXED'&&!(c.depends_on||[]).length));
 return <section><div className="tax-settings-section-heading"><div><h2>Ghana tax composition</h2><p>{componentSummary(version.components)}</p></div><TaxBadge value={version.status}/></div><TaxSummary items={[
 ['Version',`Version ${version.number}`],['Effective date',version.effective_from],['Source / reference',version.source||'Not recorded'],['Rule origin',version.provenance==='ORGANISATION_OVERRIDE'?'Organisation-created rule':taxUiLabel(version.provenance)]
 ]} />{version.provenance==='ORGANISATION_OVERRIDE'&&<p className="tax-settings-alert">Organisation-created rule. Not verified by GRA or Ledgify. Confirm this rate and treatment with your accountant or the Ghana Revenue Authority.</p>}{standard?<div className="tax-composition-example"><h3>Taxable value example: GHS 1,000.00</h3><table><thead><tr><th>Component</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{[['VAT','15%','GHS 150.00'],['NHIL','2.5%','GHS 25.00'],['GETFund','2.5%','GHS 25.00'],['Total tax','20%','GHS 200.00'],['Invoice total','—','GHS 1,200.00']].map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table><p>All components are calculated on the same taxable value.</p><small>Reference illustration for the displayed standard structure. Existing transaction calculations remain authoritative.</small></div>:<p>Use “Compare calculations on 1,000” in the version editor to preview this organisation’s structure through the existing tax service.</p>}</section>;
}
export function TaxRateTable({versions,codes,selectedCode,renderActions}) {
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[classification,setClassification]=useState(''),[activeOnly,setActiveOnly]=useState(false),[ascending,setAscending]=useState(false);
 const rows=filterTaxVersions(versions,codes,{search,status,classification,activeOnly,ascending,selectedCode});
 return <><div className="tax-settings-filters"><label>Search codes and names<div className="tax-settings-search"><Search size={16} aria-hidden="true"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tax codes"/></div></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(versions.map(v=>v.display_status||v.status))].sort().map(value=><option key={value} value={value}>{taxUiLabel(value)}</option>)}</select></label><label>Classification<select value={classification} onChange={e=>setClassification(e.target.value)}><option value="">All classifications</option>{[...new Set(versions.map(v=>v.classification))].sort().map(value=><option key={value} value={value}>{taxUiLabel(value)}</option>)}</select></label><label>Effective date order<select value={ascending?'oldest':'newest'} onChange={e=>setAscending(e.target.value==='oldest')}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label><label className="tax-settings-check"><input type="checkbox" checked={activeOnly} onChange={e=>setActiveOnly(e.target.checked)}/>Show active only</label></div>{!rows.length?<TaxEmpty title="No matching tax versions">{versions.length?'Adjust the filters or select a different code.':'Create a code and prepare a version for review.'}</TaxEmpty>:<div className="tax-settings-table-wrap"><table className="tax-settings-table"><thead><tr>{['Code','Tax name','Classification','Components / rate','Applies to'].map(label=><th key={label}>{label}</th>)}<th aria-sort={ascending?'ascending':'descending'}>Effective period {ascending?'↑':'↓'}</th><th>Source</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(v=>{const code=codes.find(c=>c.id===v.code);return <tr key={v.id}><td data-label="Code"><strong>{code?.code||'Tax code'}</strong><small>Version {v.number}</small></td><td data-label="Tax name">{code?.name||'Not recorded'}</td><td data-label="Classification"><TaxBadge value={v.classification}/></td><td data-label="Components / rate">{componentSummary(v.components)}</td><td data-label="Applies to">{taxUiLabel(code?.scope)}</td><td data-label="Effective period">{v.effective_from}<small>{v.effective_to?`Until ${v.effective_to}`:'No end date'}</small></td><td data-label="Source">{v.provenance==='ORGANISATION_OVERRIDE'?<><TaxBadge>Organisation-created rule</TaxBadge><small>Not verified by GRA or Ledgify.</small></>:taxUiLabel(v.verification_state||v.provenance)}<small>{v.source||'No source recorded'}</small></td><td data-label="Status"><TaxBadge value={v.display_status||v.status}/></td><td data-label="Actions"><details><summary>Version actions</summary><div className="tax-settings-actions">{renderActions(v)}</div></details></td></tr>;})}</tbody></table></div>}</>;
}
export function ReadableTaxRecord({value,accounts=[],codes=[],members=[]}) {
 if(value==null||value==='')return <span className="tax-settings-muted">Not recorded</span>;
 if(typeof value==='boolean')return <span>{value?'Enabled':'Not enabled'}</span>;
 if(typeof value!=='object'){const account=accounts.find(a=>a.id===value),code=codes.find(c=>c.id===value),member=members.find(m=>m.id===value);return <span>{account?`${account.code} · ${account.name}`:code?`${code.code} · ${code.name}`:member?.name||(/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(value))?'Recorded reference':taxUiLabel(value)==='Organisation-created rule'?'Organisation-created rule — not verified by GRA or Ledgify':String(value))}</span>;}
 if(Array.isArray(value))return value.length?<ul className="tax-record-list">{value.map((item,i)=><li key={i}><ReadableTaxRecord value={item} accounts={accounts} codes={codes} members={members}/></li>)}</ul>:<span className="tax-settings-muted">None recorded</span>;
 const entries=Object.entries(value).filter(([key])=>!['id','organisation','checksum','snapshot_checksum'].includes(key));
 if(!entries.length)return <span className="tax-settings-muted">None recorded</span>;
 return <dl className="tax-record-fields">{entries.map(([key,item])=><div key={key}><dt>{taxUiLabel(key)}</dt><dd><ReadableTaxRecord value={item} accounts={accounts} codes={codes} members={members}/></dd></div>)}</dl>;
}
export function TaxRegistrationsSummary({profile,dashboard,versions,codes,onEdit,canEdit}) {
 const reg=profile?.registration||{};
 const supported=family=>versions.some(v=>v.display_status==='ACTIVE'&&codes.find(c=>c.id===v.code)?.family===family&&(family==='INDIRECT'||v.rules?.verified===true))?'Fully supported':'Pending verification';
 return <section><div className="tax-settings-section-heading"><div><h2>Registrations and obligations</h2><p>Registration is never inferred from your organisation’s country.</p></div>{canEdit&&<button type="button" onClick={onEdit}>Review registration fields</button>}</div>{!profile?<TaxEmpty title="No registrations recorded">Start a tax profile to record your organisation’s registrations.</TaxEmpty>:<div className="tax-registration-cards">{[['VAT registration','vat_registered','vat_registration_number','vat_effective_from','vat_effective_to',supported('INDIRECT')],['Withholding Tax','wht_agent','tin','wht_effective_from',null,supported('WHT')],['VAT withholding','vat_wht_agent','tin','vat_wht_effective_from',null,supported('VAT_WHT')],['PAYE / employer status','paye_employer','tin','paye_effective_from',null,'Tracking only']].map(([label,flag,id,start,end,support])=><article key={flag}><h3>{label}</h3><TaxSummary items={[
 ['Registration status',reg[flag]?'Registered':'Not registered'],['Identifier',reg[id]||'Not recorded'],['Effective date',reg[start]||'Not recorded'],...(end?[['Deregistration date',reg[end]||'Not recorded']]:[]),['Reporting frequency',taxUiLabel(reg.frequency)],['Calculation support',!reg[flag]?'Not enabled':support]
 ]}/></article>)}</div>}<h3>Other tracked obligations</h3>{(reg.obligations||[]).length?<ul className="tax-obligation-list">{reg.obligations.map(item=><li key={item}><strong>{taxUiLabel(item)}</strong><TaxBadge>Tracking only</TaxBadge></li>)}</ul>:<p className="tax-settings-muted">No other obligations recorded.</p>}{dashboard?.registrations?.length>0&&<details><summary>Recorded obligation details</summary><ReadableTaxRecord value={dashboard.registrations}/></details>}</section>;
}
export function TaxMappingSummary({profile,accounts,roles,onEdit,canEdit}) {
 const mapped=roles.filter(role=>accounts.some(a=>a.id===profile?.mappings?.[role]));
 const groups=[['Sales / output tax accounts',role=>role.startsWith('output_')],['Purchase / input tax accounts',role=>role.startsWith('input_')],['Withholding payable',role=>role.includes('wht')&&role.includes('payable')&&!role.includes('vat')],['Withholding receivable',role=>role.includes('wht')&&role.includes('receivable')&&!role.includes('vat')],['VAT-withholding accounts',role=>role.includes('vat_wht')],['Tax adjustments and other controls',role=>!role.startsWith('output_')&&!role.startsWith('input_')&&!role.includes('wht')]];
 return <section><div className="tax-settings-section-heading"><div><h2>Account mapping</h2><p>{mapped.length} mappings complete · {roles.length-mapped.length} require attention</p></div>{canEdit&&<button type="button" onClick={onEdit}>Review account mappings</button>}</div>{groups.map(([label,test])=>{const rows=roles.filter(role=>test(role.toLowerCase()));return rows.length?<div key={label}><h3>{label}</h3><div className="tax-settings-table-wrap"><table className="tax-settings-table"><thead><tr><th>Tax component</th><th>Account code</th><th>Account name</th><th>Account type</th><th>Mapping status</th></tr></thead><tbody>{rows.map(role=>{const account=accounts.find(a=>a.id===profile?.mappings?.[role]);return <tr key={role}><td data-label="Tax component">{taxUiLabel(role)}</td><td data-label="Account code">{account?.code||'—'}</td><td data-label="Account name">{account?.name||'Not mapped'}</td><td data-label="Account type">{taxUiLabel(account?.account_type)}</td><td data-label="Mapping status"><TaxBadge value={account?'ACTIVE':'DRAFT'}>{account?'Mapped':'Needs attention'}</TaxBadge></td></tr>;})}</tbody></table></div></div>:null;})}<p className="tax-settings-muted">Settlement and refund accounts are selected in the existing return payment workflow. Activation validates account ownership and type.</p></section>;
}

export function TaxReturnsTable({records,periods,currency,renderActions}) {
 if(!records.length)return <TaxEmpty title="No tax returns yet">Select a saved tax period and prepare a draft when ready.</TaxEmpty>;
 return <div className="tax-settings-table-wrap"><table className="tax-settings-table"><thead><tr>{['Tax type','Period','Due date','Amount payable / refundable','Status','Last action','Actions'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{records.map(record=>{const period=periods.find(p=>p.id===record.period);return <tr key={record.id}><td data-label="Tax type"><strong>{taxUiLabel(record.kind)}</strong><small>Revision {record.revision}</small></td><td data-label="Period">{period?`${period.start_date} – ${period.end_date}`:'Not recorded'}</td><td data-label="Due date">{record.due_date||'Not recorded'}</td><td data-label="Amount payable / refundable">{record.snapshot?.net_payable??record.snapshot?.workpaper?.net_payable??'Not recorded'} {currency}</td><td data-label="Status"><TaxBadge value={record.status}/></td><td data-label="Last action">{record.updated_at||record.created_at||'Not recorded'}</td><td data-label="Actions"><details><summary>Return actions</summary><div className="tax-settings-return-actions">{renderActions(record)}</div></details></td></tr>;})}</tbody></table></div>;
}

export function TaxHistoryMetadata({event,versions,profiles,members=[]}) {
 const version=versions.find(v=>v.id===event.subject_id),profile=profiles.find(p=>p.id===event.subject_id),record=version||profile;
 if(!record)return null;
 const approver=record.approved_by||record.reviewed_by;
 return <TaxSummary items={[
 ['Related version',`Version ${version?.number||profile?.version}`],['Effective date',event.after?.effective_from||record.effective_from],['Source / reference',event.after?.source||record.source||'Not recorded'],['Reviewed / approved by',members.find(m=>m.id===approver)?.name||(approver?'Recorded approver':'Not recorded')],['Related version status',<TaxBadge value={record.display_status||record.status}/>],['Rule origin',version?taxUiLabel(version.provenance):'Organisation tax profile']
 ]}/>;
}
