// Explain an account balance with posted transactions and source-document drill-downs.

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, CalendarDays, Pencil, Scale, TriangleAlert, WalletCards } from "lucide-react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import AccountFormModal from "../../components/accounting/AccountFormModal";
import ReportExportMenu from "../../components/reports/ReportExportMenu";
import TablePagination from "../../components/common/TablePagination";
import { useTablePagination } from "../../hooks/useTablePagination";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import { reportService } from "../../services/reportService";
import { useAuth } from "../../store/AuthContext";
import { getJournalSourceRoute, journalSourceLabel } from "../../utils/journalSourceRoutes";
import "../../styles/accountDetails.css";

const today = () => new Date().toISOString().slice(0, 10);
const humanise = (value) => String(value || "—").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function AccountDetailsPage() {
  const { accountId } = useParams(); const auth = useAuth(); const [searchParams] = useSearchParams();
  const source = searchParams.get("source") || (searchParams.get("from") === "ledger" ? "general-ledger" : "chart-of-accounts");
  const isTrialBalance = source === "trial-balance"; const isProfitLoss = source === "profit-loss"; const isBalanceSheet = source === "balance-sheet"; const asOfDate = searchParams.get("as_of_date");
  const [account, setAccount] = useState(null); const [ledger, setLedger] = useState(null); const [years, setYears] = useState([]);
  const [filters, setFilters] = useState({ start_date: searchParams.get("start_date") || "", end_date: asOfDate || searchParams.get("end_date") || today() });
  const [state, setState] = useState({ loading: true, error: "" }); const [editing, setEditing] = useState(false);
  const load = useCallback(async () => { setState({ loading: true, error: "" }); try { const [metadata, rows, financialYears] = await Promise.all([accountingApiService.account(accountId), reportService.generalLedger({ account_id: accountId, ...filters, ...(isProfitLoss ? { report_type: "profit_loss" } : {}) }), accountingApiService.financialYears()]); setAccount(metadata); setLedger(rows[0] || null); setYears(financialYears); setState({ loading: false, error: "" }); } catch (error) { setState({ loading: false, error: normaliseApiError(error) }); } }, [accountId, filters, isProfitLoss]);
  useEffect(() => { const frame = window.requestAnimationFrame(() => void load()); return () => window.cancelAnimationFrame(frame); }, [load]);
  const transactions = useMemo(() => ledger?.transactions || [], [ledger]);
  const pagination = useTablePagination(transactions);
  const currency = account?.currency || auth.selectedOrganisation?.base_currency || "GBP";
  const money = (value) => new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(Number(value || 0));
  const balanceLabel = (debit, credit, side) => `${money(side === "credit" ? credit : debit)} ${side === "credit" ? "CR" : side === "debit" ? "DR" : ""}`.trim();
  const openingSide = ledger?.opening_balance_side;
  const sourceLabels = { "trial-balance": "Trial Balance", "profit-loss": "Profit & Loss", "balance-sheet": "Balance Sheet", "general-ledger": "General Ledger", "chart-of-accounts": "Chart of Accounts" };
  const reportAmount = isProfitLoss ? ledger?.profit_loss_amount : isBalanceSheet ? ledger?.balance_sheet_amount : null;
  const backQuery = new URLSearchParams({ ...(filters.start_date ? { start_date: filters.start_date } : {}), ...(filters.end_date && !isBalanceSheet && !isTrialBalance ? { end_date: filters.end_date } : {}), ...((isBalanceSheet || isTrialBalance) ? { as_of_date: asOfDate || filters.end_date } : {}) });
  const backPath = source === "profit-loss" ? `/accounting/profit-and-loss?${backQuery}` : source === "balance-sheet" ? `/accounting/balance-sheet?${backQuery}` : source === "trial-balance" ? `/accounting/trial-balance?${backQuery}` : source === "general-ledger" ? `/accounting/general-ledger?${backQuery}` : "/accounting/chart-of-accounts";
  const exportRows = transactions.map((row) => ({ account_code: account?.code, account_name: account?.name, organisation: auth.selectedOrganisation?.name, report_context: `${sourceLabels[source]} drill-down`, report_amount: reportAmount, period_start: filters.start_date || "All time", period_end: filters.end_date, opening_debit: ledger?.opening_debit, opening_credit: ledger?.opening_credit, closing_debit: ledger?.closing_debit, closing_credit: ledger?.closing_credit, date: row.date, journal: row.entry_number, reference: row.reference, description: row.description, debit: row.debit, credit: row.credit, running_debit: row.running_debit, running_credit: row.running_credit }));
  const setPreset = (preset) => { if (preset === "all") return setFilters({ start_date: "", end_date: today() }); if (preset === "month") { const now = new Date(); return setFilters({ start_date: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`, end_date: today() }); } const year = years.find((item) => item.start_date <= today() && item.end_date >= today()) || years.find((item) => item.status === "open"); if (year) setFilters({ start_date: year.start_date, end_date: year.end_date }); };
  if (state.loading && !account) return <div className="account-details-page"><section className="account-details-state"><span className="header-spinner"/><h1>Loading account</h1></section></div>;
  if (!account) return <div className="account-details-page"><section className="account-details-state"><TriangleAlert size={32}/><h1>Account unavailable</h1><p>{state.error || "This account was not found in the current organisation."}</p><button className="invoice-secondary-button" onClick={() => void load()}>Try again</button><Link to="/accounting/chart-of-accounts">Back to Chart of Accounts</Link></section></div>;
  return <div className="account-details-page">
    <header className="account-details-header"><div><Link className="journal-details-back" to={backPath}><ArrowLeft size={16}/>Back to {sourceLabels[source]}</Link><span className="journal-details-eyebrow">{sourceLabels[source]} drill-down</span><div className="account-details-title"><h1>{account.code} · {account.name}</h1><span className={`chart-account-status chart-account-status-${account.status}`}>{humanise(account.status)}</span>{account.is_system_account && <span className="chart-account-system-badge">System / Control Account</span>}</div><p>{humanise(account.account_type)} · {humanise(account.account_class)} · Normal balance: {humanise(ledger?.account?.normal_balance)}{isProfitLoss ? ` · ${filters.start_date || "Beginning"} – ${filters.end_date}` : (isTrialBalance || isBalanceSheet) ? ` · As at ${filters.end_date}` : ""}</p></div><div className="account-details-actions"><ReportExportMenu title={`${account.code} ${account.name} Ledger`} rows={exportRows} metadata={{ ...filters, opening_balance: ledger?.opening_balance, closing_balance: ledger?.balance, report_amount: reportAmount, source: sourceLabels[source] }}/>{auth.hasPermission("manage_accounts") && <button className="invoice-secondary-button" onClick={() => setEditing(true)}><Pencil size={16}/>Edit Account</button>}<Link className="page-primary-button" to={`/accounting/general-ledger?account_id=${account.id}&start_date=${filters.start_date}&end_date=${filters.end_date}`}>View General Ledger</Link></div></header>
    <section className="account-details-summary">{(isProfitLoss || isBalanceSheet) && <article className="account-report-amount"><WalletCards/><span>{isProfitLoss ? "Profit & Loss amount" : "Balance Sheet amount"}</span><strong>{money(reportAmount)}</strong><small>{isProfitLoss ? "Net movement for selected period" : `As at ${filters.end_date}`}</small></article>}<article><WalletCards/><span>{isProfitLoss ? "Net period movement" : isTrialBalance ? "Trial Balance balance" : "Closing balance"}</span><strong>{isProfitLoss ? money(ledger?.profit_loss_amount) : balanceLabel(ledger?.closing_debit, ledger?.closing_credit, ledger?.balance_side)}</strong><small>{isProfitLoss ? "Report sign convention" : `As at ${filters.end_date}`}</small></article><article><BookOpen/><span>Period debits</span><strong>{money(ledger?.period_debit)}</strong><small>Selected period</small></article><article><BookOpen/><span>Period credits</span><strong>{money(ledger?.period_credit)}</strong><small>Selected period</small></article>{!isProfitLoss && <article><Scale/><span>Period activity</span><strong>{balanceLabel(ledger?.period_debit_balance, ledger?.period_credit_balance, ledger?.period_balance_side)}</strong><small>Canonical debit/credit position</small></article>}<article><CalendarDays/><span>Opening balance</span><strong>{balanceLabel(ledger?.opening_debit, ledger?.opening_credit, openingSide)}</strong><small>Before selected start date</small></article></section>
    <section className="account-details-panel"><header><div><h2>Account information</h2><p>Classification and posting controls.</p></div></header><div className="account-details-info">{[["Account code",account.code],["Account name",account.name],["Description",account.description || "—"],["Account type",humanise(account.account_type)],["Account class",humanise(account.account_class)],["Cash flow category",humanise(account.cash_flow_category)],["Manual journals",account.allow_manual_journals ? "Allowed" : "Not allowed"],["System account",account.is_system_account ? "Yes" : "No"]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>
    {account.account_type === "asset" && account.account_class === "bank" && <section className="account-details-panel"><header><div><h2>Banking</h2><p>Operational banking profile for this ledger account.</p></div>{account.bank_account ? <Link className="page-primary-button" to="/banking/accounts">Open in Banking</Link> : <Link className="page-primary-button" to={`/banking/accounts?ledger_account_id=${account.id}`}>Set up in Banking</Link>}</header><div className="account-details-info"><div><span>Banking status</span><strong>{account.bank_account ? "Linked to Banking" : "Not linked to Banking"}</strong></div>{account.bank_account && <div><span>Bank account</span><strong>{account.bank_account.name}</strong></div>}</div></section>}
    <section className="account-details-panel"><header className="account-ledger-header"><div><h2>Account activity</h2><p>Posted journal lines from the authoritative General Ledger.</p></div><div className="account-period-presets"><button onClick={() => setPreset("all")}>All time</button><button onClick={() => setPreset("month")}>This month</button><button disabled={!years.length} onClick={() => setPreset("year")}>Financial year</button></div></header><div className="account-date-filter"><label>Start date<input type="date" value={filters.start_date} onChange={(event) => setFilters({ ...filters, start_date: event.target.value })}/></label><label>End date<input type="date" value={filters.end_date} onChange={(event) => setFilters({ ...filters, end_date: event.target.value })}/></label>{state.loading && <span>Refreshing…</span>}</div>{state.error ? <div className="invoice-form-alert"><span>{state.error}</span><button className="invoice-secondary-button" onClick={() => void load()}>Try again</button></div> : transactions.length ? <><div className="account-ledger-table-wrap"><table className="account-ledger-table"><thead><tr><th>Date</th><th>Journal</th><th>Reference</th><th>Description</th><th>Source</th><th className="report-number-column">Debit</th><th className="report-number-column">Credit</th><th className="report-number-column">Running balance</th></tr></thead><tbody>{pagination.pageRows.map((row, index) => { const sourceRoute = getJournalSourceRoute(row.source_type, row.source_id); return <tr key={`${row.journal_id}-${index}`}><td>{row.date}</td><td><Link to={`/accounting/journals/${row.journal_id}`}>{row.entry_number}</Link></td><td>{row.reference || "—"}</td><td>{row.description || "—"}</td><td>{sourceRoute ? <Link to={sourceRoute}>{journalSourceLabel(row.source_type)}</Link> : journalSourceLabel(row.source_type)}</td><td className="report-number-column">{Number(row.debit) ? money(row.debit) : "—"}</td><td className="report-number-column">{Number(row.credit) ? money(row.credit) : "—"}</td><td className="report-number-column"><strong>{money(row.running_balance)}</strong></td></tr>; })}</tbody></table></div><TablePagination {...pagination}/></> : <div className="chart-accounts-empty"><BookOpen size={30}/><h2>No transactions</h2><p>No transactions for this account in the selected period.</p></div>}</section>
    {editing && <AccountFormModal isOpen account={account} currency={currency} onClose={() => setEditing(false)} onSaved={async () => { setEditing(false); await load(); }}/>} 
  </div>;
}
