// Present supported group mappings, eliminations, and consolidated statement results.

import { useCallback, useEffect, useMemo, useState } from "react";
import PageHeader from "../../components/layout/PageHeader";
import ReportExportMenu from "../../components/reports/ReportExportMenu";
import { api } from "../../services/api";
import { normaliseApiError } from "../../services/apiError";
import { consolidationApiService as service } from "../../services/consolidationApiService";
import "../../styles/chartOfAccounts.css";

const today = () => new Date().toISOString().slice(0, 10);
const emptyLine = () => ({ consolidation_account: "", debit: "", credit: "", description: "" });
const rows = (value) => Array.isArray(value) ? value : value?.results || [];

export default function ConsolidationPage() {
  const [data, setData] = useState({ groups: [], members: [], accounts: [], mappings: [], periods: [], eliminations: [], organisations: [], currencies: [] });
  const [selectedGroup, setSelectedGroup] = useState("");
  const [unmapped, setUnmapped] = useState([]);
  const [report, setReport] = useState(null);
  const [reportType, setReportType] = useState("trialBalance");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [groupForm, setGroupForm] = useState({ name: "", reporting_currency: "GBP", status: "active" });
  const [memberForm, setMemberForm] = useState({ organisation: "", ownership_percentage: "100", consolidation_method: "full", effective_from: today(), effective_to: "", status: "active" });
  const [accountForm, setAccountForm] = useState({ code: "", name: "", account_type: "asset", account_class: "current_asset", display_order: 0, status: "active" });
  const [mappingForm, setMappingForm] = useState({ organisation: "", source_account: "", consolidation_account: "", effective_from: today(), effective_to: "" });
  const [eliminationForm, setEliminationForm] = useState({ period: "", entry_number: "", date: today(), description: "", reference: "", lines: [emptyLine(), emptyLine()] });

  const load = useCallback(async () => {
    try {
      const result = await Promise.all([service.groups(), service.members(), service.accounts(), service.mappings(), service.periods(), service.eliminations(), api.get("organisations/"), api.get("currencies/")]);
      const next = { groups: rows(result[0]), members: rows(result[1]), accounts: rows(result[2]), mappings: rows(result[3]), periods: rows(result[4]), eliminations: rows(result[5]), organisations: rows(result[6]), currencies: rows(result[7]) };
      setData(next); setSelectedGroup((current) => current || next.groups[0]?.id || ""); setError("");
    } catch (requestError) { setError(normaliseApiError(requestError)); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const frame = requestAnimationFrame(() => void load()); return () => cancelAnimationFrame(frame); }, [load]);
  useEffect(() => { let active = true; const frame = requestAnimationFrame(() => { if (!selectedGroup) { setUnmapped([]); return; } service.unmapped(selectedGroup).then((items) => { if (active) setUnmapped(rows(items)); }).catch((requestError) => { if (active) setError(normaliseApiError(requestError)); }); }); return () => { active = false; cancelAnimationFrame(frame); }; }, [selectedGroup]);
  const current = useMemo(() => data.groups.find((item) => item.id === selectedGroup), [data.groups, selectedGroup]);
  const scoped = (items) => items.filter((item) => item.group === selectedGroup);
  const submit = async (action, reset) => { try { await action(); if (reset) reset(); await load(); } catch (requestError) { setError(normaliseApiError(requestError)); } };
  const clean = (value) => Object.fromEntries(Object.entries(value).filter(([, field]) => field !== ""));
  const lineTotal = (key) => eliminationForm.lines.reduce((sum, line) => sum + Number(line[key] || 0), 0);
  const updateLine = (index, key, value) => setEliminationForm((form) => ({ ...form, lines: form.lines.map((line, lineIndex) => lineIndex === index ? { ...line, [key]: value } : line) }));
  const reportPeriod = data.periods.find((item) => item.id === eliminationForm.period);
  const reportRows = Array.isArray(report) ? report : report ? Object.entries(report).flatMap(([section, value]) => Array.isArray(value) ? value.map((row) => ({ section, ...row })) : []) : [];

  return <div className="products-page"><PageHeader eyebrow="Group reporting" title="Consolidation workbench" description="Manage 100%-owned FULL consolidations without changing subsidiary ledgers." action={report ? <ReportExportMenu title={`Consolidated ${reportType}`} rows={reportRows} metadata={{ period: reportPeriod?.end_date, currency: current?.reporting_currency }} /> : null} />
    {error && <div className="invoice-form-alert">{error}</div>}{loading ? <section className="invoice-form-card">Loading consolidation data…</section> : <>
      <section className="invoice-form-card"><h2>Consolidation groups</h2><form className="invoice-form-grid" onSubmit={(event) => { event.preventDefault(); void submit(() => service.createGroup(groupForm), () => setGroupForm({ ...groupForm, name: "" })); }}><label>Name<input required value={groupForm.name} onChange={(event) => setGroupForm({ ...groupForm, name: event.target.value })} /></label><label>Reporting currency<select value={groupForm.reporting_currency} onChange={(event) => setGroupForm({ ...groupForm, reporting_currency: event.target.value })}>{data.currencies.map((item) => <option key={item.code} value={item.code}>{item.code} — {item.name}</option>)}</select></label><button className="invoice-primary-button">Create group</button></form><label>Active group<select value={selectedGroup} onChange={(event) => setSelectedGroup(event.target.value)}><option value="">Select group</option>{data.groups.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.reporting_currency}</option>)}</select></label></section>
      {current && <>
        <section className="invoice-form-card"><h2>Members</h2><p>Full consolidation currently supports 100%-owned subsidiaries only.</p><form className="invoice-form-grid" onSubmit={(event) => { event.preventDefault(); if (Number(memberForm.ownership_percentage) !== 100) { setError("Full consolidation currently supports 100%-owned subsidiaries only."); return; } void submit(() => service.createMember(clean({ ...memberForm, group: selectedGroup }))); }}><label>Organisation<select required value={memberForm.organisation} onChange={(event) => setMemberForm({ ...memberForm, organisation: event.target.value })}><option value="">Select organisation</option>{data.organisations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Ownership %<input type="number" min="100" max="100" required value={memberForm.ownership_percentage} onChange={(event) => setMemberForm({ ...memberForm, ownership_percentage: event.target.value })} /></label><label>Method<select value="full" disabled><option value="full">FULL</option></select></label><label>Effective from<input type="date" required value={memberForm.effective_from} onChange={(event) => setMemberForm({ ...memberForm, effective_from: event.target.value })} /></label><label>Effective to<input type="date" value={memberForm.effective_to} onChange={(event) => setMemberForm({ ...memberForm, effective_to: event.target.value })} /></label><button className="invoice-primary-button">Add member</button></form>{scoped(data.members).map((item) => <p key={item.id}>{data.organisations.find((org) => org.id === item.organisation)?.name || item.organisation} — {item.ownership_percentage}% FULL — {item.status} <button onClick={() => void submit(() => service.updateMember(item.id, { status: item.status === "active" ? "inactive" : "active" }))}>{item.status === "active" ? "Deactivate" : "Activate"}</button> <button onClick={() => void submit(() => service.removeMember(item.id))}>Remove</button></p>)}</section>
        <section className="invoice-form-card"><h2>Group accounts</h2><form className="invoice-form-grid" onSubmit={(event) => { event.preventDefault(); void submit(() => service.createAccount({ ...accountForm, group: selectedGroup })); }}><label>Code<input required value={accountForm.code} onChange={(event) => setAccountForm({ ...accountForm, code: event.target.value })} /></label><label>Name<input required value={accountForm.name} onChange={(event) => setAccountForm({ ...accountForm, name: event.target.value })} /></label><label>Type<select value={accountForm.account_type} onChange={(event) => setAccountForm({ ...accountForm, account_type: event.target.value })}>{["asset", "liability", "equity", "revenue", "expense"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Class<input required value={accountForm.account_class} onChange={(event) => setAccountForm({ ...accountForm, account_class: event.target.value })} /></label><label>Display order<input type="number" value={accountForm.display_order} onChange={(event) => setAccountForm({ ...accountForm, display_order: Number(event.target.value) })} /></label><button className="invoice-primary-button">Create account</button></form><div className="chart-accounts-table-wrapper"><table className="chart-accounts-table"><thead><tr><th>Code</th><th>Name</th><th>Type / class</th><th>Status</th></tr></thead><tbody>{scoped(data.accounts).map((item) => <tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td>{item.account_type} / {item.account_class}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>
        <section className="invoice-form-card"><h2>Account mappings</h2><form className="invoice-form-grid" onSubmit={(event) => { event.preventDefault(); void submit(() => service.createMapping(clean({ ...mappingForm, group: selectedGroup }))); }}><label>Unmapped source account<select required value={mappingForm.source_account} onChange={(event) => { const account = unmapped.find((item) => item.id === event.target.value); setMappingForm({ ...mappingForm, source_account: event.target.value, organisation: account?.organisation_id || "" }); }}><option value="">Select account</option>{unmapped.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name} ({item.organisation_id})</option>)}</select></label><label>Consolidation account<select required value={mappingForm.consolidation_account} onChange={(event) => setMappingForm({ ...mappingForm, consolidation_account: event.target.value })}><option value="">Select group account</option>{scoped(data.accounts).map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></label><label>Effective from<input required type="date" value={mappingForm.effective_from} onChange={(event) => setMappingForm({ ...mappingForm, effective_from: event.target.value })} /></label><label>Effective to<input type="date" value={mappingForm.effective_to} onChange={(event) => setMappingForm({ ...mappingForm, effective_to: event.target.value })} /></label><button className="invoice-primary-button">Map account</button></form><p><strong>{unmapped.length}</strong> unmapped active account(s). Unmapped balances are never silently ignored during preparation.</p>{scoped(data.mappings).map((item) => <p key={item.id}>{item.source_account} → {item.consolidation_account} ({item.effective_from}) <button onClick={() => void submit(() => service.removeMapping(item.id))}>Remove</button></p>)}</section>
        <section className="invoice-form-card"><h2>Elimination journals</h2><form onSubmit={(event) => { event.preventDefault(); if (eliminationForm.lines.length < 2 || lineTotal("debit") !== lineTotal("credit")) { setError("Elimination requires at least two lines and equal debit and credit totals."); return; } void submit(() => service.createElimination({ ...eliminationForm, group: selectedGroup })); }}><div className="invoice-form-grid"><label>Period<select required value={eliminationForm.period} onChange={(event) => setEliminationForm({ ...eliminationForm, period: event.target.value })}><option value="">Select period</option>{scoped(data.periods).map((item) => <option key={item.id} value={item.id}>{item.start_date} – {item.end_date}</option>)}</select></label><label>Entry number<input required value={eliminationForm.entry_number} onChange={(event) => setEliminationForm({ ...eliminationForm, entry_number: event.target.value })} /></label><label>Date<input required type="date" value={eliminationForm.date} onChange={(event) => setEliminationForm({ ...eliminationForm, date: event.target.value })} /></label><label>Description<input required value={eliminationForm.description} onChange={(event) => setEliminationForm({ ...eliminationForm, description: event.target.value })} /></label></div>{eliminationForm.lines.map((line, index) => <div className="invoice-form-grid" key={index}><select required value={line.consolidation_account} onChange={(event) => updateLine(index, "consolidation_account", event.target.value)}><option value="">Group account</option>{scoped(data.accounts).map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Debit" value={line.debit} onChange={(event) => updateLine(index, "debit", event.target.value)} /><input type="number" min="0" step="0.01" placeholder="Credit" value={line.credit} onChange={(event) => updateLine(index, "credit", event.target.value)} /><button type="button" disabled={eliminationForm.lines.length <= 2} onClick={() => setEliminationForm({ ...eliminationForm, lines: eliminationForm.lines.filter((_, lineIndex) => lineIndex !== index) })}>Remove</button></div>)}<p>Debit {lineTotal("debit").toFixed(2)} · Credit {lineTotal("credit").toFixed(2)}</p><button type="button" onClick={() => setEliminationForm({ ...eliminationForm, lines: [...eliminationForm.lines, emptyLine()] })}>Add line</button> <button className="invoice-primary-button">Save draft</button></form>{scoped(data.eliminations).map((item) => <p key={item.id}>{item.entry_number} — {item.status} — {item.lines?.length || 0} lines {item.status === "draft" && <button onClick={() => void submit(() => service.postElimination(item.id))}>Post</button>} {item.status === "posted" && <button onClick={() => void submit(() => service.reverseElimination(item.id, today()))}>Reverse</button>}</p>)}</section>
        <section className="invoice-form-card"><h2>Consolidated reports</h2><p>Group: <strong>{current.name}</strong> · Reporting currency: <strong>{current.reporting_currency}</strong> · Period status: <strong>{reportPeriod?.status || "select a period"}</strong></p><select value={eliminationForm.period} onChange={(event) => setEliminationForm({ ...eliminationForm, period: event.target.value })}><option value="">Select period</option>{scoped(data.periods).map((item) => <option key={item.id} value={item.id}>{item.start_date} – {item.end_date}</option>)}</select> <select value={reportType} onChange={(event) => setReportType(event.target.value)}><option value="trialBalance">Trial Balance</option><option value="profitLoss">Profit &amp; Loss</option><option value="balanceSheet">Balance Sheet</option></select> <button disabled={!eliminationForm.period} onClick={() => service[reportType](eliminationForm.period).then(setReport).catch((requestError) => setError(normaliseApiError(requestError)))}>Run report</button>{report && <pre>{JSON.stringify(report, null, 2)}</pre>}<p>Consolidated Cash Flow and CTA are intentionally unavailable in this milestone.</p></section>
      </>}
    </>}</div>;
}
