import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Calculator, FilterX, Plus, Printer, Search, TriangleAlert } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import PageHeader from "../../components/layout/PageHeader";
import ReportExportMenu from "../../components/reports/ReportExportMenu";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import { useAuth } from "../../store/AuthContext";
import { formatCurrency } from "../../utils/currency";
import { formatDisplayDate, formatTimestamp } from "../../utils/dateUtils";
import { generalJournalExportRows, journalTotals, orderedJournalLines } from "../../utils/generalJournal";
import { journalSourceLabel } from "../../utils/journalSourceRoutes";
import "../../styles/journals.css";

const humanise = (value) => String(value || "—").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const sameMoney = (left, right) => Math.abs(left - right) < 0.005;

function JournalGroup({ journal, money }) {
  const lines = orderedJournalLines(journal.lines);
  const totals = journalTotals([journal]); const balanced = sameMoney(totals.debit, totals.credit);
  const reversal = journal.reversal_of || journal.reversal_entry;
  return <tbody className="general-journal-group">
    <tr className="general-journal-identity"><td colSpan="5"><div><Link to={`/accounting/journals/${journal.id}`}>{journal.entry_number}</Link><span className={`journal-status journal-status-${journal.status}`}>{humanise(journal.status)}</span>{journal.reversal_of && <span className="journal-reversal-label">Reversal journal</span>}{journal.reversal_entry && <span className="journal-reversal-label">Reversed</span>}</div><small>Reference: {journal.reference || "—"} · Source: {journalSourceLabel(journal.source_type)} · Created by: {journal.created_by?.name || "—"}{journal.posted_by?.name ? ` · Posted by: ${journal.posted_by.name}` : ""}{reversal ? ` · Linked journal: ${reversal.entry_number}` : ""}</small></td></tr>
    {lines.map((line, index) => { const debit = Number(line.debit || 0); const credit = Number(line.credit || 0); const malformed = debit !== 0 && credit !== 0; return <tr className={`${credit ? "general-journal-credit" : "general-journal-debit"}${malformed ? " is-malformed" : ""}`} key={line.id || index}><td>{index === 0 ? formatDisplayDate(journal.date) : ""}</td><td><Link to={`/accounting/general-ledger?account_id=${line.account?.id}`}>{line.account?.name || "Unknown account"}</Link>{line.description && line.description !== journal.description && <small>{line.description}</small>}{malformed && <em><TriangleAlert size={12}/>Both debit and credit are populated</em>}</td><td>{line.account?.code || "—"}</td><td className="general-journal-amount">{debit ? money(debit) : "—"}</td><td className="general-journal-amount">{credit ? money(credit) : "—"}</td></tr>; })}
    <tr className="general-journal-narration"><td/><td colSpan="4"><strong>Narration:</strong> {journal.description || "No narration provided."}</td></tr>
    <tr className={`general-journal-subtotal ${balanced ? "is-balanced" : "is-unbalanced"}`}><td/><td colSpan="2">{balanced ? "Journal balanced" : "Journal out of balance"}</td><td className="general-journal-amount">{money(totals.debit)}</td><td className="general-journal-amount">{money(totals.credit)}</td></tr>
  </tbody>;
}

function RegisterTable({ journals, money, className = "" }) {
  return <div className={`general-journal-table-wrap ${className}`}><table className="general-journal-table"><caption className="visually-hidden">General Journal register</caption><thead><tr><th>Date</th><th>Particulars</th><th>Post Ref</th><th>Debit</th><th>Credit</th></tr></thead>{journals.map((journal) => <JournalGroup journal={journal} money={money} key={journal.id}/>)}</table></div>;
}

function JournalPagination({ page, pageSize, total, loading, onPage, onPageSize }) {
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const first = total ? (page - 1) * pageSize + 1 : 0; const last = Math.min(page * pageSize, total);
  const start = Math.max(1, page - 2); const end = Math.min(totalPages, start + 4);
  const pages = Array.from({ length: end - start + 1 }, (_, index) => start + index);
  return <nav className="general-journal-pagination" aria-label="General Journal pagination" aria-busy={loading}>
    <span>Showing {first}–{last} of {total} journals</span><label>Journals per page<select aria-label="Journals per page" value={pageSize} disabled={loading} onChange={(event) => onPageSize(Number(event.target.value))}>{[10,25,50,100].map((value) => <option value={value} key={value}>{value}</option>)}</select></label>
    <div><button type="button" aria-label="Previous page" disabled={loading || page === 1} onClick={() => onPage(page - 1)}>Previous</button>{start > 1 && <span>…</span>}{pages.map((value) => <button type="button" aria-label={`Page ${value}`} aria-current={value === page ? "page" : undefined} className={value === page ? "is-current" : ""} disabled={loading} onClick={() => onPage(value)} key={value}>{value}</button>)}{end < totalPages && <span>…</span>}<button type="button" aria-label="Next page" disabled={loading || page === totalPages} onClick={() => onPage(page + 1)}>Next</button></div><strong>Page {page} of {totalPages}</strong>
  </nav>;
}

export default function GeneralJournalPage() {
  const auth = useAuth(); const organisation = auth.selectedOrganisation;
  const [searchParams, setSearchParams] = useSearchParams(); const sequence = useRef(0);
  const allowedSizes = [10,25,50,100]; const requestedSize = Number(searchParams.get("page_size")); const pageSize = allowedSizes.includes(requestedSize) ? requestedSize : 25; const page = Math.max(1, Number(searchParams.get("page")) || 1);
  const filters = { start: searchParams.get("start_date") || "", end: searchParams.get("end_date") || "", status: searchParams.get("status") || "", source: searchParams.get("source_type") || "", account: searchParams.get("account_id") || "", search: searchParams.get("search") || "" };
  const [journals, setJournals] = useState([]); const [printJournals, setPrintJournals] = useState([]); const [state, setState] = useState({ loading: true, preparing: false, error: "" });
  const [meta, setMeta] = useState({ count: 0, totals: { debit: 0, credit: 0 }, ledger_totals: { debit: 0, credit: 0 }, facets: { sources: [], accounts: [] } });
  const requestFilters = useMemo(() => ({ ...(filters.start && { start_date: filters.start }), ...(filters.end && { end_date: filters.end }), ...(filters.status && { status: filters.status }), ...(filters.source && { source_type: filters.source }), ...(filters.account && { account_id: filters.account }), ...(filters.search && { search: filters.search }) }), [filters.account, filters.end, filters.search, filters.source, filters.start, filters.status]);
  const load = useCallback(async () => { const request = ++sequence.current; setState((current) => ({ ...current, loading: true, error: "" })); try { const result = await accountingApiService.journalRegister({ ...requestFilters, page, page_size: pageSize }); if (request !== sequence.current) return; setJournals(result.results || []); setMeta({ count: result.count || 0, totals: result.totals || { debit: 0, credit: 0 }, ledger_totals: result.ledger_totals || { debit: 0, credit: 0 }, facets: result.facets || { sources: [], accounts: [] } }); setState((current) => ({ ...current, loading: false, error: "" })); } catch (error) { if (request !== sequence.current) return; const beyond = error.status === 404 && page > 1; if (beyond) { const next = new URLSearchParams(searchParams); next.set("page", "1"); setSearchParams(next, { replace: true }); return; } setState((current) => ({ ...current, loading: false, error: normaliseApiError(error) })); } }, [page, pageSize, requestFilters, searchParams, setSearchParams]);
  useEffect(() => { const frame = requestAnimationFrame(() => void load()); return () => cancelAnimationFrame(frame); }, [load, organisation?.id]);
  const sources = meta.facets.sources; const accounts = meta.facets.accounts;
  const displayed = { debit: Number(meta.totals.debit || 0), credit: Number(meta.totals.credit || 0) }; const ledger = { debit: Number(meta.ledger_totals.debit || 0), credit: Number(meta.ledger_totals.credit || 0) };
  const difference = displayed.debit - displayed.credit; const currency = organisation?.base_currency || "GBP"; const money = (value) => formatCurrency(value, currency);
  const period = filters.start || filters.end ? `${filters.start ? formatDisplayDate(filters.start) : "Beginning"} – ${filters.end ? formatDisplayDate(filters.end) : "Current date"}` : "All dates";
  const activeFilters = Object.values(filters).some(Boolean);
  const update = (key, value) => { const next = new URLSearchParams(searchParams); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.set("page", "1"); if (!next.has("page_size")) next.set("page_size", String(pageSize)); setSearchParams(next); };
  const clear = () => setSearchParams(new URLSearchParams({ page: "1", page_size: String(pageSize) }));
  const fetchAll = useCallback(async () => { const first = await accountingApiService.journalRegister({ ...requestFilters, page: 1, page_size: 100 }); if ((first.count || 0) > 10000) throw new Error("This filtered register is too large for browser print or export. Narrow the filters and try again."); const all = [...(first.results || [])]; const pages = Math.ceil((first.count || 0) / 100); for (let nextPage = 2; nextPage <= pages; nextPage += 1) { const batch = await accountingApiService.journalRegister({ ...requestFilters, page: nextPage, page_size: 100 }); all.push(...(batch.results || [])); } return all; }, [requestFilters]);
  const exportAll = useCallback(async () => generalJournalExportRows(await fetchAll()), [fetchAll]);
  const print = async () => { if (!meta.count || state.loading || state.preparing) return; setState((current) => ({ ...current, preparing: true, error: "" })); try { const all = await fetchAll(); setPrintJournals(all); requestAnimationFrame(() => requestAnimationFrame(() => { window.addEventListener("afterprint", () => setPrintJournals([]), { once: true }); window.print(); setState((current) => ({ ...current, preparing: false })); })); } catch (error) { setState((current) => ({ ...current, preparing: false, error: normaliseApiError(error) })); } };
  return <div className="journals-page general-journal-page">
    <PageHeader eyebrow="Accounting · Journal register" title="General Journal" description="A chronological register of journal debits, credits, narration and audit identity." action={<div className="general-journal-actions"><button className="invoice-secondary-button" disabled={state.loading || state.preparing || !meta.count} onClick={() => void print()}><Printer size={16}/>{state.preparing ? "Preparing…" : "Print"}</button>{auth.hasPermission("export_reports") && <ReportExportMenu title="General Journal" loadRows={exportAll} metadata={{ organisation: organisation?.name, start_date: filters.start, end_date: filters.end, currency, filters: [filters.status, filters.source, filters.account].filter(Boolean).join(", ") || "All" }} disabled={state.loading || !meta.count}/>} {auth.hasPermission("create_journal") && <Link className="page-primary-button" to="/accounting/journals/new"><Plus size={16}/>New Journal</Link>}</div>}/>
    <header className="general-journal-report-header"><div><strong>{organisation?.name || "Ledgify"}</strong><h2>General Journal</h2><p>{period}</p></div><dl><div><dt>Currency</dt><dd>{currency}</dd></div><div><dt>Generated</dt><dd>{formatTimestamp(new Date().toISOString(), { timeZone: organisation?.timezone || "UTC" })}</dd></div><div><dt>Filters</dt><dd>{activeFilters ? "Selected filters applied" : "All journals"}</dd></div></dl><span className="general-journal-page-number">Page</span></header>
    <section className="general-journal-filters" aria-label="General Journal filters"><label><span>From</span><input type="date" value={filters.start} onChange={(event) => update("start_date",event.target.value)}/></label><label><span>To</span><input type="date" min={filters.start} value={filters.end} onChange={(event) => update("end_date",event.target.value)}/></label><label><span>Status</span><select value={filters.status} onChange={(event) => update("status",event.target.value)}><option value="">All statuses</option>{["draft","awaiting_approval","approved","posted","reversed","rejected","void"].map((value) => <option value={value} key={value}>{humanise(value)}</option>)}</select></label><label><span>Source</span><select value={filters.source} onChange={(event) => update("source_type",event.target.value)}><option value="">All sources</option>{sources.map((value) => <option value={value} key={value}>{journalSourceLabel(value)}</option>)}</select></label><label><span>Account</span><select value={filters.account} onChange={(event) => update("account_id",event.target.value)}><option value="">All accounts</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.code} · {account.name}</option>)}</select></label><label className="general-journal-search"><span className="visually-hidden">Search</span><Search size={16}/><input value={filters.search} onChange={(event) => update("search",event.target.value)} placeholder="Number, reference, narration or account"/></label>{activeFilters && <button className="general-journal-clear" onClick={clear}><FilterX size={15}/>Clear</button>}</section>
    {state.error && <div className="invoice-form-alert" role="alert">{state.error}<button onClick={() => void load()}>Try again</button></div>}
    {state.loading && !journals.length ? <section className="invoice-form-card">Loading the General Journal…</section> : journals.length ? <><div className={state.loading ? "general-journal-page-loading" : ""}><RegisterTable journals={journals} money={money}/></div><RegisterTable journals={printJournals} money={money} className="general-journal-print-register"/><JournalPagination page={page} pageSize={pageSize} total={meta.count} loading={state.loading} onPage={(value) => update("page",String(value))} onPageSize={(value) => { const next = new URLSearchParams(searchParams); next.set("page","1"); next.set("page_size",String(value)); setSearchParams(next); }}/><section className="general-journal-totals"><div><span>Full filtered debit</span><strong>{money(displayed.debit)}</strong></div><div><span>Full filtered credit</span><strong>{money(displayed.credit)}</strong></div><div className={sameMoney(displayed.debit,displayed.credit) ? "is-balanced" : "is-unbalanced"}><span>Difference</span><strong>{money(difference)}</strong><small>{sameMoney(displayed.debit,displayed.credit) ? "Balanced" : "Out of balance"}</small></div><div><span>Ledger-effective debit / credit</span><strong>{money(ledger.debit)} / {money(ledger.credit)}</strong><small>Posted and reversed journals</small></div></section></> : !state.loading && <section className="chart-accounts-empty"><Calculator size={30}/><h2>No journals match these filters</h2><p>Adjust or clear the filters to view journal entries.</p>{activeFilters && <button className="invoice-secondary-button" onClick={clear}>Clear filters</button>}</section>}
  </div>;
}
