// Show an auditable journal and allow posting or reversal only when permissions permit.

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, FileText, Link2, Printer, RotateCcw, Send, Scale, TriangleAlert, UserRound } from "lucide-react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import Modal from "../../components/common/Modal";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import { getJournalSourceRoute, journalSourceLabel } from "../../utils/journalSourceRoutes";
import { useAuth } from "../../store/AuthContext";
import "../../styles/journalDetails.css";

const humanise = (value) => String(value || "—").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const dateTime = (value) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const dateOnly = (value) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) : "—";

export default function JournalDetailsPage() {
  const { journalId } = useParams(); const [searchParams] = useSearchParams(); const auth = useAuth(); const [journal, setJournal] = useState(null); const [state, setState] = useState({ loading: true, error: "" }); const [action, setAction] = useState(""); const [actionError, setActionError] = useState(""); const [printError, setPrintError] = useState("");
  const load = useCallback(async () => { setState({ loading: true, error: "" }); try { setJournal(await accountingApiService.journal(journalId)); setState({ loading: false, error: "" }); } catch (error) { setJournal(null); setState({ loading: false, error: normaliseApiError(error) }); } }, [journalId]);
  useEffect(() => { const frame = window.requestAnimationFrame(() => void load()); return () => window.cancelAnimationFrame(frame); }, [load]);
  const totals = useMemo(() => (journal?.lines || []).reduce((sum, line) => ({ debit: sum.debit + Number(line.debit || 0), credit: sum.credit + Number(line.credit || 0) }), { debit: 0, credit: 0 }), [journal]);
  const difference = totals.debit - totals.credit; const balanced = Math.abs(difference) < 0.005;
  const currency = journal?.organisation?.base_currency || journal?.transaction_currency || "GBP";
  const money = (value) => new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(Number(value || 0));
  const printJournal = () => { if (!journal?.lines?.length) { setPrintError("This journal has no lines to print."); return; } setPrintError(""); window.requestAnimationFrame(() => window.print()); };
  const mutate = async () => { setActionError(""); try { const result = action === "post" ? await accountingApiService.postJournal(journal.id) : await accountingApiService.reverseJournal(journal.id, { reversal_date: new Date().toISOString().slice(0, 10) }); setAction(""); if (action === "reverse") window.location.assign(`/accounting/journals/${result.id}`); else setJournal(result); } catch (error) { setActionError(normaliseApiError(error)); setAction(""); } };
  if (state.loading) return <div className="journal-details-page"><section className="journal-details-not-found"><span className="header-spinner"/><h1>Loading journal entry</h1><p>Retrieving the accounting record and its lines.</p></section></div>;
  if (!journal) return <div className="journal-details-page"><section className="journal-details-not-found"><div className="journal-details-not-found-icon"><TriangleAlert/></div><h1>Journal entry unavailable</h1><p>{state.error || "The journal could not be found in this organisation."}</p><button className="invoice-secondary-button" onClick={() => void load()}>Try again</button><br/><Link to="/accounting/journals"><ArrowLeft size={16}/>Back to journals</Link></section></div>;
  const sourceRoute = getJournalSourceRoute(journal.source_type, journal.source_id);
  return <div className="journal-details-page">
    <header className="journal-details-header"><div><Link className="journal-details-back" to="/accounting/journals"><ArrowLeft size={16}/>Back to journals</Link><span className="journal-details-eyebrow">Journal Entry</span><div className="journal-details-title-row"><div><h1>{journal.entry_number}</h1><p>{journal.description || "No journal description was provided."}</p></div><span className={`journal-details-status ${journal.status}`}>{humanise(journal.status)}</span></div></div><div className="journal-details-header-actions">{journal.status === "draft" && auth.hasPermission("post_journal") && <button type="button" className="page-primary-button" onClick={() => setAction("post")}><Send size={17}/>Post Journal</button>}{journal.status === "posted" && !journal.reversal_entry && auth.hasPermission("reverse_journal") && <button type="button" className="invoice-secondary-button" onClick={() => setAction("reverse")}><RotateCcw size={17}/>Reverse Journal</button>}<button type="button" className="journal-details-export-button" disabled={!journal.lines?.length} onClick={printJournal}><Printer size={17}/>Print</button></div></header>
    {searchParams.get("created") && <div className="chart-accounts-success" role="status" aria-live="polite">Journal {searchParams.get("created") === "posted" ? "posted" : "draft saved"} successfully.</div>}
    {actionError && <div className="invoice-form-alert" role="alert">{actionError}</div>}
    {printError && <div className="invoice-form-alert journal-print-error" role="alert">{printError}</div>}
    <div className="journal-print-meta">Generated {dateTime(new Date().toISOString())} · {journal.organisation?.name || "Ledgify"} · {currency}</div>
    <section className="journal-details-summary-grid"><article className="journal-details-summary-card"><span className="journal-details-summary-icon"><CalendarDays size={20}/></span><div><span>Journal date</span><strong>{dateOnly(journal.date)}</strong><small>{journal.reference || "No reference"}</small></div></article><article className="journal-details-summary-card"><span className="journal-details-summary-icon"><FileText size={20}/></span><div><span>Source</span><strong>{journalSourceLabel(journal.source_type)}</strong><small>{sourceRoute ? <Link to={sourceRoute}>View source document</Link> : "No supported source route"}</small></div></article><article className="journal-details-summary-card"><span className="journal-details-summary-icon"><Scale size={20}/></span><div><span>Total value</span><strong>{money(totals.debit)}</strong><small>{journal.lines.length} journal lines</small></div></article><article className={`journal-details-summary-card ${balanced ? "is-balanced" : "is-unbalanced"}`}><span className="journal-details-summary-icon">{balanced ? <CheckCircle2 size={20}/> : <TriangleAlert size={20}/>}</span><div><span>Balance check</span><strong>{balanced ? "Balanced" : money(difference)}</strong><small>Debit and credit difference</small></div></article></section>
    {!balanced && <div className="invoice-form-alert" role="alert"><TriangleAlert size={18}/>This journal is out of balance by {money(difference)}. Values are displayed exactly as stored.</div>}
    {(journal.reversal_entry || journal.reversal_of) && <section className={`journal-details-reversal-panel ${journal.reversal_of ? "is-reversal-entry" : ""}`}><span className="journal-details-reversal-icon"><Link2 size={20}/></span><div className="journal-details-reversal-content"><h2>{journal.reversal_of ? "Reversal journal" : "Journal reversed"}</h2><p>{journal.reversal_of ? "This entry reverses an earlier journal." : "This journal has a linked reversal entry."}</p>{[journal.reversal_of, journal.reversal_entry].filter(Boolean).map((related) => <Link className="journal-details-original-link" key={related.id} to={`/accounting/journals/${related.id}`}>{related.entry_number} · {dateOnly(related.date)}</Link>)}</div></section>}
    <section className="journal-details-content-grid"><article className="journal-details-panel"><header className="journal-details-panel-header"><h2>Journal information</h2><p>Source and transaction identity.</p></header><div className="journal-details-information-list"><div><span>Journal number</span><strong>{journal.entry_number}</strong></div><div><span>Reference</span><strong>{journal.reference || "—"}</strong></div><div><span>Source type</span><strong>{journalSourceLabel(journal.source_type)}</strong></div><div><span>Organisation</span><strong>{journal.organisation?.name || "—"}</strong></div>{journal.transaction_currency && <div><span>Transaction currency</span><strong>{journal.transaction_currency}</strong></div>}{journal.exchange_rate && <div><span>Exchange rate</span><strong>{journal.exchange_rate}</strong></div>}</div></article><article className="journal-details-panel"><header className="journal-details-panel-header"><h2>Audit activity</h2><p>Creation and posting history.</p></header><div className="journal-details-activity-list"><div><span><UserRound size={14}/>Created by</span><strong>{journal.created_by?.name || "—"}</strong></div><div><span>Created at</span><strong>{dateTime(journal.created_at)}</strong></div><div><span><UserRound size={14}/>Posted by</span><strong>{journal.posted_by?.name || "—"}</strong></div><div><span>Posted at</span><strong>{dateTime(journal.posted_at)}</strong></div></div></article></section>
    <section className="journal-details-panel"><header className="journal-details-panel-header journal-details-lines-header"><div><h2>Journal lines</h2><p>{journal.status === "posted" ? "Posted debit and credit entries. Posted journals are immutable." : "Draft debit and credit lines awaiting posting."}</p></div><span>{journal.lines.length} {journal.lines.length === 1 ? "line" : "lines"}</span></header><div className="journal-details-table-wrapper"><table className="journal-details-table"><caption className="visually-hidden">Debit and credit lines for journal {journal.entry_number}</caption><thead><tr><th>Account code</th><th>Account name</th><th>Description</th><th className="journal-details-amount">Debit</th><th className="journal-details-amount">Credit</th></tr></thead><tbody>{journal.lines.length ? journal.lines.map((line) => <tr key={line.id}><td><Link className="journal-details-account" to={`/accounting/general-ledger?account_id=${line.account.id}`} aria-label={`Open general ledger for ${line.account.code} ${line.account.name}`}><strong>{line.account.code}</strong></Link></td><td><Link className="journal-details-account" to={`/accounting/general-ledger?account_id=${line.account.id}`}><span>{line.account.name}</span></Link></td><td className="journal-details-description">{line.description || journal.description || "—"}</td><td className="journal-details-amount journal-details-debit">{Number(line.debit) ? money(line.debit) : "—"}</td><td className="journal-details-amount journal-details-credit">{Number(line.credit) ? money(line.credit) : "—"}</td></tr>) : <tr><td className="journal-details-empty" colSpan="5">No journal lines are available.</td></tr>}</tbody><tfoot><tr><td colSpan="3">Totals</td><td className="journal-details-amount">{money(totals.debit)}</td><td className="journal-details-amount">{money(totals.credit)}</td></tr><tr className={balanced ? "is-balanced" : "is-unbalanced"}><td colSpan="3">Difference</td><td className="journal-details-amount" colSpan="2">{money(difference)}</td></tr></tfoot></table></div></section>
    {action && <Modal isOpen title={action === "post" ? "Post Journal Entry?" : "Reverse Journal Entry?"} onClose={() => setAction("")}><p>{action === "post" ? "This will post the draft to the general ledger. It cannot be edited afterwards." : "This creates and posts an equal and opposite journal. The original audit record remains unchanged."}</p><div className="journal-modal-actions"><button className="invoice-secondary-button" onClick={() => setAction("")}>Cancel</button><button className="page-primary-button" onClick={() => void mutate()}>{action === "post" ? "Post Journal" : "Reverse Journal"}</button></div></Modal>}
  </div>;
}
