// Validate a balanced manual journal before asking the backend to create or post it.

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Plus, Send, Trash2 } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import PageHeader from "../../components/layout/PageHeader";
import Modal from "../../components/common/Modal";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import { useAuth } from "../../store/AuthContext";
import "../../styles/journals.css";

const today = () => new Date().toISOString().slice(0, 10);
const blankLine = () => ({ id: crypto.randomUUID(), account_id: "", description: "", debit: "", credit: "" });
const toCents = (value) => {
  const match = String(value || "").trim().match(/^(\d+)(?:\.(\d{0,2}))?$/);
  return match ? (BigInt(match[1]) * 100n) + BigInt((match[2] || "").padEnd(2, "0")) : 0n;
};
export default function NewJournalPage() {
  const navigate = useNavigate(); const auth = useAuth();
  const [accounts, setAccounts] = useState([]); const [search, setSearch] = useState("");
  const [form, setForm] = useState({ date: today(), reference: "", description: "", lines: [blankLine(), blankLine()] });
  const [state, setState] = useState({ loading: true, saving: false, error: "" }); const [confirming, setConfirming] = useState(false); const [dirty, setDirty] = useState(false);
  useEffect(() => { let active = true; accountingApiService.accounts({ status: "active" }).then((rows) => { if (active) { setAccounts(rows.filter((account) => account.allow_manual_journals)); setState((value) => ({ ...value, loading: false })); } }).catch((error) => active && setState((value) => ({ ...value, loading: false, error: normaliseApiError(error) }))); return () => { active = false; }; }, []);
  useEffect(() => { const warn = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const totals = useMemo(() => form.lines.reduce((sum, line) => ({ debit: sum.debit + toCents(line.debit), credit: sum.credit + toCents(line.credit) }), { debit: 0n, credit: 0n }), [form.lines]);
  const difference = totals.debit - totals.credit; const balanced = totals.debit > 0n && difference === 0n;
  const visibleAccounts = accounts.filter((account) => `${account.code} ${account.name}`.toLowerCase().includes(search.toLowerCase()));
  const update = (id, field, value) => { setDirty(true); setForm((current) => ({ ...current, lines: current.lines.map((line) => line.id === id ? { ...line, [field]: value, ...(field === "debit" && toCents(value) > 0n ? { credit: "" } : {}), ...(field === "credit" && toCents(value) > 0n ? { debit: "" } : {}) } : line) })); };
  const validate = () => { if (!form.description.trim()) return "Description is required."; if (form.lines.length < 2) return "Add at least two journal lines."; for (const [index, line] of form.lines.entries()) { if (!line.account_id) return `Line ${index + 1} requires an account.`; if ((toCents(line.debit) > 0n) === (toCents(line.credit) > 0n)) return `Line ${index + 1} requires either a debit or a credit.`; } if (!balanced) return "Journal entries must balance before they can be posted."; return ""; };
  const save = async (post) => { const error = validate(); if (error) { setState((value) => ({ ...value, error })); setConfirming(false); return; } setState((value) => ({ ...value, saving: true, error: "" })); try { const journal = await accountingApiService.createManualJournal({ date: form.date, reference: form.reference, description: form.description, post, lines: form.lines.map(({ account_id, description, debit, credit }) => ({ account_id, description, debit: debit || "0.00", credit: credit || "0.00" })) }); setDirty(false); navigate(`/accounting/journals/${journal.id}?created=${post ? "posted" : "draft"}`, { replace: true }); } catch (requestError) { setState((value) => ({ ...value, saving: false, error: normaliseApiError(requestError) })); setConfirming(false); } };
  const money = (cents) => new Intl.NumberFormat("en-GB", { style: "currency", currency: auth.selectedOrganisation?.base_currency || "GBP" }).format(Number(cents) / 100);
  return <div className="journals-page new-journal-page"><PageHeader eyebrow="Accounting · Journals" title="New Journal Entry" description="Record a manual debit and credit adjustment in the general ledger." action={<Link className="invoice-secondary-button" to="/accounting/journals"><ArrowLeft size={16}/>Cancel</Link>}/>
    {state.error && <div className="invoice-form-alert" role="alert">{state.error}</div>}
    <section className="invoice-form-card journal-workspace"><div className="journal-details-grid"><label className="journal-form-field">Journal date<input type="date" required value={form.date} onChange={(event) => { setDirty(true); setForm({ ...form, date: event.target.value }); }}/></label><label className="journal-form-field">Reference<input value={form.reference} onChange={(event) => { setDirty(true); setForm({ ...form, reference: event.target.value }); }} placeholder="Optional reference"/></label><label className="journal-form-field journal-form-field-full">Description / narration<input required value={form.description} onChange={(event) => { setDirty(true); setForm({ ...form, description: event.target.value }); }} placeholder="Explain the reason for this journal"/></label></div>
      <div className="journal-lines-heading"><div><h3>Journal lines</h3><p>Only active accounts that allow manual journals are available.</p></div><button className="invoice-secondary-button" type="button" onClick={() => { setDirty(true); setForm((value) => ({ ...value, lines: [...value.lines, blankLine()] })); }}><Plus size={16}/>Add Line</button></div>
      <label className="journal-account-search">Search accounts<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by account code or name"/></label>
      <div className="journal-lines-wrapper"><div className="journal-lines-header"><span>Account</span><span>Description</span><span>Debit</span><span>Credit</span><span/></div>{form.lines.map((line, index) => <div className="journal-line-row" key={line.id}><select aria-label={`Account for line ${index + 1}`} value={line.account_id} onChange={(event) => update(line.id, "account_id", event.target.value)}><option value="">Select account</option>{visibleAccounts.map((account) => <option value={account.id} key={account.id}>{account.code} · {account.name}</option>)}</select><input aria-label={`Description for line ${index + 1}`} value={line.description} onChange={(event) => update(line.id, "description", event.target.value)} placeholder="Line description"/><input aria-label={`Debit for line ${index + 1}`} inputMode="decimal" value={line.debit} onChange={(event) => update(line.id, "debit", event.target.value)} placeholder="0.00"/><input aria-label={`Credit for line ${index + 1}`} inputMode="decimal" value={line.credit} onChange={(event) => update(line.id, "credit", event.target.value)} placeholder="0.00"/><button type="button" className="journal-remove-line" disabled={form.lines.length <= 2} onClick={() => { setDirty(true); setForm((value) => ({ ...value, lines: value.lines.filter((item) => item.id !== line.id) })); }} aria-label={`Remove line ${index + 1}`}><Trash2 size={16}/></button></div>)}</div>
      <div className="journal-totals journal-sticky-totals"><div><span>Total Debit</span><strong>{money(totals.debit)}</strong></div><div><span>Total Credit</span><strong>{money(totals.credit)}</strong></div><div className={balanced ? "journal-balance-status journal-balanced" : "journal-balance-status journal-unbalanced"}><span>Difference</span><strong>{money(difference < 0n ? -difference : difference)}</strong></div></div>{!balanced && <p className="journal-balance-warning">Journal entries must balance before they can be posted.</p>}
      <div className="journal-modal-actions"><Link className="invoice-secondary-button" to="/accounting/journals">Cancel</Link><button type="button" className="invoice-save-draft-button" disabled={state.saving} onClick={() => void save(false)}>Save Draft</button>{auth.hasPermission("post_journal") && <button type="button" className="page-primary-button" disabled={state.saving || !balanced} onClick={() => setConfirming(true)}><Send size={17}/>Post Journal</button>}</div></section>
    {confirming && <Modal isOpen title="Post Journal Entry?" onClose={() => setConfirming(false)}><p>This will create a posted general ledger entry and cannot be edited afterwards.</p><div className="journal-modal-actions"><button className="invoice-secondary-button" onClick={() => setConfirming(false)}>Cancel</button><button className="page-primary-button" disabled={state.saving} onClick={() => void save(true)}>Post Journal</button></div></Modal>}
  </div>;
}
