import { useCallback,useEffect,useMemo,useState } from "react";
import { AlertTriangle,CheckCircle2,Search,Scale } from "lucide-react";
import { Link } from "react-router-dom";
import PageHeader from "../../components/layout/PageHeader";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import { useAuth } from "../../store/AuthContext";
import { getOrganisationToday } from "../../utils/dateUtils";
import "../../styles/openingBalances.css";
const cents=(value)=>{const match=String(value||"").match(/^(\d+)(?:\.(\d{0,2}))?$/);return match?BigInt(match[1])*100n+BigInt((match[2]||"").padEnd(2,"0")):0n;};
const side=(account)=>["asset","expense"].includes(account.account_type)?"debit":"credit";
export default function OpeningBalancesPage(){
 const auth=useAuth(),org=auth.selectedOrganisation;const [accounts,setAccounts]=useState([]),[record,setRecord]=useState(null),[tab,setTab]=useState("accounts"),[search,setSearch]=useState(""),[hideZero,setHideZero]=useState(false),[message,setMessage]=useState(""),[state,setState]=useState({loading:true,saving:false,error:""});
 const [form,setForm]=useState({opening_date:getOrganisationToday(org?.timezone),reference:"OPENING",description:"Balances brought forward from the previous accounting system",values:{}});
 const load=useCallback(async()=>{setState(v=>({...v,loading:true,error:""}));try{const [accountRows,balanceRows]=await Promise.all([accountingApiService.accounts({status:"active"}),accountingApiService.openingBalances()]);setAccounts(accountRows);const current=balanceRows[0];if(current){setRecord(current);setForm({opening_date:current.opening_date,reference:current.reference,description:current.description,values:Object.fromEntries(current.lines.map(line=>[line.account.id,{debit:String(line.debit),credit:String(line.credit),unusual_side_confirmed:line.unusual_side_confirmed}]))});}setState({loading:false,saving:false,error:""});}catch(error){setState({loading:false,saving:false,error:normaliseApiError(error)});}},[]);
 useEffect(()=>{void load();},[load]);
 const totals=useMemo(()=>Object.values(form.values).reduce((sum,row)=>({debit:sum.debit+cents(row.debit),credit:sum.credit+cents(row.credit)}),{debit:0n,credit:0n}),[form.values]);const difference=totals.debit-totals.credit,balanced=totals.debit>0n&&difference===0n;const money=(value)=>new Intl.NumberFormat(undefined,{style:"currency",currency:org?.base_currency||"GBP"}).format(Number(value)/100);const visible=accounts.filter(a=>(!search||`${a.code} ${a.name}`.toLowerCase().includes(search.toLowerCase()))&&(!hideZero||cents(form.values[a.id]?.debit)||cents(form.values[a.id]?.credit)));
 const change=(account,key,value)=>{if(value&& !/^\d*(?:\.\d{0,2})?$/.test(value))return;setForm(current=>({...current,values:{...current.values,[account.id]:{...current.values[account.id],debit:key==="credit"&&value?"":current.values[account.id]?.debit||"",credit:key==="debit"&&value?"":current.values[account.id]?.credit||"",[key]:value}}}));};
 const payload=()=>({opening_date:form.opening_date,reference:form.reference,description:form.description,lines:accounts.map(account=>({account_id:account.id,debit:form.values[account.id]?.debit||"0",credit:form.values[account.id]?.credit||"0",unusual_side_confirmed:Boolean(form.values[account.id]?.unusual_side_confirmed)}))});
 const act=async(kind)=>{setState(v=>({...v,saving:true,error:""}));try{let next;if(kind==="save")next=record?await accountingApiService.updateOpeningBalance(record.id,payload()):await accountingApiService.createOpeningBalance(payload());else if(kind==="submit")next=await accountingApiService.submitOpeningBalance(record.id);else if(kind==="post")next=await accountingApiService.postOpeningBalance(record.id);else next=await accountingApiService.reverseOpeningBalance(record.id,{reversal_date:getOrganisationToday(org?.timezone)});setRecord(next);setMessage(kind==="save"?"Draft saved.":`Opening balance ${kind}ed successfully.`);setState({loading:false,saving:false,error:""});}catch(error){setState(v=>({...v,saving:false,error:normaliseApiError(error)}));}};
 const editable=!record||record.status==="draft";return <div className="opening-balances-page"><PageHeader eyebrow="Settings · Accounting" title="Opening Balances" description="Bring verified balances forward from your previous accounting system without recreating historical activity." action={<Link className="invoice-secondary-button" to="/accounting/chart-of-accounts">Chart of Accounts</Link>}/>{message&&<div className="chart-accounts-success">{message}</div>}{state.error&&<div className="invoice-form-alert" role="alert">{state.error}</div>}
 <section className="opening-balance-identity"><label>Opening balance date<input disabled={!editable} type="date" value={form.opening_date} onChange={e=>setForm({...form,opening_date:e.target.value})}/><small>Enter balances as at the end of this date. Later transactions form normal Ledgify activity.</small></label><label>Base currency<input disabled value={org?.base_currency||""}/></label><label>Reference<input disabled={!editable} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label className="is-wide">Narration<input disabled={!editable} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div><span>Status</span><strong>{record?.status||"Unsaved draft"}</strong></div><div><span>Created / updated by</span><strong>{record?.updated_by?.name||auth.user?.email||"Current user"}</strong></div></section>
 <nav className="opening-balance-tabs">{[["overview","Overview"],["accounts","Account Balances"],["customers","Customers"],["suppliers","Suppliers"],["bank","Bank and Cash"],["inventory","Inventory"],["review","Review and Post"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 {tab==="accounts"&&<section className="opening-balance-panel"><header><div><h2>Opening Trial Balance</h2><p>Assets and expenses normally debit; liabilities, equity and income normally credit. Unusual sides are allowed but must be reviewed.</p></div><label className="opening-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code or account"/></label><label><input type="checkbox" checked={hideZero} onChange={e=>setHideZero(e.target.checked)}/>Hide zero rows</label></header><div className="opening-table-wrap"><table><thead><tr><th>Account Code</th><th>Account Name</th><th>Account Type</th><th>Normal Balance</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{visible.map(account=>{const row=form.values[account.id]||{};const unusual=(cents(row.debit)>0n&&side(account)==="credit")||(cents(row.credit)>0n&&side(account)==="debit");return <tr key={account.id}><td>{account.code}</td><td>{account.name}{unusual&&<small><AlertTriangle size={12}/>Unusual balance side—review before posting.</small>}</td><td>{account.account_type}</td><td>{side(account)}</td><td><input disabled={!editable} inputMode="decimal" value={row.debit||""} onChange={e=>change(account,"debit",e.target.value)} aria-label={`Debit for ${account.code}`}/></td><td><input disabled={!editable} inputMode="decimal" value={row.credit||""} onChange={e=>change(account,"credit",e.target.value)} aria-label={`Credit for ${account.code}`}/></td></tr>})}</tbody></table></div></section>}
 {["customers","suppliers","inventory"].includes(tab)&&<section className="opening-balance-panel opening-unavailable"><AlertTriangle/><h2>{tab[0].toUpperCase()+tab.slice(1)} opening details</h2><p>Detailed opening subledger import is not enabled because creating partial documents without a tested control-account clearing mechanism could double-count receivables, payables, revenue, expenses, tax, or inventory. Enter the verified control-account balance in the Opening Trial Balance and establish operational detail through the supported workflows.</p></section>}
 {tab==="bank"&&<section className="opening-balance-panel"><h2>Bank and Cash</h2><p>Enter each recognised bank or cash ledger account once in the Account Balances tab. Positive and overdrawn balances may be entered on the accounting side supported by the Chart of Accounts. These opening amounts become brought-forward cash, not a current-period financing inflow.</p>{accounts.filter(a=>a.account_class==="bank").map(a=><p key={a.id}><strong>{a.code} · {a.name}</strong> — Debit {form.values[a.id]?.debit||"0.00"} / Credit {form.values[a.id]?.credit||"0.00"}</p>)}</section>}
 {(tab==="overview"||tab==="review")&&<section className="opening-balance-review"><article><Scale/><span>Total Debits</span><strong>{money(totals.debit)}</strong></article><article><Scale/><span>Total Credits</span><strong>{money(totals.credit)}</strong></article><article className={balanced?"balanced":"unbalanced"}>{balanced?<CheckCircle2/>:<AlertTriangle/>}<span>Difference</span><strong>{money(difference<0n?-difference:difference)}</strong><small>{balanced?"Ready for review":"Debits and credits must agree"}</small></article><div className="opening-review-warning"><strong>Review before posting</strong><p>Opening balances affect the General Ledger, Trial Balance, Balance Sheet, Cash Flow opening cash, and—during a mid-year conversion—Profit and Loss.</p><ul><li>{Object.values(form.values).filter(v=>cents(v.debit)||cents(v.credit)).length} non-zero accounts</li><li>Customer, supplier and inventory detail must be reconciled separately.</li><li>Posting uses the normal journal and locked-period controls.</li></ul></div></section>}
 <footer className="opening-actions">{editable&&auth.hasPermission("manage_opening_balances")&&<button disabled={state.saving} className="invoice-secondary-button" onClick={()=>void act("save")}>Save Draft</button>}{record?.status==="draft"&&balanced&&auth.hasPermission("manage_opening_balances")&&<button disabled={state.saving} className="page-primary-button" onClick={()=>void act("submit")}>Submit for Approval</button>}{record?.status==="submitted"&&auth.hasPermission("approve_opening_balances")&&<button disabled={state.saving} className="page-primary-button" onClick={()=>void act("post")}>Approve and Post</button>}{record?.status==="posted"&&auth.hasPermission("approve_opening_balances")&&<button disabled={state.saving} className="invoice-secondary-button" onClick={()=>void act("reverse")}>Reverse Opening Balance</button>}</footer></div>;
}
