"""Consolidation groups, account mappings, eliminations, and translated report records."""

import uuid
from django.conf import settings
from django.db import models
class ConsolidationGroup(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);name=models.CharField(max_length=150);parent_organisation=models.ForeignKey("organisations.Organisation",on_delete=models.PROTECT,related_name="consolidation_groups");reporting_currency=models.ForeignKey("fx.Currency",on_delete=models.PROTECT);status=models.CharField(max_length=10,choices=(("active","Active"),("inactive","Inactive")),default="active");cta_account=models.ForeignKey("self_account",on_delete=models.PROTECT,null=True,blank=True) if False else models.ForeignKey("consolidation.ConsolidationAccount",on_delete=models.PROTECT,null=True,blank=True,related_name="cta_groups");created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT);created_at=models.DateTimeField(auto_now_add=True);updated_at=models.DateTimeField(auto_now=True)
class ConsolidationGroupMember(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);group=models.ForeignKey(ConsolidationGroup,on_delete=models.CASCADE,related_name="members");organisation=models.ForeignKey("organisations.Organisation",on_delete=models.PROTECT);ownership_percentage=models.DecimalField(max_digits=7,decimal_places=4,default=100);consolidation_method=models.CharField(max_length=20,choices=(("full","Full"),("proportionate","Proportionate"),("equity","Equity")),default="full");effective_from=models.DateField();effective_to=models.DateField(null=True,blank=True);status=models.CharField(max_length=10,default="active");created_at=models.DateTimeField(auto_now_add=True)
 class Meta:constraints=[models.UniqueConstraint(fields=["group","organisation"],name="unique_group_member")]
class ConsolidationPeriod(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);group=models.ForeignKey(ConsolidationGroup,on_delete=models.CASCADE,related_name="periods");start_date=models.DateField();end_date=models.DateField();status=models.CharField(max_length=12,choices=(("open","Open"),("prepared","Prepared"),("finalised","Finalised")),default="open");prepared_at=models.DateTimeField(null=True,blank=True);prepared_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,null=True,blank=True,related_name="consolidations_prepared");finalised_at=models.DateTimeField(null=True,blank=True);finalised_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,null=True,blank=True,related_name="consolidations_finalised");created_at=models.DateTimeField(auto_now_add=True)
class ConsolidationAccount(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);group=models.ForeignKey(ConsolidationGroup,on_delete=models.CASCADE,related_name="accounts");code=models.CharField(max_length=30);name=models.CharField(max_length=150);account_type=models.CharField(max_length=20);account_class=models.CharField(max_length=30);cash_flow_category=models.CharField(max_length=30,default="not_applicable");display_order=models.IntegerField(default=0);status=models.CharField(max_length=10,default="active")
 class Meta:constraints=[models.UniqueConstraint(fields=["group","code"],name="unique_group_account")]
class ConsolidationAccountMapping(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);group=models.ForeignKey(ConsolidationGroup,on_delete=models.CASCADE,related_name="mappings");organisation=models.ForeignKey("organisations.Organisation",on_delete=models.PROTECT);source_account=models.ForeignKey("accounting.Account",on_delete=models.PROTECT);consolidation_account=models.ForeignKey(ConsolidationAccount,on_delete=models.PROTECT);effective_from=models.DateField();effective_to=models.DateField(null=True,blank=True)
 class Meta:
  constraints=[models.UniqueConstraint(fields=["group","source_account","effective_from"],name="unique_active_source_mapping_date")]
class ConsolidationSnapshot(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);group=models.ForeignKey(ConsolidationGroup,on_delete=models.PROTECT);period=models.ForeignKey(ConsolidationPeriod,on_delete=models.PROTECT,related_name="snapshots");organisation=models.ForeignKey("organisations.Organisation",on_delete=models.PROTECT);source_currency=models.CharField(max_length=3);reporting_currency=models.CharField(max_length=3);translation_metadata=models.JSONField(default=dict);version=models.PositiveIntegerField(default=1);created_at=models.DateTimeField(auto_now_add=True)
class ConsolidationSnapshotLine(models.Model):
 snapshot=models.ForeignKey(ConsolidationSnapshot,on_delete=models.PROTECT,related_name="lines");source_account=models.ForeignKey("accounting.Account",on_delete=models.PROTECT);consolidation_account=models.ForeignKey(ConsolidationAccount,on_delete=models.PROTECT);source_debit=models.DecimalField(max_digits=18,decimal_places=2);source_credit=models.DecimalField(max_digits=18,decimal_places=2);translated_debit=models.DecimalField(max_digits=18,decimal_places=2);translated_credit=models.DecimalField(max_digits=18,decimal_places=2);exchange_rate=models.DecimalField(max_digits=20,decimal_places=10);translation_method=models.CharField(max_length=20)
class EliminationJournal(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);group=models.ForeignKey(ConsolidationGroup,on_delete=models.PROTECT);period=models.ForeignKey(ConsolidationPeriod,on_delete=models.PROTECT,related_name="eliminations");entry_number=models.CharField(max_length=50);date=models.DateField();description=models.TextField();reference=models.CharField(max_length=100,blank=True);status=models.CharField(max_length=10,choices=(("draft","Draft"),("posted","Posted"),("reversed","Reversed")),default="draft");created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name="eliminations_created");posted_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,null=True,blank=True,related_name="eliminations_posted");posted_at=models.DateTimeField(null=True,blank=True);reversal_of=models.OneToOneField("self",on_delete=models.PROTECT,null=True,blank=True,related_name="reversal_entry");reversed_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,null=True,blank=True,related_name="eliminations_reversed");reversed_at=models.DateTimeField(null=True,blank=True)
 class Meta:constraints=[models.UniqueConstraint(fields=["group","entry_number"],name="unique_group_elimination_number")]
class EliminationJournalLine(models.Model):
 journal=models.ForeignKey(EliminationJournal,on_delete=models.CASCADE,related_name="lines");consolidation_account=models.ForeignKey(ConsolidationAccount,on_delete=models.PROTECT);debit=models.DecimalField(max_digits=18,decimal_places=2,default=0);credit=models.DecimalField(max_digits=18,decimal_places=2,default=0);organisation=models.ForeignKey("organisations.Organisation",on_delete=models.PROTECT,null=True,blank=True,related_name="elimination_lines");counterparty_organisation=models.ForeignKey("organisations.Organisation",on_delete=models.PROTECT,null=True,blank=True,related_name="counterparty_elimination_lines");description=models.CharField(max_length=255,blank=True)
class ConsolidationHistory(models.Model):
 group=models.ForeignKey(ConsolidationGroup,on_delete=models.PROTECT);period=models.ForeignKey(ConsolidationPeriod,on_delete=models.PROTECT);event=models.CharField(max_length=30);user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT);timestamp=models.DateTimeField(auto_now_add=True);reason=models.TextField(blank=True);metadata=models.JSONField(default=dict)
