from datetime import date
from decimal import Decimal
from django.contrib.auth import get_user_model
from django.test import TestCase
from common.exceptions import BusinessRuleError
from apps.accounting.models import Account,JournalEntry,JournalLine
from apps.consolidation.models import ConsolidationAccount,ConsolidationAccountMapping,ConsolidationGroup,ConsolidationGroupMember,ConsolidationPeriod,EliminationJournal,EliminationJournalLine
from apps.consolidation.serializers import MappingSerializer,MemberSerializer
from apps.consolidation.services import consolidated_balance_sheet,consolidated_profit_loss,consolidated_trial_balance,post_elimination,prepare_consolidation,reverse_elimination
from apps.fx.models import Currency
from apps.organisations.models import Organisation,OrganisationMember

class ConsolidationWorkflowTests(TestCase):
 def setUp(self):
  self.user=get_user_model().objects.create_user(username="group",email="group@example.com",password="x",first_name="G",last_name="R");Currency.objects.get_or_create(code="GBP",defaults={"name":"Pound"});self.parent=self.org("Parent");self.sub=self.org("Subsidiary");self.outsider=self.org("Outsider");self.group=ConsolidationGroup.objects.create(name="Group",parent_organisation=self.parent,reporting_currency_id="GBP",created_by=self.user);self.member=ConsolidationGroupMember.objects.create(group=self.group,organisation=self.sub,ownership_percentage=100,consolidation_method="full",effective_from=date(2026,1,1));self.period=ConsolidationPeriod.objects.create(group=self.group,start_date=date(2026,1,1),end_date=date(2026,12,31));self.cash=self.account(self.sub,"1000","Cash","asset","bank");self.equity=self.account(self.sub,"3000","Equity","equity","equity");self.gc=ConsolidationAccount.objects.create(group=self.group,code="G1000",name="Cash",account_type="asset",account_class="bank");self.ge=ConsolidationAccount.objects.create(group=self.group,code="G3000",name="Equity",account_type="equity",account_class="equity");ConsolidationAccountMapping.objects.create(group=self.group,organisation=self.sub,source_account=self.cash,consolidation_account=self.gc,effective_from=date(2026,1,1));ConsolidationAccountMapping.objects.create(group=self.group,organisation=self.sub,source_account=self.equity,consolidation_account=self.ge,effective_from=date(2026,1,1));journal=JournalEntry.objects.create(organisation=self.sub,entry_number="SUB-1",date=date(2026,1,2),description="Capital",status="draft",created_by=self.user);JournalLine.objects.create(journal_entry=journal,account=self.cash,debit=100,credit=0);JournalLine.objects.create(journal_entry=journal,account=self.equity,debit=0,credit=100);JournalEntry.objects.filter(pk=journal.pk).update(status="posted")
 def org(self,name):
  org=Organisation.objects.create(name=name,base_currency="GBP",created_by=self.user);OrganisationMember.objects.create(organisation=org,user=self.user,role="owner");return org
 def account(self,org,code,name,kind,klass):return Account.objects.create(organisation=org,created_by=self.user,code=code,name=name,account_type=kind,account_class=klass)
 def test_member_and_mapping_validation(self):
  invalid=MemberSerializer(data={"group":self.group.id,"organisation":self.outsider.id,"ownership_percentage":"80","consolidation_method":"full","effective_from":"2026-01-01","status":"active"});self.assertFalse(invalid.is_valid());foreign=self.account(self.outsider,"9000","Foreign","asset","current_asset");mapping=MappingSerializer(data={"group":self.group.id,"organisation":self.outsider.id,"source_account":foreign.id,"consolidation_account":self.gc.id,"effective_from":"2026-01-01"});self.assertFalse(mapping.is_valid())
 def test_prepare_elimination_reports_and_reversal(self):
  prepare_consolidation(group=self.group,period=self.period,user=self.user);draft=EliminationJournal.objects.create(group=self.group,period=self.period,entry_number="ELIM-1",date=date(2026,12,31),description="Eliminate",created_by=self.user);EliminationJournalLine.objects.create(journal=draft,consolidation_account=self.gc,debit=0,credit=10);EliminationJournalLine.objects.create(journal=draft,consolidation_account=self.ge,debit=10,credit=0);post_elimination(journal=draft,user=self.user);tb=consolidated_trial_balance(group=self.group,period=self.period);self.assertTrue(tb["balanced"]);self.assertEqual(tb["total_debit"],Decimal("110.00"));self.assertTrue(consolidated_balance_sheet(group=self.group,period=self.period)["balanced"]);self.assertEqual(consolidated_profit_loss(group=self.group,period=self.period)["net_profit"],0);reversal=reverse_elimination(journal=draft,user=self.user,date=date(2026,12,31));self.assertEqual(reversal.lines.aggregate(total=__import__("django.db.models",fromlist=["Sum"]).Sum("debit"))["total"],Decimal("10"))
  with self.assertRaises(BusinessRuleError):reverse_elimination(journal=draft,user=self.user)
 def test_unmapped_account_blocks_prepare(self):
  self.account(self.sub,"1010","Unmapped","asset","current_asset");journal=JournalEntry.objects.create(organisation=self.sub,entry_number="SUB-2",date=date(2026,1,3),description="Missing",status="draft",created_by=self.user);account=self.sub.accounts.get(code="1010");JournalLine.objects.create(journal_entry=journal,account=account,debit=5,credit=0);JournalLine.objects.create(journal_entry=journal,account=self.equity,debit=0,credit=5);JournalEntry.objects.filter(pk=journal.pk).update(status="posted")
  with self.assertRaises(BusinessRuleError):prepare_consolidation(group=self.group,period=self.period,user=self.user)
