from datetime import date
from decimal import Decimal
from django.contrib.auth import get_user_model
from django.test import TestCase
from common.exceptions import BusinessRuleError
from apps.accounting.models import Account
from apps.inventory.models import InventoryCostLayer,Product,StockMovement,Warehouse
from apps.manufacturing.models import BOMComponent,BOMVersion,BillOfMaterials,ProductionCostTransaction
from apps.manufacturing.services import *
from apps.organisations.models import Organisation,OrganisationMember

class Manufacturing14BTests(TestCase):
 def setUp(self):
  self.user=get_user_model().objects.create_user(username="maker",email="maker@example.com",password="x",first_name="M",last_name="R");self.org=Organisation.objects.create(name="Factory",base_currency="GBP",created_by=self.user);OrganisationMember.objects.create(organisation=self.org,user=self.user,role="owner");self.inv=self.account("1200","Inventory","asset","current_asset");self.wip=self.account("1210","WIP","asset","current_asset");self.cogs=self.account("5000","COGS","expense","cost_of_sales");self.wh=Warehouse.objects.create(organisation=self.org,code="MAIN",name="Main",is_default=True,created_by=self.user);self.a=self.product("A");self.b=self.product("B");self.c=self.product("C")
 def account(self,code,name,kind,klass):return Account.objects.create(organisation=self.org,code=code,name=name,account_type=kind,account_class=klass,currency="GBP",created_by=self.user)
 def product(self,code):return Product.objects.create(organisation=self.org,code=code,name=code,product_type="goods",unit="each",currency="GBP",track_inventory=True,inventory_asset_account=self.inv,cost_of_goods_sold_account=self.cogs,created_by=self.user)
 def bom(self,product,code,components,start=date(2026,1,1),end=None):
  bom=BillOfMaterials.objects.create(organisation=self.org,product=product,code=code,name=code,created_by=self.user);version=BOMVersion.objects.create(bom=bom,version_number="1",effective_from=start,effective_to=end,output_quantity=1,status="active",created_by=self.user)
  for sequence,(item,qty,scrap) in enumerate(components):BOMComponent.objects.create(bom_version=version,component_product=item,quantity=qty,scrap_percentage=scrap,sequence=sequence)
  return version
 def stock(self,product,qty,cost):
  qty,cost=Decimal(str(qty)),Decimal(str(cost));movement=StockMovement.objects.create(organisation=self.org,product=product,warehouse=self.wh,movement_date=date(2026,1,1),movement_type="opening",quantity=qty,unit_cost=cost,total_cost=qty*cost,source_type="opening",status="posted",created_by=self.user)
  InventoryCostLayer.objects.create(organisation=self.org,product=product,warehouse=self.wh,movement=movement,quantity_on_hand=qty,total_cost=qty*cost,average_unit_cost=cost,effective_date=date(2026,1,1))
 def test_versions_explosion_scrap_and_cost(self):
  v=self.bom(self.a,"A-BOM",[(self.b,2,Decimal("10")),(self.c,3,0)],end=date(2026,6,30));self.assertEqual(get_effective_bom_version(organisation=self.org,product=self.a,date=date(2026,3,1)),v)
  with self.assertRaises(BusinessRuleError):BOMVersion.objects.create(bom=v.bom,version_number="2",effective_from=date(2026,6,1),output_quantity=1,status="active",created_by=self.user)
  data=explode_bom(organisation=self.org,product=self.a,quantity=10,production_date=date(2026,3,1));amounts={x["product"]["code"]:x["required_quantity"] for x in data["flattened_requirements"]};self.assertEqual(amounts,{"B":Decimal("22.000000000000"),"C":Decimal("30.00000000")})
  self.stock(self.b,30,5);self.stock(self.c,40,2);cost=calculate_bom_cost(organisation=self.org,bom_version=v,warehouse=self.wh);self.assertEqual(cost["material_cost"],Decimal("17.000000000000"))
 def test_draft_version_activation_supersedes_current_version(self):
  current=self.bom(self.a,"A-BOM",[(self.b,1,0)]);draft=BOMVersion.objects.create(bom=current.bom,version_number="2",effective_from=date(2026,7,1),output_quantity=1,status="draft",created_by=self.user);BOMComponent.objects.create(bom_version=draft,component_product=self.c,quantity=2);activate_bom_version(organisation=self.org,bom_version=draft);current.refresh_from_db();draft.refresh_from_db();self.assertEqual(current.status,"superseded");self.assertEqual(current.effective_to,date(2026,6,30));self.assertEqual(draft.status,"active")
 def test_multilevel_cycle_and_release_snapshot(self):
  self.bom(self.b,"B-BOM",[(self.c,3,0)]);va=self.bom(self.a,"A-BOM",[(self.b,2,0)]);data=explode_bom(organisation=self.org,product=self.a,quantity=10,production_date=date(2026,2,1));self.assertEqual(data["flattened_requirements"][0]["required_quantity"],Decimal("60.000000000000"));self.stock(self.c,100,4)
  order=create_production_order(organisation=self.org,product=self.a,warehouse=self.wh,planned_quantity=10,start_date=date(2026,2,1),due_date=date(2026,2,28),wip_account=self.wip,user=self.user,bom_version=va,order_number="PO1");release_production_order(organisation=self.org,production_order=order,user=self.user);snapshot=order.components.get();self.assertEqual(snapshot.required_quantity,Decimal("60"));BOMComponent.objects.filter(bom_version=va).update(quantity=9);snapshot.refresh_from_db();self.assertEqual(snapshot.required_quantity,Decimal("60"));
  with self.assertRaises(BusinessRuleError):release_production_order(organisation=self.org,production_order=order,user=self.user)
  vc=self.bom(self.c,"C-BOM",[(self.a,1,0)])
  with self.assertRaises(BusinessRuleError):validate_bom_no_cycles(organisation=self.org,bom_version=vc)
 def test_issue_return_requirements_and_no_cogs(self):
  v=self.bom(self.a,"A-BOM",[(self.b,10,0)]);self.stock(self.b,10,20);order=create_production_order(organisation=self.org,product=self.a,warehouse=self.wh,planned_quantity=1,start_date=date(2026,2,1),due_date=date(2026,2,28),wip_account=self.wip,user=self.user,bom_version=v,order_number="PO2");release_production_order(organisation=self.org,production_order=order,user=self.user);component=order.components.get();issue_production_order_materials(organisation=self.org,production_order=order,lines=[{"production_order_component_id":component.id,"quantity":4}],issue_date=date(2026,2,2),user=self.user);component.refresh_from_db();self.assertEqual(component.issued_quantity,4);journal=ProductionCostTransaction.objects.get(cost_type="material").journal_entry;self.assertTrue(journal.lines.filter(account=self.wip,debit=80).exists());self.assertFalse(journal.lines.filter(account=self.cogs).exists());return_production_order_material(organisation=self.org,production_order=order,component=component,quantity=1,return_date=date(2026,2,3),user=self.user);component.refresh_from_db();self.assertEqual(component.returned_quantity,1);self.assertEqual(get_production_material_requirements(organisation=self.org,production_order=order)[0]["remaining_to_issue"],7)
 def test_batch_failure_rolls_back_everything(self):
  v=self.bom(self.a,"A-BOM",[(self.b,2,0),(self.c,2,0)]);self.stock(self.b,2,10);self.stock(self.c,1,10);order=create_production_order(organisation=self.org,product=self.a,warehouse=self.wh,planned_quantity=1,start_date=date(2026,2,1),due_date=date(2026,2,28),wip_account=self.wip,user=self.user,bom_version=v,order_number="PO3");release_production_order(organisation=self.org,production_order=order,user=self.user);parts=list(order.components.order_by("product__code"));before=(StockMovement.objects.count(),InventoryCostLayer.objects.count(),ProductionCostTransaction.objects.count())
  with self.assertRaises(BusinessRuleError):issue_production_order_materials(organisation=self.org,production_order=order,lines=[{"production_order_component_id":parts[0].id,"quantity":2},{"production_order_component_id":parts[1].id,"quantity":2}],issue_date=date(2026,2,2),user=self.user)
  self.assertEqual((StockMovement.objects.count(),InventoryCostLayer.objects.count(),ProductionCostTransaction.objects.count()),before);self.assertFalse(order.components.exclude(issued_quantity=0).exists())

 def test_partial_completions_wac_late_cost_variance_and_close(self):
  version=self.bom(self.a,"A-BOM",[(self.b,1,0)]);self.stock(self.b,10,20);labour=self.account("2100","Labour clearing","liability","current_liability");overhead=self.account("2110","Overhead applied","liability","current_liability");variance=self.account("5900","Production variance","expense","cost_of_sales")
  order=create_production_order(organisation=self.org,product=self.a,warehouse=self.wh,planned_quantity=10,start_date=date(2026,2,1),due_date=date(2026,2,28),wip_account=self.wip,variance_account=variance,user=self.user,bom_version=version,order_number="PO4");release_production_order(organisation=self.org,production_order=order,user=self.user);component=order.components.get();issue_production_order_materials(organisation=self.org,production_order=order,lines=[{"production_order_component_id":component.id,"quantity":10}],issue_date=date(2026,2,2),user=self.user)
  labour_tx=add_labour_cost(organisation=self.org,production_order=order,date=date(2026,2,3),amount=100,source_account=labour,user=self.user);add_overhead_cost(organisation=self.org,production_order=order,date=date(2026,2,3),amount=50,source_account=overhead,user=self.user);self.assertTrue(labour_tx.journal_entry.lines.filter(account=self.wip,debit=100).exists());self.assertEqual(get_current_wip(organisation=self.org,production_order=order),Decimal("350.00"))
  first=complete_production(organisation=self.org,production_order=order,quantity_completed=2,completion_date=date(2026,2,4),destination_warehouse=self.wh,user=self.user);self.assertEqual(first["transfer_amount"],Decimal("70.00"));order.refresh_from_db();self.assertEqual(order.status,"partly_completed")
  add_labour_cost(organisation=self.org,production_order=order,date=date(2026,2,5),amount=50,source_account=labour,user=self.user);second=complete_production(organisation=self.org,production_order=order,quantity_completed=3,completion_date=date(2026,2,6),destination_warehouse=self.wh,user=self.user);third=complete_production(organisation=self.org,production_order=order,quantity_completed=5,completion_date=date(2026,2,7),destination_warehouse=self.wh,user=self.user);self.assertEqual(second["transfer_amount"],Decimal("130.00"));self.assertEqual(third["transfer_amount"],Decimal("200.00"));self.assertEqual(get_current_wip(organisation=self.org,production_order=order),Decimal("0.00"))
  layer=InventoryCostLayer.objects.filter(product=self.a,warehouse=self.wh).latest("created_at");self.assertEqual(layer.quantity_on_hand,Decimal("10"));self.assertEqual(layer.total_cost,Decimal("400.00"));self.assertEqual(InventoryCostLayer.objects.filter(product=self.a,warehouse=self.wh).count(),3)
  add_overhead_cost(organisation=self.org,production_order=order,date=date(2026,2,8),amount=10,source_account=overhead,user=self.user);closed=close_production_order(organisation=self.org,production_order=order,close_date=date(2026,2,9),user=self.user);self.assertEqual(closed["variance_transaction"].amount,Decimal("-10.00"));self.assertTrue(closed["variance_transaction"].journal_entry.lines.filter(account=variance,debit=10).exists());self.assertEqual(get_current_wip(organisation=self.org,production_order=order),Decimal("0.00"));order.refresh_from_db();self.assertEqual(order.status,"closed")
  with self.assertRaises(BusinessRuleError):add_labour_cost(organisation=self.org,production_order=order,date=date(2026,2,10),amount=1,source_account=labour,user=self.user)
  dashboard=manufacturing_dashboard(organisation=self.org);self.assertEqual(dashboard["kpis"]["production_variance"],Decimal("-10.00"));self.assertEqual(len(bom_cost_report(organisation=self.org)),1);self.assertEqual(len(variance_report(organisation=self.org)),1);self.assertEqual(len(material_usage_report(organisation=self.org)),1);self.assertEqual(len(finished_goods_output_report(organisation=self.org)),3);self.assertEqual(wip_report(organisation=self.org),[])
