# Generated by Django 6.1 on 2026-08-12 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_journalentry_source_type'),
        ('banking', '0002_banktransaction_reconciliation_object_id_and_more'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='unreconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='unreconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions_unreconciled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='unreconciliation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BankReconciliationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('reconciled', 'Reconciled'), ('unreconciled', 'Unreconciled')], max_length=20)),
                ('reconciliation_type', models.CharField(max_length=50)),
                ('reconciliation_object_id', models.UUIDField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('accounting_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliation_history', to='accounting.journalentry')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_history', to='banking.banktransaction')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliation_history', to='organisations.organisation')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['organisation', 'bank_transaction'], name='banking_ban_organis_257c5e_idx'), models.Index(fields=['organisation', 'action'], name='banking_ban_organis_06fc70_idx')],
            },
        ),
    ]
