# Generated by Django 6.1 on 2026-09-10 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_phase2_integrity'),
        ('banking', '0004_bankrule_bankstatementimport_bankstatementimportrow'),
        ('organisations', '0006_normalise_legacy_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='import_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('import_fingerprint__isnull', False)), fields=('organisation', 'bank_account', 'import_fingerprint'), name='unique_bank_import_fingerprint'),
        ),
    ]
