# Generated by Django 6.1 on 2026-09-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_phase2_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimportrow',
            name='duplicate_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bankstatementimportrow',
            name='source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bankstatementimportrow',
            name='statement_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementimportrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('duplicate', 'Duplicate'), ('imported', 'Imported'), ('rejected', 'Rejected'), ('information', 'Statement balance')], default='pending', max_length=20),
        ),
    ]
