import { useEffect, useState } from 'react';
import { api } from '../../services/api';
import { useAuth } from '../../store/AuthContext';
import { getOrganisationToday } from '../../utils/dateUtils';
import { normaliseApiError } from '../../services/apiError';
export default function TaxClassifications({codes,run,busy}){
 const auth=useAuth();const [products,setProducts]=useState([]),[contacts,setContacts]=useState([]),[error,setError]=useState('');
 const [form,setForm]=useState({target:'contact',target_id:'',code_id:'',effective_from:getOrganisationToday(auth.selectedOrganisation?.timezone),source_note:''});
 useEffect(()=>{let live=true;Promise.all([api.get('products/'),api.get('contacts/')]).then(([p,c])=>{if(live){setProducts(p);setContacts(c);}}).catch(e=>{if(live)setError(normaliseApiError(e));});return()=>{live=false;};},[]);
 if(!auth.hasPermission('assign_tax_codes'))return null;
 return <section><h2>Product and contact tax classifications</h2><p>Record a reviewed effective-dated classification. Transaction entry will suggest it and require explicit confirmation.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void run(()=>api.post('tax/configuration/classify/',{[form.target+'_id']:form.target_id,code_id:form.code_id,effective_from:form.effective_from,source_note:form.source_note}));}}><div className="tax-config-grid"><label>Classification target<select value={form.target} onChange={e=>setForm({...form,target:e.target.value,target_id:''})}><option value="contact">Customer / supplier</option><option value="product">Product / service</option></select></label><label>Record<select required value={form.target_id} onChange={e=>setForm({...form,target_id:e.target.value})}><option value="">Select</option>{(form.target==='product'?products:contacts).map(obj=><option key={obj.id} value={obj.id}>{obj.name}</option>)}</select></label><label>Reviewed code<select required value={form.code_id} onChange={e=>setForm({...form,code_id:e.target.value})}><option value="">Select</option>{codes.filter(c=>c.family==='INDIRECT'&&!c.tracking_only).map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><label>Effective from<input required type="date" value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label><label>Classification source and reason<textarea required value={form.source_note} onChange={e=>setForm({...form,source_note:e.target.value})}/></label></div><button disabled={busy}>Save reviewed classification</button></form></section>;
}
