import { ReadableTaxRecord } from '../tax/TaxSettingsUi';
import { taxUiLabel } from '../../utils/taxSettingsPresentation';
import { createPaymentSubmission } from '../../utils/paymentSubmission';
import { useState } from 'react';
import { api } from '../../services/api';
import { useAuth } from '../../store/AuthContext';
import { getOrganisationToday } from '../../utils/dateUtils';
import { saveBlob } from '../../utils/reportExport';

export function ReturnOperations({record,accounts,periods,run,busy}) {
 const auth=useAuth(), today=getOrganisationToday(auth.selectedOrganisation?.timezone);
 const [paymentSubmission]=useState(createPaymentSubmission),[adjustmentSubmission]=useState(createPaymentSubmission);
 const postOnce=async(submission,path,payload)=>{const key=submission.begin(payload);if(!key)return;try{const result=await api.post(path,{...payload,idempotency_key:key});submission.complete();return result;}finally{submission.finish();}};
 const [payment,setPayment]=useState({date:today,amount:'',account_id:'',bank_account_id:'',reference:'',allocations:{}});
 const [adjustment,setAdjustment]=useState({date:today,period_id:'',account_id:'',counter_account_id:'',amount:'',direction:'OUTPUT',component_code:'',reason:''});
 const [reversal,setReversal]=useState(null);
 const [ack,setAck]=useState(''),[file,setFile]=useState(null);
 const select=(label,name,value,onChange,options)=><label>{label}<select required value={value} onChange={e=>onChange(name,e.target.value)}><option value="">Select</option>{options.map(a=><option key={a.id} value={a.id}>{a.code||a.start_date} · {a.name||a.end_date}</option>)}</select></label>;
 const field=(label,name,form,setter,type='text')=><label>{label}<input required type={type} value={form[name]} onChange={e=>setter({...form,[name]:e.target.value})}/></label>;
 return <>
 {auth.hasPermission('export_gra_schedules')&&['REVIEWED','APPROVED','EXPORTED','FILED','PAID'].includes(record.status)&&<button disabled={busy} onClick={()=>run(async()=>saveBlob(await api.post(`tax/returns/${record.id}/workpaper-export/`,{},{responseType:'blob'}),'tax-review-workpaper.json'))}>Download reconciliation workpaper</button>}
 {auth.hasPermission('export_gra_schedules')&&['REVIEWED','APPROVED','EXPORTED','FILED','PAID'].includes(record.status)&&<button disabled={busy} onClick={()=>run(async()=>saveBlob(await api.post(`tax/returns/${record.id}/workpaper-export/`,{format:'pdf'},{responseType:'blob'}),'tax-review-workpaper.pdf'))}>Download readable workpaper PDF</button>}
 {record.filing_evidence?.length>0&&<details><summary>Filing acknowledgements and evidence</summary>{record.filing_evidence.map(e=><p key={e.id}>{e.acknowledgement} · {e.created_at}{e.filename&&<button disabled={busy} onClick={()=>run(async()=>saveBlob(await api.download(`tax/returns/evidence/${e.id}/download/`),e.filename))}>Download {e.filename}</button>}</p>)}</details>}
 {record.payments?.length>0&&<details><summary>Recorded payments and refunds</summary>{record.payments.map(p=><p key={p.id}>{p.payment_date} · {p.amount} · {p.reference} · {p.reversed?'Reversed':'Posted'}{!p.reversed&&auth.hasPermission('record_tax_payment')&&auth.hasPermission('reverse_journal')&&<button disabled={busy} onClick={()=>setReversal({payment_id:p.id,date:today,reason:'',confirmed:false})}>Correct recorded payment</button>}</p>)}</details>}
 {reversal&&<section><h3>Reverse recorded tax payment</h3><p>This reverses the accounting entry and its control allocations. It does not move money or cancel a payment with the bank or tax authority. The filed return is retained.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api.post(`tax/returns/${record.id}/reverse-payment/`,reversal);setReversal(null);});}}>{field('Reversal date','date',reversal,setReversal,'date')}{field('Correction reason','reason',reversal,setReversal)}<label><input type="checkbox" checked={reversal.confirmed} onChange={e=>setReversal({...reversal,confirmed:e.target.checked})}/>I confirm reversal of this recorded payment and all its tax-control allocations.</label><button disabled={busy||!reversal.confirmed}>Reverse confirmed tax payment</button><button type="button" disabled={busy} onClick={()=>setReversal(null)}>Cancel correction</button></form></section>}
 <details><summary>Reviewed snapshot and source records</summary><ReadableTaxRecord value={record.snapshot} accounts={accounts}/></details>
 {auth.hasPermission('record_tax_filing')&&<details><summary>Upload private filing evidence</summary><form onSubmit={e=>{e.preventDefault();void run(async()=>{const body=new FormData();body.append('file',file);body.append('acknowledgement',ack);await api.postForm(`tax/returns/${record.id}/evidence/`,body);setAck('');setFile(null);});}}><label>Actual acknowledgement<input required value={ack} onChange={e=>setAck(e.target.value)}/></label><label>PDF, PNG or JPEG under 5 MB<input required type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files[0]||null)}/></label><button disabled={busy||!file}>Upload evidence</button></form></details>}
 {auth.hasPermission('record_tax_payment')&&record.status==='FILED'&&<details><summary>Record tax payment</summary><form onSubmit={e=>{e.preventDefault();void run(()=>postOnce(paymentSubmission,`tax/returns/${record.id}/payment/`,{...payment,allocations:Object.entries(payment.allocations).filter(([,amount])=>amount!=='').map(([account_id,amount])=>({account_id,amount}))}));}}><p>Record an actual payment against this filed return. Amounts are in {auth.selectedOrganisation?.base_currency}.</p><div className="tax-config-grid">{field('Payment date','date',payment,setPayment,'date')}{field('Signed bank amount (negative for refund)','amount',payment,setPayment)}{field('Payment reference','reference',payment,setPayment)}{Number(payment.amount)!==0&&select('Bank account','bank_account_id',payment.bank_account_id,(k,v)=>setPayment({...payment,[k]:v}),accounts.filter(a=>a.account_class==='bank'))}</div><fieldset><legend>Reviewed control allocations</legend><p>Enter positive allocation amounts. The backend determines debit/credit from the reviewed balance. Final settlement must clear all controls.</p>{Object.entries(record.settlement_balances||{}).filter(([,balance])=>Number(balance)!==0).map(([id,balance])=><label key={id}>{accounts.find(a=>a.id===id)?.name||id} · Remaining signed balance {balance}<input inputMode="decimal" value={payment.allocations[id]||''} onChange={e=>setPayment({...payment,allocations:{...payment.allocations,[id]:e.target.value}})}/></label>)}</fieldset><button disabled={busy}>Record confirmed payment / refund</button></form></details>}
 {auth.hasPermission('approve_tax_returns')&&['APPROVED','EXPORTED','FILED','PAID'].includes(record.status)&&<details><summary>Post a correction in an open period</summary><form onSubmit={e=>{e.preventDefault();void run(()=>postOnce(adjustmentSubmission,'tax/returns/adjustment/',{...adjustment,original_return_id:record.id}));}}><p>The filed snapshot stays unchanged. Review the signed adjustment and counterpart before posting.</p><div className="tax-config-grid">{select('Open period','period_id',adjustment.period_id,(k,v)=>setAdjustment({...adjustment,[k]:v}),periods.filter(p=>p.status==='OPEN'))}{field('Adjustment date','date',adjustment,setAdjustment,'date')}{field('Signed amount','amount',adjustment,setAdjustment)}{field('Component code','component_code',adjustment,setAdjustment)}<label>Direction<select value={adjustment.direction} onChange={e=>setAdjustment({...adjustment,direction:e.target.value})}><option>OUTPUT</option><option>INPUT</option></select></label>{select('Mapped tax control','account_id',adjustment.account_id,(k,v)=>setAdjustment({...adjustment,[k]:v}),accounts)}{select('Counterpart account','counter_account_id',adjustment.counter_account_id,(k,v)=>setAdjustment({...adjustment,[k]:v}),accounts)}{field('Reason','reason',adjustment,setAdjustment)}</div><button disabled={busy}>Post reviewed adjustment</button></form></details>}
 </>;
}

export function TaxDashboard({data,run,busy}) {
 const auth=useAuth(),today=getOrganisationToday(auth.selectedOrganisation?.timezone);
 const [support,setSupport]=useState({registration_id:'',notes:'',file:null}),[calendarAction,setCalendarAction]=useState(null);
 const [calendar,setCalendar]=useState({responsible_user_id:auth.user?.id||'',registration_id:'',period_start:today,period_end:today,due_date:today,payment_due_date:'',source:'',rule_version:'',reminders:[7,1]});
 if(!data)return <p>Loading tax dashboard…</p>;
 return <><section><h2>Tax dashboard</h2><p>{data.profile?taxUiLabel(data.profile.structure):'Tax profile requires review'} · Reconciliation: {data.reconciliation.reconciled?'reconciled':'review required'} · Difference {data.reconciliation.difference} {data.reconciliation.currency}</p><p>{data.draft_returns.length} draft/reviewed returns · {data.certificates_outstanding} withholding certificates outstanding · {data.pending_codes.length} inactive or pending codes</p>{auth.selectedOrganisation?.country_code==='GH'&&<p>GRA E-VAT: disabled, not connected or certified.</p>}<h3>Registrations</h3>{data.registrations.map(r=><p key={r.id}>{r.obligation} · {r.status} · From {r.effective_from}</p>)}<h3>Upcoming and overdue deadlines</h3>{!data.deadlines.length&&<p>No verified deadlines recorded.</p>}{data.deadlines.map(d=><article key={d.id}><strong>{d.due_date} · {d.status}{d.reminder_due?' · Reminder due':''}</strong><p>{d.period_start} – {d.period_end} · {d.rule_source} · version {d.rule_version}</p><p>Responsible user: {data.members.find(m=>m.id===d.responsible_user)?.name||'Recorded user'} · Reminders: {d.reminders.join(', ')} days before due</p>{auth.hasPermission(d.status==='OPEN'?'record_tax_filing':'record_tax_payment')&&<button disabled={busy} onClick={()=>setCalendarAction({calendar_id:d.id,status:d.status==='OPEN'?'FILED':'PAID',reference:'',reason:''})}>Record {d.status==='OPEN'?'filing acknowledgement':'external payment reference'}</button>}</article>)}</section>
 {calendarAction&&<section><h2>Record actual obligation activity</h2><p>This updates obligation tracking. Accounting payments are recorded separately through the return payment workflow.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api.post('tax/configuration/calendar-status/',{calendar_id:calendarAction.calendar_id,status:calendarAction.status,reason:calendarAction.reason,[calendarAction.status==='FILED'?'acknowledgement':'payment_reference']:calendarAction.reference});setCalendarAction(null);});}}><label>Actual reference<input required value={calendarAction.reference} onChange={e=>setCalendarAction({...calendarAction,reference:e.target.value})}/></label><label>Reason<input required value={calendarAction.reason} onChange={e=>setCalendarAction({...calendarAction,reason:e.target.value})}/></label><button disabled={busy}>Record activity</button></form></section>}
 <section><h2>Supporting obligation documents</h2>{data.supporting_documents.map(d=><p key={d.id}><button disabled={busy} onClick={()=>run(async()=>saveBlob(await api.download(`tax/returns/evidence/${d.id}/download/`),d.filename))}>{d.filename}</button> · {d.notes}</p>)}{auth.hasPermission('configure_tax')&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{const body=new FormData();body.append('registration_id',support.registration_id);body.append('notes',support.notes);body.append('file',support.file);await api.postForm('tax/configuration/obligation-evidence/',body);});}}><label>Registered obligation<select required value={support.registration_id} onChange={e=>setSupport({...support,registration_id:e.target.value})}><option value="">Select</option>{data.registrations.map(r=><option key={r.id} value={r.id}>{r.obligation}</option>)}</select></label><label>Source / notes<input required value={support.notes} onChange={e=>setSupport({...support,notes:e.target.value})}/></label><label>Private PDF, PNG or JPEG<input required type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setSupport({...support,file:e.target.files[0]||null})}/></label><button disabled={busy||!support.file}>Upload supporting document</button></form>}</section>
 {auth.hasPermission('configure_tax')&&<section><h2>Record a verified filing deadline</h2><p>Tracking only. Enter the official source and rule version; dates are not inferred from tax names.</p><form onSubmit={e=>{e.preventDefault();void run(()=>api.post('tax/configuration/calendar/',{...calendar,payment_due_date:calendar.payment_due_date||null,responsible_user_id:calendar.responsible_user_id}));}}><div className="tax-config-grid"><label>Registration<select required value={calendar.registration_id} onChange={e=>setCalendar({...calendar,registration_id:e.target.value})}><option value="">Select</option>{data.registrations.map(r=><option key={r.id} value={r.id}>{r.obligation}</option>)}</select></label>{[['period_start','Period start'],['period_end','Period end'],['due_date','Filing due'],['payment_due_date','Payment due'],['source','Verified source'],['rule_version','Effective rule version']].map(([key,label])=><label key={key}>{label}<input required={key!=='payment_due_date'} type={['source','rule_version'].includes(key)?'text':'date'} value={calendar[key]} onChange={e=>setCalendar({...calendar,[key]:e.target.value})}/></label>)}</div><label>Responsible user<select required value={calendar.responsible_user_id} onChange={e=>setCalendar({...calendar,responsible_user_id:e.target.value})}>{data.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button disabled={busy}>Save verified deadline</button></form></section>}</>;
}
