import { useEffect, useState } from 'react';
import { useAuth } from '../../store/AuthContext';
import { api } from '../../services/api';
import { normaliseApiError } from '../../services/apiError';
export default function WithholdingFields({items,onChange,supplier=false,sourceId,date,amount}){
 const { selectedOrganisation } = useAuth();
 const previewKey = JSON.stringify({items,supplier,sourceId,date,amount});
 const [codes,setCodes]=useState([]),[error,setError]=useState(''),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;api.get('tax/configuration/codes/').then(rows=>{if(live)setCodes(rows.filter(c=>['WHT','VAT_WHT'].includes(c.family)));}).catch(e=>{if(live)setError(normaliseApiError(e));});return()=>{live=false;};},[]);
 const change=(index,key,value)=>{setPreview(null);onChange(items.map((item,i)=>i===index?{...item,[key]:value}:item));};
 if(!codes.length)return null;
 return <details className="document-withholding"><summary>Withholding tax / certificate</summary><p>The payment amount is the gross settlement. Verified withholding reduces cash paid or received; it does not reduce invoice VAT.</p>{items.map((item,i)=><fieldset key={i}><legend>Withholding {i+1}</legend><label>Verified tax code<select required value={item.tax_code_id} onChange={e=>change(i,'tax_code_id',e.target.value)}><option value="">Select code</option>{codes.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><label>Withholdee tax identifier<input required value={item.tax_identifier} onChange={e=>change(i,'tax_identifier',e.target.value)}/></label><label>Residence<select value={item.residence} onChange={e=>change(i,'residence',e.target.value)}><option>RESIDENT</option><option>NONRESIDENT</option></select></label><label>Country of residence<input required maxLength={2} value={item.country} onChange={e=>change(i,'country',e.target.value.toUpperCase())}/></label><label>Contract amount<input required inputMode="decimal" value={item.contract_amount} onChange={e=>change(i,'contract_amount',e.target.value)}/></label><label>Certificate / reference<input required={!supplier||codes.find(c=>c.id===item.tax_code_id)?.family==='VAT_WHT'} value={item.certificate} onChange={e=>change(i,'certificate',e.target.value)}/></label><label>Certificate date<input type="date" value={item.certificate_date} onChange={e=>change(i,'certificate_date',e.target.value)}/></label><label><input required type="checkbox" checked={item.eligibility_confirmed} onChange={e=>change(i,'eligibility_confirmed',e.target.checked)}/>I confirm eligibility for this verified withholding code</label><label><input type="checkbox" checked={item.counterparty_vat_registered} onChange={e=>change(i,'counterparty_vat_registered',e.target.checked)}/>Counterparty is VAT registered (VAT withholding)</label><button type="button" onClick={()=>{onChange(items.filter((_,index)=>index!==i));setPreview(null);}}>Remove withholding</button></fieldset>)}{items.length<2&&<button type="button" onClick={()=>onChange([...items,{tax_code_id:'',tax_identifier:'',country:selectedOrganisation?.country_code || '',residence:'RESIDENT',contract_amount:amount,certificate:'',certificate_date:date,eligibility_confirmed:false,counterparty_vat_registered:false}])}>Add withholding</button>}{items.length>0&&<button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setPreview({key:previewKey,...await api.post('tax/configuration/withholding-preview/',{supplier_payment:supplier,source_id:sourceId,date,amount,withholdings:items})});}catch(e){setError(normaliseApiError(e));}finally{setBusy(false);}}}>Preview net cash</button>}{error&&<p role="alert">{error}</p>}{preview?.key===previewKey&&<p>Gross {preview.gross} · Withheld {preview.withheld} · Cash {preview.net} {preview.currency}</p>}</details>;
}
