// Display stock and submit movements while backend WAC services remain authoritative.

import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";

import PageHeader from "../../components/layout/PageHeader";
import TablePagination from "../../components/common/TablePagination";
import { useTablePagination } from "../../hooks/useTablePagination";
import { accountingApiService } from "../../services/accountingApiService";
import { normaliseApiError } from "../../services/apiError";
import { inventoryService } from "../../services/inventoryService";
import { useAuth } from "../../store/AuthContext";

import "../../styles/products.css";
import "../../styles/productDetails.css";
import "../../styles/stockAdjustments.css";
import "../../styles/chartOfAccounts.css";

const today = () => new Date().toISOString().slice(0, 10);
const show = (value) => {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value === "object") return value.name || value.code || JSON.stringify(value);
  return String(value);
};
function State({ loading, error, children }) {
  if (loading) return <div className="inventory-state inventory-state-loading">Loading inventory data…</div>;
  if (error) return <div className="invoice-form-alert inventory-state">{error}</div>;
  return children;
}
function Table({ rows, actions }) {
  const values = Array.isArray(rows) ? rows : [];
  const pagination = useTablePagination(values);
  if (!values.length) return <div className="inventory-empty-state"><strong>No records found</strong><span>Records will appear here when inventory activity is available.</span></div>;
  const columns = [...new Set(values.flatMap((row) => Object.keys(row || {})))].filter((key) => !["id", "created_at", "updated_at", "accounts"].includes(key));
  return <><div className="chart-accounts-table-wrapper inventory-table-wrapper"><table className="chart-accounts-table inventory-table"><thead><tr>{columns.map((key) => <th key={key}>{key.replaceAll("_", " ")}</th>)}{actions && <th className="inventory-actions-heading">Actions</th>}</tr></thead><tbody>{pagination.pageRows.map((row, index) => <tr key={row.id || index}>{columns.map((key) => <td key={key}>{key === "status" ? <span className={`inventory-status inventory-status-${String(row[key]).toLowerCase().replaceAll("_", "-")}`}>{show(row[key])}</span> : key === "movement_type" ? <span className={`inventory-movement-type ${String(row[key]).endsWith("_in") ? "inventory-movement-type-in" : "inventory-movement-type-out"}`}>{show(row[key]).replaceAll("_", " ")}</span> : show(row[key])}</td>)}{actions && <td><div className="inventory-row-actions">{actions(row)}</div></td>}</tr>)}</tbody></table></div><TablePagination {...pagination}/></>;
}

export function LiveProductsPage() {
  const auth = useAuth(); const [products, setProducts] = useState([]); const [warehouses, setWarehouses] = useState([]); const [valuation, setValuation] = useState(null);
  const [message, setMessage] = useState("");
  const [productForm, setProductForm] = useState({ code: "", name: "", product_type: "goods" });
  const [warehouseForm, setWarehouseForm] = useState({ code: "", name: "" });
  const [state, setState] = useState({ loading: true, error: "" });
  const load = useCallback(async () => { setState({ loading: true, error: "" }); try { const [items, locations, values] = await Promise.all([inventoryService.products(), inventoryService.warehouses(), inventoryService.valuation()]); setProducts(items); setWarehouses(locations); setValuation(values); setState({ loading: false, error: "" }); } catch (error) { setState({ loading: false, error: normaliseApiError(error) }); } }, []);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, [load]);
  const createProduct = async (event) => { event.preventDefault(); setMessage(""); try { await inventoryService.createProduct({ ...productForm, description: "", unit: "each", sales_price: "0.00", purchase_price: "0.00", currency: auth.selectedOrganisation?.base_currency || "GBP", track_inventory: productForm.product_type === "goods", status: "active" }); setProductForm({ code: "", name: "", product_type: "goods" }); setMessage("Product created."); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  const createWarehouse = async (event) => { event.preventDefault(); setMessage(""); try { await inventoryService.createWarehouse({ ...warehouseForm, description: "", address_line_1: "", address_line_2: "", city: "", county_state: "", postcode: "", country: "", status: "active", is_default: warehouses.length === 0 }); setWarehouseForm({ code: "", name: "" }); setMessage("Warehouse created."); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  const toggleProduct = async (product) => { setMessage(""); try { await inventoryService.updateProduct(product.id, { status: product.status === "active" ? "inactive" : "active" }); setMessage("Product status updated."); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  const toggleWarehouse = async (warehouse) => { setMessage(""); try { await inventoryService.updateWarehouse(warehouse.id, { status: warehouse.status === "active" ? "inactive" : "active" }); setMessage("Warehouse status updated."); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  const valuationRows = Array.isArray(valuation) ? valuation : valuation?.rows || valuation?.items || [];
  return <div className="products-page"><PageHeader eyebrow="Inventory" title="Products and stock" description="Manage products, warehouses, stock levels, and inventory valuation." />{message && <p className="invoice-form-alert">{message}</p>}
    {auth.hasPermission("manage_products") && <form className="invoice-form-card" onSubmit={createProduct}><h2>Add product</h2><label>Code <input required value={productForm.code} onChange={(event) => setProductForm((current) => ({ ...current, code: event.target.value }))} /></label><label>Name <input required value={productForm.name} onChange={(event) => setProductForm((current) => ({ ...current, name: event.target.value }))} /></label><label>Type <select value={productForm.product_type} onChange={(event) => setProductForm((current) => ({ ...current, product_type: event.target.value }))}><option value="goods">Goods</option><option value="service">Service</option></select></label><button className="page-primary-button" type="submit">Create product</button></form>}
    {auth.hasPermission("manage_warehouses") && <form className="invoice-form-card" onSubmit={createWarehouse}><h2>Add warehouse</h2><label>Code <input required value={warehouseForm.code} onChange={(event) => setWarehouseForm((current) => ({ ...current, code: event.target.value }))} /></label><label>Name <input required value={warehouseForm.name} onChange={(event) => setWarehouseForm((current) => ({ ...current, name: event.target.value }))} /></label><button className="page-primary-button" type="submit">Create warehouse</button></form>}
    <State {...state}><section className="invoice-form-card"><h2>Products</h2><Table rows={products} actions={(product) => <><Link className="invoice-secondary-button" to={`/inventory/products/${product.id}`}>View stock</Link>{auth.hasPermission("manage_products") && <button className="invoice-secondary-button" onClick={() => void toggleProduct(product)}>{product.status === "active" ? "Deactivate" : "Activate"}</button>}</>} /></section>
      <section className="invoice-form-card"><h2>Warehouses</h2><Table rows={warehouses} actions={auth.hasPermission("manage_warehouses") ? (warehouse) => <button className="invoice-secondary-button" onClick={() => void toggleWarehouse(warehouse)}>{warehouse.status === "active" ? "Deactivate" : "Activate"}</button> : null} /></section>
      <section className="invoice-form-card"><h2>Inventory valuation</h2><Table rows={valuationRows} />{valuation && !valuationRows.length && <pre>{JSON.stringify(valuation, null, 2)}</pre>}</section></State>
  </div>;
}

export function LiveProductDetailsPage() {
  const { productId } = useParams(); const [product, setProduct] = useState(null); const [stock, setStock] = useState(null); const [movements, setMovements] = useState([]); const [state, setState] = useState({ loading: true, error: "" });
  const load = useCallback(async () => { setState({ loading: true, error: "" }); try { const [item, summary, allMovements] = await Promise.all([inventoryService.product(productId), inventoryService.productStock(productId), inventoryService.movements()]); setProduct(item); setStock(summary); setMovements(allMovements.filter((movement) => movement.product?.id === productId)); setState({ loading: false, error: "" }); } catch (error) { setState({ loading: false, error: normaliseApiError(error) }); } }, [productId]);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, [load]);
  const stockRows = Array.isArray(stock) ? stock : stock?.warehouses || stock?.rows || (stock ? [stock] : []);
  return <div className="product-details-page"><PageHeader eyebrow="Inventory" title={product?.name || "Product details"} description="Current stock and perpetual weighted-average movement history." action={<Link className="invoice-secondary-button" to="/inventory/products">Back to products</Link>} /><State {...state}>{product && <section className="invoice-form-card"><h2>{product.code} · {product.name}</h2><p>{product.description || "No description"}</p><p>Status: {product.status}</p></section>}<section className="invoice-form-card"><h2>Stock summary</h2><Table rows={stockRows} /></section><section className="invoice-form-card"><h2>Movement history</h2><Table rows={movements} /></section></State></div>;
}

export function LiveStockAdjustmentPage() {
  const auth = useAuth(); const [products, setProducts] = useState([]); const [warehouses, setWarehouses] = useState([]); const [accounts, setAccounts] = useState([]); const [movements, setMovements] = useState([]); const [message, setMessage] = useState(""); const [state, setState] = useState({ loading: true, error: "" });
  const [historySearch, setHistorySearch] = useState("");
  const [historyType, setHistoryType] = useState("all");
  const [form, setForm] = useState({ product_id: "", warehouse_id: "", adjustment_date: today(), adjustment_type: "adjustment_in", quantity: "", unit_cost: "", offset_account_id: "", reference: "", description: "" });
  const load = useCallback(async () => { setState({ loading: true, error: "" }); try { const [items, locations, ledgers, history] = await Promise.all([inventoryService.products(), inventoryService.warehouses(), accountingApiService.accounts({ status: "active" }), inventoryService.movements()]); setProducts(items.filter((item) => item.track_inventory)); setWarehouses(locations.filter((item) => item.status === "active")); setAccounts(ledgers); setMovements(history.filter((item) => ["adjustment_in", "adjustment_out"].includes(item.movement_type))); setState({ loading: false, error: "" }); } catch (error) { setState({ loading: false, error: normaliseApiError(error) }); } }, []);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, [load]);
  const change = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setMessage(""); try { await inventoryService.createAdjustment(form); setMessage("Stock adjustment posted successfully."); setForm((value) => ({ ...value, quantity: "", unit_cost: "", reference: "", description: "" })); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  const visibleMovements = movements.filter((item) => {
    const matchesType = historyType === "all" || item.movement_type === historyType;
    const text = [item.reference, item.description, item.product?.code, item.product?.name, item.warehouse?.code, item.warehouse?.name].filter(Boolean).join(" ").toLowerCase();
    return matchesType && text.includes(historySearch.trim().toLowerCase());
  });
  const increases = movements.filter((item) => item.movement_type === "adjustment_in");
  const decreases = movements.filter((item) => item.movement_type === "adjustment_out");
  const sumQuantity = (items) => items.reduce((total, item) => total + Number(item.quantity || 0), 0).toLocaleString(undefined, { maximumFractionDigits: 4 });
  return <div className="stock-adjustments-page"><PageHeader eyebrow="Inventory" title="Stock adjustments" description="Correct physical stock differences through controlled, fully auditable WAC postings." /><State {...state}>
    <section className="stock-adjustment-summary"><article><span>Total adjustments</span><strong>{movements.length}</strong><small>Posted inventory corrections</small></article><article className="stock-adjustment-summary-in"><span>Quantity increased</span><strong>{sumQuantity(increases)}</strong><small>{increases.length} incoming adjustments</small></article><article className="stock-adjustment-summary-out"><span>Quantity decreased</span><strong>{sumQuantity(decreases)}</strong><small>{decreases.length} outgoing adjustments</small></article></section>
    {auth.hasPermission("adjust_stock") ? <form className={`invoice-form-card stock-adjustment-form stock-adjustment-form-${form.adjustment_type === "adjustment_in" ? "in" : "out"}`} onSubmit={submit}><div className="stock-adjustment-form-heading"><div><span className="stock-adjustment-kicker">New inventory correction</span><h2>{form.adjustment_type === "adjustment_in" ? "Increase stock" : "Decrease stock"}</h2><p>{form.adjustment_type === "adjustment_in" ? "Add quantity and value using the entered unit cost." : "Reduce quantity using the current weighted-average cost."}</p></div><span className={`stock-adjustment-direction ${form.adjustment_type === "adjustment_in" ? "stock-adjustment-direction-in" : "stock-adjustment-direction-out"}`}>{form.adjustment_type === "adjustment_in" ? "Stock in" : "Stock out"}</span></div><label>Product <select required name="product_id" value={form.product_id} onChange={change}><option value="">Select a product</option>{products.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Warehouse <select required name="warehouse_id" value={form.warehouse_id} onChange={change}><option value="">Select a warehouse</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Adjustment date <input required type="date" name="adjustment_date" value={form.adjustment_date} onChange={change} /></label><label>Direction <select name="adjustment_type" value={form.adjustment_type} onChange={change}><option value="adjustment_in">Increase stock</option><option value="adjustment_out">Decrease stock</option></select></label><label>Quantity <input required min="0.0001" step="0.0001" type="number" name="quantity" placeholder="0.0000" value={form.quantity} onChange={change} /></label><label>Unit cost <input required min="0" step="0.00000001" type="number" name="unit_cost" placeholder="0.00" value={form.unit_cost} onChange={change} /></label><label>Offset account <select required name="offset_account_id" value={form.offset_account_id} onChange={change}><option value="">Select an account</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Reference <input name="reference" placeholder="e.g. COUNT-2026-001" value={form.reference} onChange={change} /></label><label className="stock-adjustment-description">Description <input name="description" placeholder="Explain why this adjustment is required" value={form.description} onChange={change} /></label><div className="stock-adjustment-submit"><span>This action posts an inventory movement and its accounting entry.</span><button className="page-primary-button" type="submit">Post adjustment</button></div>{message && <p>{message}</p>}</form> : <div className="invoice-form-alert">You do not have permission to adjust stock.</div>}
    <section className="invoice-form-card stock-adjustment-history"><div className="stock-adjustment-history-heading"><div><h2>Adjustment history</h2><p>Review stock corrections and the reason each change was posted.</p></div><span>{visibleMovements.length} records</span></div><div className="stock-adjustment-history-filters"><label>Search<input type="search" placeholder="Product, warehouse or reference…" value={historySearch} onChange={(event) => setHistorySearch(event.target.value)} /></label><label>Direction<select value={historyType} onChange={(event) => setHistoryType(event.target.value)}><option value="all">All adjustments</option><option value="adjustment_in">Stock increases</option><option value="adjustment_out">Stock decreases</option></select></label></div><Table rows={visibleMovements} /></section>
  </State></div>;
}

const workflowConfig = {
  "purchase-receipts": { title: "Purchase receipts", submit: "receivePurchase", needsCost: true, needsAccount: true },
  "sales-issues": { title: "Sales issues", submit: "issueSale", needsDocument: true },
  transfers: { title: "Stock transfers", submit: "transfer", needsDestination: true },
  "customer-returns": { title: "Customer returns", submit: "customerReturn", needsDocument: true, needsMovement: true },
  "supplier-returns": { title: "Supplier returns", submit: "supplierReturn", needsAccount: true },
};

export function LiveInventoryWorkflowPage({ kind }) {
  const config = workflowConfig[kind];
  const [products, setProducts] = useState([]); const [warehouses, setWarehouses] = useState([]);
  const [accounts, setAccounts] = useState([]); const [transactions, setTransactions] = useState([]);
  const [message, setMessage] = useState(""); const [state, setState] = useState({ loading: true, error: "" });
  const [form, setForm] = useState({ product_id: "", warehouse_id: "", destination_warehouse_id: "", transaction_date: today(), quantity: "", unit_cost: "", account_id: "", source_document_id: "", original_movement_id: "", reference: "", description: "" });
  const load = useCallback(async () => { setState({ loading: true, error: "" }); try { const [items, locations, ledgers, history] = await Promise.all([inventoryService.products(), inventoryService.warehouses(), accountingApiService.accounts({ status: "active" }), inventoryService.transactions()]); setProducts(items.filter((item) => item.track_inventory)); setWarehouses(locations.filter((item) => item.status === "active")); setAccounts(ledgers); setTransactions(history.filter((item) => item.transaction_type === (kind === "transfers" ? "transfer" : kind.replace(/s$/, "").replaceAll("-", "_")))); setState({ loading: false, error: "" }); } catch (error) { setState({ loading: false, error: normaliseApiError(error) }); } }, [kind]);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, [load]);
  const change = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setMessage(""); const payload = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== "")); try { await inventoryService[config.submit](payload); setMessage(`${config.title} posted successfully.`); setForm((value) => ({ ...value, quantity: "", reference: "", description: "" })); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  return <div className="stock-adjustments-page"><PageHeader eyebrow="Inventory" title={config.title} description="Post this inventory workflow through the perpetual weighted-average costing engine." /><State {...state}><form className="invoice-form-card" onSubmit={submit}><h2>New transaction</h2><label>Product <select required name="product_id" value={form.product_id} onChange={change}><option value="">Select</option>{products.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Warehouse <select required name="warehouse_id" value={form.warehouse_id} onChange={change}><option value="">Select</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>{config.needsDestination && <label>Destination <select required name="destination_warehouse_id" value={form.destination_warehouse_id} onChange={change}><option value="">Select</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>}<label>Date <input required type="date" name="transaction_date" value={form.transaction_date} onChange={change} /></label><label>Quantity <input required min="0.0001" step="0.0001" type="number" name="quantity" value={form.quantity} onChange={change} /></label>{config.needsCost && <label>Unit cost <input required min="0" step="0.00000001" type="number" name="unit_cost" value={form.unit_cost} onChange={change} /></label>}{config.needsAccount && <label>GRNI / settlement account <select required name="account_id" value={form.account_id} onChange={change}><option value="">Select</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>}{config.needsDocument && <label>Invoice ID <input required name="source_document_id" value={form.source_document_id} onChange={change} /></label>}{config.needsMovement && <label>Original issue movement ID <input required name="original_movement_id" value={form.original_movement_id} onChange={change} /></label>}<label>Reference <input required name="reference" value={form.reference} onChange={change} /></label><label>Description <input name="description" value={form.description} onChange={change} /></label><button className="page-primary-button" type="submit">Post</button>{message && <p>{message}</p>}</form><section className="invoice-form-card"><h2>History</h2><Table rows={transactions} /></section></State></div>;
}

export function LiveStockCountsPage() {
  const [counts, setCounts] = useState([]); const [products, setProducts] = useState([]); const [warehouses, setWarehouses] = useState([]); const [accounts, setAccounts] = useState([]); const [entered, setEntered] = useState({}); const [message, setMessage] = useState(""); const [state, setState] = useState({ loading: true, error: "" });
  const [form, setForm] = useState({ warehouse_id: "", count_date: today(), reference: "", offset_account_id: "", product_ids: [] });
  const load = useCallback(async () => { try { const [history, items, locations, ledgers] = await Promise.all([inventoryService.stockCounts(), inventoryService.products(), inventoryService.warehouses(), accountingApiService.accounts({ status: "active" })]); setCounts(history); setProducts(items.filter((item) => item.track_inventory)); setWarehouses(locations.filter((item) => item.status === "active")); setAccounts(ledgers); setState({ loading: false, error: "" }); } catch (error) { setState({ loading: false, error: normaliseApiError(error) }); } }, []);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, [load]);
  const create = async (event) => { event.preventDefault(); try { await inventoryService.createStockCount(form); setMessage("Draft stock count created."); setForm((value) => ({ ...value, reference: "", product_ids: [] })); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  const start = async (row) => { try { await inventoryService.startStockCount(row.id); setMessage("Stock count is now counting."); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  const post = async (row) => { const values = Object.fromEntries(row.lines.map((line) => [line.product.id, entered[`${row.id}:${line.product.id}`] ?? line.expected_quantity])); try { await inventoryService.postStockCount(row.id, values); setMessage("Stock count variance posted."); await load(); } catch (error) { setMessage(normaliseApiError(error)); } };
  return <div className="stock-adjustments-page"><PageHeader eyebrow="Inventory" title="Stock counts" description="Review draft, counting, and posted stock takes with variance audit history." />{message && <p className="invoice-form-alert">{message}</p>}<State {...state}><form className="invoice-form-card" onSubmit={create}><h2>New stock count</h2><label>Warehouse <select required value={form.warehouse_id} onChange={(event) => setForm((value) => ({ ...value, warehouse_id: event.target.value }))}><option value="">Select</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Count date <input required type="date" value={form.count_date} onChange={(event) => setForm((value) => ({ ...value, count_date: event.target.value }))} /></label><label>Reference <input required value={form.reference} onChange={(event) => setForm((value) => ({ ...value, reference: event.target.value }))} /></label><label>Variance account <select required value={form.offset_account_id} onChange={(event) => setForm((value) => ({ ...value, offset_account_id: event.target.value }))}><option value="">Select</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Products <select required multiple value={form.product_ids} onChange={(event) => setForm((value) => ({ ...value, product_ids: [...event.target.selectedOptions].map((option) => option.value) }))}>{products.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><button className="page-primary-button" type="submit">Create draft</button></form>{counts.map((row) => <section className="invoice-form-card" key={row.id}><h2>{row.reference} · {row.status}</h2><p>Count date: {row.count_date}</p>{row.lines.map((line) => <label key={line.id}>{line.product.code} · expected {line.expected_quantity}<input disabled={row.status !== "counting"} min="0" step="0.0001" type="number" value={entered[`${row.id}:${line.product.id}`] ?? line.counted_quantity ?? line.expected_quantity} onChange={(event) => setEntered((value) => ({ ...value, [`${row.id}:${line.product.id}`]: event.target.value }))} /></label>)}{row.status === "draft" && <button className="invoice-secondary-button" onClick={() => void start(row)}>Start count</button>}{row.status === "counting" && <button className="page-primary-button" onClick={() => void post(row)}>Post variance</button>}</section>)}</State></div>;
}

export function LiveInventoryReportsPage() {
  const reports = ["valuation", "stock-on-hand", "movements", "negative-stock", "slow-moving", "fast-moving", "reorder"];
  const [name, setName] = useState("movements"); const [rows, setRows] = useState([]); const [state, setState] = useState({ loading: true, error: "" });
  const [search, setSearch] = useState("");
  const [movementType, setMovementType] = useState("all");
  useEffect(() => { let current = true; const frame = window.requestAnimationFrame(() => { inventoryService.report(name).then((data) => { if (!current) return; setRows(Array.isArray(data) ? data : data.items || []); setState({ loading: false, error: "" }); }).catch((error) => current && setState({ loading: false, error: normaliseApiError(error) })); }); return () => { current = false; window.cancelAnimationFrame(frame); }; }, [name]);
  const movementTypes = useMemo(() => [...new Set(rows.map((row) => row.movement_type).filter(Boolean))].sort(), [rows]);
  const visibleRows = useMemo(() => rows.filter((row) => {
    if (name !== "movements") return true;
    const matchesType = movementType === "all" || row.movement_type === movementType;
    const haystack = [row.reference, row.description, row.product?.name, row.product?.code, row.warehouse?.name, row.warehouse?.code, row.movement_type].filter(Boolean).join(" ").toLowerCase();
    return matchesType && haystack.includes(search.trim().toLowerCase());
  }), [movementType, name, rows, search]);
  const incomingCount = rows.filter((row) => String(row.movement_type || "").match(/in$|receipt|return_in|completion/)).length;
  const outgoingCount = rows.filter((row) => String(row.movement_type || "").match(/out$|issue|return_out|scrap/)).length;
  const reportTitle = name.replaceAll("-", " ");
  return <div className="products-page inventory-reports-page"><PageHeader eyebrow="Inventory" title={name === "movements" ? "Stock movements" : "Inventory reports"} description={name === "movements" ? "Review every stock increase and decrease with product, warehouse, quantity, cost, and posting context." : "Live operational and perpetual WAC inventory reporting."} />
    <section className="inventory-report-toolbar"><label>Report view<select value={name} onChange={(event) => { setState({ loading: true, error: "" }); setSearch(""); setMovementType("all"); setName(event.target.value); }}>{reports.map((item) => <option key={item} value={item}>{item.replaceAll("-", " ")}</option>)}</select></label>{name === "movements" && <><label className="inventory-report-search">Search movements<input type="search" placeholder="Product, warehouse or reference…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label>Movement type<select value={movementType} onChange={(event) => setMovementType(event.target.value)}><option value="all">All movement types</option>{movementTypes.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label></>}</section>
    {name === "movements" && <section className="inventory-movement-summary"><article><span>Total movements</span><strong>{rows.length}</strong><small>All recorded stock activity</small></article><article className="inventory-summary-in"><span>Incoming</span><strong>{incomingCount}</strong><small>Receipts and stock increases</small></article><article className="inventory-summary-out"><span>Outgoing</span><strong>{outgoingCount}</strong><small>Issues and stock reductions</small></article><article><span>Showing</span><strong>{visibleRows.length}</strong><small>After current filters</small></article></section>}
    <State {...state}><section className="invoice-form-card inventory-report-panel"><div className="inventory-report-heading"><div><h2>{reportTitle}</h2><p>{name === "movements" ? "A chronological audit trail of inventory quantity and value changes." : "Current results from the inventory reporting service."}</p></div><span>{visibleRows.length} {visibleRows.length === 1 ? "record" : "records"}</span></div><Table rows={visibleRows} /></section></State>
  </div>;
}
