import { useMemo,useRef,useState } from "react";
import { Download,FileSpreadsheet,Search,Upload,X } from "lucide-react";
import TablePagination from "../common/TablePagination";
import { useTablePagination } from "../../hooks/useTablePagination";
import { contactService } from "../../services/contactService";
import { normaliseApiError } from "../../services/apiError";

const save=(blob,name)=>{const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);};
export default function ContactImportModal({type,onClose,onCompleted}){const plural=type==="customer"?"Customers":"Suppliers",permission=type==="customer"?"import_customers":"import_suppliers";void permission;const input=useRef(null);const [file,setFile]=useState(null),[batch,setBatch]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState(""),[mode,setMode]=useState("stop_on_existing");const rows=useMemo(()=>(batch?.rows||[]).filter(row=>(!filter||row.status===filter)&&`${row.data.name} ${row.data.account_number} ${row.data.email}`.toLowerCase().includes(search.toLowerCase())),[batch,filter,search]),paging=useTablePagination(rows);
 const download=async()=>{setBusy(true);try{save(await contactService.importTemplate(type),`Ledgify_${type[0].toUpperCase()+type.slice(1)}_Import_Template.xlsx`);}catch(e){setError(normaliseApiError(e));}finally{setBusy(false);}};
 const preview=async()=>{setBusy(true);setError("");try{setBatch(await contactService.importPreview(type,file,mode));}catch(e){setError(normaliseApiError(e,`The ${type} workbook could not be validated.`));}finally{setBusy(false);}};
 const confirm=async()=>{setBusy(true);setError("");try{const result=await contactService.importConfirm(type,batch.id);setBatch(result);await onCompleted(result);}catch(e){setError(normaliseApiError(e,`The ${type} import could not be completed.`));}finally{setBusy(false);}};
 return <div className="account-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="account-modal account-import-modal" role="dialog" aria-modal="true" aria-labelledby="contact-import-title"><header className="account-modal-header"><div><span>{plural}</span><h2 id="contact-import-title">Import {plural}</h2><p>Validate a Ledgify Excel template before creating any records.</p></div><button className="account-modal-close" onClick={onClose} aria-label="Close"><X/></button></header><div className="account-form"><ol className="account-import-steps"><li className="active">Download Template</li><li className={file?"active":""}>Upload File</li><li className={batch?"active":""}>Validate and Preview</li><li className={batch&&!batch.error_rows?"active":""}>Confirm Import</li><li className={batch?.status==="completed"?"active":""}>Import Results</li></ol>{error&&<div className="account-form-error" role="alert">{error}</div>}
 {!batch&&<><section className="account-form-section"><div><h3>1. Download template</h3><p>Includes exact contact fields, ISO currencies, payment terms and non-importable examples.</p></div><button className="invoice-secondary-button" disabled={busy} onClick={download}><Download/>Download {type} template</button></section><section className="account-form-section"><div><h3>2. Upload workbook</h3><p>Macro-free .xlsx · maximum 5 MB · maximum 2,000 rows.</p></div><button className="account-import-dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFile(e.dataTransfer.files[0]||null);}}><Upload/><strong>{file?file.name:"Choose or drop an .xlsx file"}</strong><span>{file?`${(file.size/1024).toFixed(1)} KB`:"Validation happens securely on the server"}</span></button><input hidden ref={input} type="file" accept=".xlsx" onChange={e=>setFile(e.target.files[0]||null)}/><label>Duplicate policy<select value={mode} onChange={e=>setMode(e.target.value)}><option value="stop_on_existing">Stop when existing records are found</option><option value="skip_existing">Skip existing records and import new records</option></select></label></section></>}
 {batch&&<>{batch.status==="completed"?<section className="chart-accounts-success"><FileSpreadsheet/><div><strong>Import completed</strong><p>{batch.created_record_ids.length} {plural.toLowerCase()} created, {batch.skipped_rows} skipped. Batch {batch.id}</p></div></section>:<><div className="account-import-summary">{[["Total Rows",batch.total_rows],["Ready",batch.valid_rows],["Warnings",batch.warning_rows],["Errors",batch.error_rows],["Existing",batch.duplicate_rows]].map(([name,value])=><article key={name}><span>{name}</span><strong>{value}</strong></article>)}</div><div className="chart-accounts-toolbar"><label className="chart-account-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${plural.toLowerCase()}`}/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{["ready","warning","error","existing"].map(value=><option key={value}>{value}</option>)}</select>{batch.error_rows>0&&<button className="invoice-secondary-button" onClick={async()=>save(await contactService.importErrors(type,batch.id),`Ledgify_${type}_Import_Errors.csv`)}>Download Error Report</button>}</div><div className="chart-accounts-table-wrapper"><table className="chart-accounts-table"><thead><tr><th>Row</th><th>Name</th><th>Account number</th><th>Contact</th><th>Email</th><th>Phone</th><th>Currency</th><th>Status</th><th>Messages</th></tr></thead><tbody>{paging.pageRows.map(row=><tr key={row.row_number}><td>{row.row_number}</td><td>{row.data.name||"—"}</td><td>{row.data.account_number||"—"}</td><td>{row.data.contact_name||"—"}</td><td>{row.data.email||"—"}</td><td>{row.data.phone||"—"}</td><td>{row.data.currency}</td><td>{row.status}</td><td>{[...row.errors,...row.warnings].map(item=>item.message).join(" ")||"Ready"}</td></tr>)}</tbody></table></div><TablePagination {...paging}/></>}</>}
 <footer className="account-modal-actions">{batch?.status==="completed"&&<button className="invoice-secondary-button" onClick={async()=>save(await contactService.importErrors(type,batch.id),`Ledgify_${type}_Import_Results.csv`)}>Download Result Report</button>}<button className="invoice-secondary-button" onClick={onClose}>{batch?.status==="completed"?"Close":"Cancel"}</button>{!batch&&<button className="page-primary-button" disabled={!file||busy} onClick={preview}>{busy?"Validating…":"Validate and Preview"}</button>}{batch&&batch.status!=="completed"&&<><button className="invoice-secondary-button" onClick={()=>setBatch(null)}>Choose Another File</button><button className="page-primary-button" disabled={busy||batch.error_rows>0} onClick={confirm}>{busy?"Importing…":"Confirm Import"}</button></>}</footer></div></section></div>;
}
