import { useEffect, useRef, useState } from 'react';
import { api } from '../../services/api';
import { normaliseApiError } from '../../services/apiError';
import '../../styles/publicAccess.css';
export default function InvitationManager(){
 const [page,setPage]=useState(1),[data,setData]=useState(null),[form,setForm]=useState({email:'',role:'employee',message:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const guard=useRef(false);
 useEffect(()=>{let live=true;api.get(`organisation-invitations/?page=${page}`).then(v=>{if(live)setData(v);}).catch(e=>{if(live)setError(normaliseApiError(e));});return()=>{live=false;};},[page]);
 async function run(fn){if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await fn();setPage(1);setData(await api.get('organisation-invitations/?page=1'));setNotice('Request accepted. Email status records backend acceptance, not guaranteed delivery.');}catch(e){setError(normaliseApiError(e));}finally{guard.current=false;setBusy(false);}}
 return <section className="access-invitations"><h2>Invite team members</h2><p>The recipient must verify their email and explicitly accept. Existing memberships are never replaced by invitations.</p>{error&&<p role="alert" className="auth-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{data&&<><form onSubmit={e=>{e.preventDefault();void run(()=>api.post('organisation-invitations/',form));}}><div className="access-grid"><label>Recipient email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Intended role<select required value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{data.roles.map(role=><option key={role} value={role}>{role}</option>)}</select></label></div><label>Optional message<textarea maxLength={500} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button disabled={busy}>Send invitation</button></form><h3>Invitations</h3>{!data.invitations.length?<p>No invitations yet.</p>:data.invitations.map(item=><article className="access-invitation-row" key={item.id}><div><strong>{item.email}</strong><p>{item.role} · {item.status} · Email: {item.email_status}</p><small>Expires {item.expires_at.slice(0,10)}</small></div>{item.status==='pending'&&<div><button disabled={busy} onClick={()=>run(()=>api.post(`organisation-invitations/${item.id}/resend/`,{}))}>Resend</button><button disabled={busy} onClick={()=>{if(window.confirm('Revoke this invitation? Its link will stop working.'))void run(()=>api.post(`organisation-invitations/${item.id}/revoke/`,{}));}}>Revoke</button></div>}</article>)}<nav aria-label="Invitation pages"><button disabled={busy||!data.previous} onClick={()=>setPage(p=>p-1)}>Previous invitations</button><span>Page {page} · {data.count} invitations</span><button disabled={busy||!data.next} onClick={()=>setPage(p=>p+1)}>Next invitations</button></nav></>}</section>;
}
